

create table if not exists commerce.marketplace_claim_events (
    id bigint generated by default as identity primary key,
    claim_id bigint not null references commerce.marketplace_claims(id) on delete restrict,
    event_type text not null,
    actor_kind text not null,
    actor_id text not null,
    message text,
    data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint marketplace_claim_events_actor check (actor_kind in ('buyer', 'seller', 'support', 'finance', 'admin', 'system')),
    constraint marketplace_claim_events_data check (jsonb_typeof(data) = 'object')
);

alter table commerce.marketplace_claim_events
    drop constraint if exists marketplace_claim_events_actor;
alter table commerce.marketplace_claim_events
    add constraint marketplace_claim_events_actor check (
        actor_kind in ('buyer', 'seller', 'support', 'finance', 'admin', 'system')
    );

create index if not exists marketplace_claim_events_claim_idx
    on commerce.marketplace_claim_events(claim_id, created_at, id);

create table if not exists commerce.marketplace_claim_evidence (
    id bigint generated by default as identity primary key,
    claim_id bigint not null references commerce.marketplace_claims(id) on delete restrict,
    submitted_by_kind text not null,
    submitted_by text not null,
    storage_bucket text not null,
    storage_path text not null,
    mime_type text not null,
    file_size bigint not null,
    original_filename text not null,
    sha256 text not null,
    description text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint marketplace_claim_evidence_actor check (submitted_by_kind in ('buyer', 'seller', 'support')),
    constraint marketplace_claim_evidence_path_unique unique (storage_bucket, storage_path),
    constraint marketplace_claim_evidence_file_size check (file_size between 1 and 10485760),
    constraint marketplace_claim_evidence_filename check (length(btrim(original_filename)) between 1 and 255),
    constraint marketplace_claim_evidence_sha256 check (sha256 ~ '^[a-f0-9]{64}$'),
    constraint marketplace_claim_evidence_description check (description is null or length(description) <= 1000),
    constraint marketplace_claim_evidence_metadata check (
        jsonb_typeof(metadata) = 'object' and pg_column_size(metadata) <= 8192
    ),
    constraint marketplace_claim_evidence_mime check (
        mime_type in ('image/jpeg', 'image/png', 'image/webp', 'application/pdf', 'video/mp4')
    )
);

create index if not exists marketplace_claim_evidence_claim_idx
    on commerce.marketplace_claim_evidence(claim_id, created_at, id);

do $commerce_claim_evidence_bucket$
begin
    if to_regclass('storage.buckets') is not null then
        execute $sql$
            insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
            values (
                'commerce-claim-evidence', 'commerce-claim-evidence', false, 10485760,
                array['image/jpeg', 'image/png', 'image/webp', 'application/pdf', 'video/mp4']::text[]
            )
            on conflict (id) do update set
                public = false,
                file_size_limit = excluded.file_size_limit,
                allowed_mime_types = excluded.allowed_mime_types
        $sql$;
    end if;
end;
$commerce_claim_evidence_bucket$;

create table if not exists commerce.marketplace_claim_return_events (
    id bigint generated by default as identity primary key,
    claim_id bigint not null references commerce.marketplace_claims(id) on delete restrict,
    provider_event_id text not null unique,
    provider_reference text not null,
    normalized_status text not null,
    occurred_at timestamptz not null,
    provider_evidence jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint marketplace_claim_return_event_id check (length(btrim(provider_event_id)) between 1 and 300),
    constraint marketplace_claim_return_reference check (length(btrim(provider_reference)) between 1 and 300),
    constraint marketplace_claim_return_status check (normalized_status in (
        'carrier_accepted', 'in_transit', 'arrived_at_pickup_point', 'available_for_pickup',
        'recipient_handoff', 'pickup_expired', 'returning_to_sender', 'returned_to_sender',
        'incident', 'lost'
    )),
    constraint marketplace_claim_return_evidence check (
        jsonb_typeof(provider_evidence) = 'object' and pg_column_size(provider_evidence) <= 32768
    )
);

create index if not exists marketplace_claim_return_events_claim_idx
    on commerce.marketplace_claim_return_events(claim_id, occurred_at, id);

alter table commerce.marketplace_claim_return_events
    drop constraint if exists marketplace_claim_return_status;
alter table commerce.marketplace_claim_return_events
    add constraint marketplace_claim_return_status check (normalized_status in (
        'carrier_accepted', 'in_transit', 'arrived_at_pickup_point', 'available_for_pickup',
        'recipient_handoff', 'pickup_expired', 'returning_to_sender', 'returned_to_sender',
        'incident', 'lost'
    ));