/**
 * Validate the user-supplied secret values that will be served via
 * `envsubst` at edge reload time. Two characters are forbidden:
 *
 * - `$` — would cause envsubst to interpret the value as a variable,
 *   leaking other env vars or producing empty output. We reject at write
 *   time rather than escape, because escape rules in shell-style
 *   substitution are subtle and a token can typically be regenerated by
 *   the third-party API without `$`.
 * - NUL / newline — would either truncate the env var (NUL) or break the
 *   `key="value"` env file format (LF/CR).
 *
 * Header NAMES are not validated here — they are emitted as static text
 * inside `proxy_set_header` and don't pass through envsubst.
 */
const FORBIDDEN = /[$\0\r\n]/;

export function assertValidProxyAuthValue(value: unknown, fieldName: string): asserts value is string {
    if (typeof value !== "string") {
        throw new TypeError(`${fieldName} must be a string.`);
    }
    if (value.length === 0) {
        throw new Error(`${fieldName} must not be empty.`);
    }
    if (FORBIDDEN.test(value)) {
        throw new Error(`${fieldName} contains a forbidden character ($, NUL, or line break) — regenerate the secret with safe characters.`);
    }
}
