export function surfaceMountFixtures() {
    const token = (name: string) => ({ name });
    return {
        env: {
            CONTROL_PORT: 3100,
            DELIVERY_PORT: 3101,
            CONTROL_PUBLIC_URL: "https://admin.example.test",
            DELIVERY_PUBLIC_URL: "https://www.example.test",
            CMS_CONTROL_AUTH_EMAIL_VERIFICATION_URL: "https://admin.example.test/auth/verify-email",
            CMS_CONTROL_AUTH_PASSWORD_RESET_URL: "https://admin.example.test/auth/reset-password",
            CMS_AUTH_EMAIL_VERIFICATION_URL: "https://www.example.test/auth/confirm-email",
            CMS_AUTH_PASSWORD_RESET_URL: "https://www.example.test/auth/reset-password",
            CMS_FILES_DIR: "/data/files",
            ANALYTICS_TRUST_PROXY: false,
            ANALYTICS_TRUSTED_PROXY_VERIFIED: false,
        },
        analyticsVisitorSecret: "analytics-secret",
        core: {
            repo: token("repo"),
            cache: token("cache"),
            secrets: token("secrets"),
            filesMetadata: token("files-metadata"),
            filesBlob: token("files-blob"),
            variantStore: token("variant-store"),
            users: token("users"),
            identityProviders: token("identity-providers"),
            pats: token("pats"),
            credentials: token("credentials"),
            roles: token("roles"),
            db: { databaseName: "cms-test" },
        },
        features: {
            integrationInstallations: token("installations"),
            integrationConnectorProviders: token("connector-providers"),
            dashboards: token("dashboards"),
            relations: token("relations"),
            functions: token("functions"),
            triggers: token("triggers"),
            identities: token("identities"),
            sourceOverlays: token("source-overlays"),
            sources: token("sources"),
            deliverySources: token("delivery-sources"),
            analytics: token("analytics"),
            resolveSecret: token("resolve-secret"),
        },
        integrations: {
            integrationRepositoryCatalog: token("repository-catalog"),
            integrationCatalog: token("integration-catalog"),
            integrationConnectorDeployers: [token("deployer")],
            integrationProvisioners: [token("provisioner")],
        },
        authentication: {
            auth: token("auth"),
            publicAuthBase: { marker: "public-auth" },
        },
    };
}
