

create table if not exists commerce.marketplace_claims (
    id bigint generated by default as identity primary key,
    public_id uuid not null default gen_random_uuid() unique,
    order_id bigint not null references commerce.orders(id) on delete restrict,
    buyer_cms_user_id text not null,
    seller_id bigint not null references commerce.sellers(id) on delete restrict,
    reason text not null,
    status text not null default 'open',
    description text not null,
    buyer_requested_amount bigint,
    resolution_outcome text,
    resolution_buyer_refund_amount bigint,
    resolution_seller_transfer_amount bigint,
    resolution_protection_fee_refund_amount bigint,
    decision_reason text,
    seller_response_by_at timestamptz not null,
    return_ship_by_at timestamptz,
    return_delivery_status text,
    return_provider_reference text,
    return_carrier_accepted_at timestamptz,
    return_recipient_handoff_at timestamptz,
    resolved_at timestamptz,
    resolved_by text,
    version integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint marketplace_claims_buyer check (length(btrim(buyer_cms_user_id)) > 0),
    constraint marketplace_claims_reason check (reason in (
        'not_received', 'damaged', 'not_as_described', 'empty_package',
        'missing_items', 'return_requested', 'other'
    )),
    constraint marketplace_claims_status check (status in (
        'open', 'awaiting_seller_response', 'under_review', 'return_required',
        'resolution_pending', 'resolved_buyer', 'resolved_seller', 'resolved_split'
    )),
    constraint marketplace_claims_description check (length(btrim(description)) between 1 and 10000),
    constraint marketplace_claims_amounts check (
        (buyer_requested_amount is null or buyer_requested_amount between 0 and 9007199254740991)
        and (resolution_buyer_refund_amount is null or resolution_buyer_refund_amount between 0 and 9007199254740991)
        and (resolution_seller_transfer_amount is null or resolution_seller_transfer_amount between 0 and 9007199254740991)
        and (resolution_protection_fee_refund_amount is null or resolution_protection_fee_refund_amount between 0 and 9007199254740991)
    ),
    constraint marketplace_claims_outcome check (
        resolution_outcome is null or resolution_outcome in ('buyer', 'seller', 'split', 'return_required')
    ),
    constraint marketplace_claims_return_delivery check (
        (return_delivery_status is null and return_provider_reference is null
            and return_carrier_accepted_at is null and return_recipient_handoff_at is null)
        or (return_delivery_status in (
                'awaiting_carrier', 'carrier_accepted', 'in_transit', 'arrived_at_pickup_point',
                'available_for_pickup', 'recipient_handoff', 'pickup_expired',
                'returning_to_sender', 'returned_to_sender', 'incident', 'lost'
            )
            and (return_recipient_handoff_at is null or return_carrier_accepted_at is not null)
            and (return_delivery_status <> 'recipient_handoff' or return_recipient_handoff_at is not null))
    ),
    constraint marketplace_claims_version check (version > 0)
);

create unique index if not exists marketplace_claims_one_active_idx
    on commerce.marketplace_claims(order_id)
    where status not in ('resolved_buyer', 'resolved_seller', 'resolved_split');
create index if not exists marketplace_claims_order_created_idx
    on commerce.marketplace_claims(order_id, created_at desc);
create index if not exists marketplace_claims_seller_idx
    on commerce.marketplace_claims(seller_id, status, created_at desc);
create index if not exists marketplace_claims_buyer_idx
    on commerce.marketplace_claims(buyer_cms_user_id, status, created_at desc);
create index if not exists marketplace_claims_seller_response_due_idx
    on commerce.marketplace_claims(seller_response_by_at, id)
    where status = 'awaiting_seller_response';
create index if not exists marketplace_claims_return_ship_due_idx
    on commerce.marketplace_claims(return_ship_by_at, id)
    where status = 'return_required';

alter table commerce.marketplace_claims
    drop constraint if exists marketplace_claims_return_delivery;
alter table commerce.marketplace_claims
    add constraint marketplace_claims_return_delivery check (
        (return_delivery_status is null and return_provider_reference is null
            and return_carrier_accepted_at is null and return_recipient_handoff_at is null)
        or (return_delivery_status in (
                'awaiting_carrier', 'carrier_accepted', 'in_transit', 'arrived_at_pickup_point',
                'available_for_pickup', 'recipient_handoff', 'pickup_expired',
                'returning_to_sender', 'returned_to_sender', 'incident', 'lost'
            )
            and (return_recipient_handoff_at is null or return_carrier_accepted_at is not null)
            and (return_delivery_status <> 'recipient_handoff' or return_recipient_handoff_at is not null))
    );