

create table if not exists commerce.refund_requests (
    id bigint generated by default as identity primary key,
    public_id uuid not null default gen_random_uuid() constraint refund_requests_public_id_key unique,
    order_id bigint not null references commerce.orders(id) on delete restrict,
    claim_id bigint references commerce.marketplace_claims(id) on delete restrict,
    business_key text not null constraint refund_requests_business_key_key unique,
    reason text not null,
    status text not null default 'requested',
    requested_amount bigint not null,
    merchandise_refund_amount bigint not null default 0,
    shipping_refund_amount bigint not null default 0,
    protection_fee_refund_amount bigint not null default 0,
    allocation_version smallint not null default 0,
    seller_recovery_amount bigint not null default 0,
    seller_reserve_offset_amount bigint not null default 0,
    requires_finance_approval boolean not null default false,
    dual_approval_required boolean not null default false,
    requested_by_kind text not null,
    requested_by text not null,
    approved_by text,
    first_approved_by text,
    first_approved_at timestamptz,
    second_approved_by text,
    second_approved_at timestamptz,
    rejected_by text,
    decision_reason text,
    provider_refund_id bigint,
    provider_operation_key text,
    provider_snapshot jsonb not null default '{}'::jsonb,
    version integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint refund_requests_business_key check (length(btrim(business_key)) > 0),
    constraint refund_requests_reason check (length(btrim(reason)) > 0),
    constraint refund_requests_status check (status in (
        'requested', 'approved', 'rejected', 'cancelled', 'provider_operation_reserved',
        'processing', 'succeeded', 'failed', 'manual_review'
    )),
    constraint refund_requests_amounts check (
        requested_amount between 1 and 9007199254740991
        and merchandise_refund_amount between 0 and requested_amount
        and shipping_refund_amount between 0 and requested_amount
        and protection_fee_refund_amount between 0 and requested_amount
        and merchandise_refund_amount + shipping_refund_amount
            + protection_fee_refund_amount <= requested_amount
        and allocation_version between 0 and 1
        and seller_recovery_amount between 0 and requested_amount
        and seller_reserve_offset_amount between 0 and seller_recovery_amount
        and protection_fee_refund_amount + seller_recovery_amount <= requested_amount
    ),
    constraint refund_requests_actor check (requested_by_kind in ('buyer', 'seller', 'support', 'finance', 'admin', 'system')),
    constraint refund_requests_dual_approval check (
        not dual_approval_required
        or (second_approved_by is null or first_approved_by is distinct from second_approved_by)
    ),
    constraint refund_requests_provider_id check (provider_refund_id is null or provider_refund_id > 0),
    constraint refund_requests_snapshot check (jsonb_typeof(provider_snapshot) = 'object'),
    constraint refund_requests_version check (version > 0)
);

alter table commerce.refund_requests
    add column if not exists seller_reserve_offset_amount bigint not null default 0,
    add column if not exists merchandise_refund_amount bigint not null default 0,
    add column if not exists shipping_refund_amount bigint not null default 0,
    add column if not exists allocation_version smallint not null default 0;
alter table commerce.refund_requests
    drop constraint if exists refund_requests_amounts,
    drop constraint if exists refund_requests_actor;
alter table commerce.refund_requests
    add constraint refund_requests_amounts check (
        requested_amount between 1 and 9007199254740991
        and merchandise_refund_amount between 0 and requested_amount
        and shipping_refund_amount between 0 and requested_amount
        and protection_fee_refund_amount between 0 and requested_amount
        and merchandise_refund_amount + shipping_refund_amount
            + protection_fee_refund_amount <= requested_amount
        and allocation_version between 0 and 1
        and seller_recovery_amount between 0 and requested_amount
        and seller_reserve_offset_amount between 0 and seller_recovery_amount
        and protection_fee_refund_amount + seller_recovery_amount <= requested_amount
    ),
    add constraint refund_requests_actor check (
        requested_by_kind in ('buyer', 'seller', 'support', 'finance', 'admin', 'system')
    );

create index if not exists refund_requests_order_idx
    on commerce.refund_requests(order_id, status, created_at desc);
create index if not exists refund_requests_claim_idx
    on commerce.refund_requests(claim_id) where claim_id is not null;
create unique index if not exists refund_requests_one_nonterminal_order_idx
    on commerce.refund_requests(order_id)
    where status in ('requested', 'approved', 'provider_operation_reserved', 'processing', 'manual_review');
