export {
    ADMISSION_INPUT_SNAPSHOT_SCHEMA,
    BEHAVIORAL_RLS_AUTHOR_INPUT_SCHEMA,
    BEHAVIORAL_RLS_PLAN_SCHEMA,
    INTEGRATION_VERIFICATION_SCHEMA,
    INTEGRATION_VERIFICATION_SDK_V1_SPECIFIER,
    INTEGRATION_VERIFICATION_SUITE_CONTENT_SCHEMA,
    RELEASE_ADMISSION_POLICY_SNAPSHOT_SCHEMA,
    PLATFORM_VERIFICATION_EVIDENCE_SCHEMA,
    PLATFORM_VERIFICATION_SUITE_DEFINITION_SCHEMA,
    CANDIDATE_ADMISSION_JOB_RESULT_SCHEMA,
    CMS_POSTGRES_MIGRATION_ENVIRONMENT_V1,
    MIGRATION_JOB_RESULT_SCHEMA,
    MIGRATION_VERIFICATION_ENVIRONMENT_SCHEMA,
    MIGRATION_VERIFICATION_INPUT_SCHEMA,
    VERIFICATION_JOB_RESULT_SCHEMA,
    type AdmissionActiveContractReferenceV1,
    type AdmissionBehavioralRlsPlanBindingV1,
    type AdmissionDependencyReferenceV1,
    type AdmissionInputSnapshotV1,
    type AdmissionReviewedBaselineReferenceV1,
    type AdmissionSuitePlanEntryV1,
    type BoundIntegrationVerificationAuthorSuiteV1,
    type BehavioralRlsAuthorInputV1,
    type BehavioralRlsFixtureV1,
    type BehavioralRlsPlanV1,
    type BehavioralRlsProbeV1,
    type BehavioralRlsScalarV1,
    type IdentifiedAdmissionInputSnapshotV1,
    type IdentifiedBehavioralRlsPlanV1,
    type IdentifiedReleaseAdmissionPolicySnapshotV1,
    type IdentifiedVerificationJobResultV1,
    type IntegrationVerificationEnvelopeV1,
    type IntegrationVerificationAuthorSuiteType,
    type IntegrationVerificationConformanceSuiteV1,
    type IntegrationVerificationContractSuiteV1,
    type IntegrationVerificationManifestV1,
    type IntegrationVerificationSuiteContentV2,
    type IntegrationVerificationValidationOptions,
    type CandidateAdmissionJobResultV1,
    type IdentifiedCandidateAdmissionJobResultV1,
    type IdentifiedMigrationJobResultV1,
    type IdentifiedMigrationVerificationEnvironmentV1,
    type IdentifiedMigrationVerificationInputV1,
    type MigrationEvidencePolicyV1,
    type MigrationCutoverObservationV1,
    type MigrationEquivalenceObservationV1,
    type MigrationFailureObservationV1,
    type MigrationJobAttemptIdentityV1,
    type MigrationJobResultV1,
    type MigrationLedgerObservationV1,
    type MigrationRawObservationEvidenceV1,
    type MigrationRawObservationStatus,
    type MigrationReplayObservationV1,
    type MigrationResumptionObservationV1,
    type MigrationTargetObservationV1,
    type MigrationVerificationEnvironmentV1,
    type MigrationVerificationInputV1,
    type PlatformRequiredVerificationSuiteV1,
    type PlatformVerificationCheckEvidenceV1,
    type PlatformVerificationEvidenceV1,
    type PlatformVerificationFindingV1,
    type PlatformVerificationSuiteApplicabilityV1,
    type PlatformVerificationSuiteDefinitionV1,
    type ReleaseAdmissionPolicySnapshotV1,
    type VerificationCachePolicyV1,
    type VerificationJobAttemptIdentityV1,
    type VerificationJobResultV1,
    type VerificationJobSuiteResultV1,
    type VerificationRetryPolicyV1,
} from "../interfaces/verification";
export {
    INTEGRATION_CANDIDATE_SCHEMA,
    type IntegrationCandidateEnvelopeV1,
    type ValidatedIntegrationCandidateEnvelopeV1,
} from "../interfaces/candidate";
export {
    FINDING_RESOLUTION_PROOF_SCHEMA,
    type CompatibilityFinding,
    type CompatibilityFindingClassification,
    type CompatibilityFindingResolutionResult,
    type CompatibilityFindingIdentityInput,
    type CompatibilityFindingInput,
    type CompatibilityFindingSurface,
    type FindingResolutionProof,
    type FindingResolutionPolicyRule,
    type ResolvedCompatibilityFinding,
} from "../interfaces/finding";
export {
    REVIEWED_SCHEMA_BASELINE_SCHEMA,
    type ReviewedSchemaBaselineV1,
} from "../interfaces/baseline";
export type {
    PinnedVerificationRunnerIdentity,
    VerificationPolicyIdentity,
    VerificationRunnerRequirement,
} from "../interfaces/runner";
export {
    COMPATIBILITY_REPORT_V2_SCHEMA,
    MIGRATION_REPORT_SCHEMA,
    MIGRATION_REPORT_V2_SCHEMA,
    MIGRATION_REPORT_V3_SCHEMA,
    MIGRATION_REPORT_V4_SCHEMA,
    RELEASE_ADMISSION_DECISION_SCHEMA,
    VERIFICATION_REPORT_SCHEMA,
    type CompatibilityNoBaselineReason,
    type CompatibilityReleaseLevel,
    type CompatibilityReportAssessment,
    type CompatibilityReportOutcome,
    type CompatibilityReportV2,
    type CompatibilityRequiredReleaseLevel,
    type ComposeReleaseAdmissionDecisionInput,
    type DigestContractReference,
    type MigrationCheckResult,
    type MigrationCutoverEvidence,
    type MigrationPolicyEvaluationCheck,
    type MigrationOperationalEvidence,
    type MigrationReport,
    type MigrationReportPolicyEvaluation,
    type MigrationReportV2,
    type MigrationReportV3,
    type MigrationReportV4,
    type LegacyMigrationReportV1,
    type MigrationReportRevisionDigestReference,
    type ReleaseAdmissionDecision,
    type RequiredMigrationEvidence,
    type IdentifiedStatefulChangeSelectionV1,
    type ReportRevisionDigestReference,
    type ReportHistoryFields,
    type ReportOrigin,
    type ReportProvenance,
    type VerificationReport,
    type VerificationSuiteResult,
    type VersionDigestReference,
    type StatefulChangeSelectionV1,
} from "../interfaces/reports";
export { STATEFUL_CHANGE_SELECTION_SCHEMA } from "../interfaces/reports";
export {
    assertVerificationJobResultReplay,
    buildIntegrationVerificationSuiteContent,
    identifyIntegrationVerificationSuiteContent,
    computeIntegrationVerificationDigest,
    computeIntegrationVerificationSuiteContentDigest,
    identifyCandidateAdmissionJobResult,
    identifyAdmissionInputSnapshot,
    identifyMigrationJobResult,
    identifyMigrationVerificationEnvironment,
    identifyMigrationVerificationInput,
    identifyReleaseAdmissionPolicySnapshot,
    identifyVerificationJobResult,
    parseAdmissionInputSnapshot,
    parseIntegrationVerificationEnvelope,
    parseCandidateAdmissionJobResult,
    parseMigrationJobResult,
    parseMigrationVerificationEnvironment,
    parseMigrationVerificationInput,
    parseReleaseAdmissionPolicySnapshot,
    parseVerificationJobResult,
    validateAdmissionInputSnapshot,
    validateAdmissionInputSnapshotForPolicy,
    buildBehavioralRlsPlan,
    identifyBehavioralRlsPlan,
    parseBehavioralRlsAuthorInput,
    validateBehavioralRlsAuthorInput,
    validateBehavioralRlsPlan,
    validateBehavioralRlsPlanBinding,
    validateIntegrationVerificationEnvelope,
    validateIntegrationVerificationSuiteContent,
    validateBoundIntegrationVerificationAuthorSuites,
    validateIntegrationVerificationSuiteSources,
    validateCandidateAdmissionJobResult,
    validateCandidateAdmissionJobResultForPlan,
    validateMigrationJobResult,
    validateMigrationJobResultForInput,
    validateMigrationVerificationEnvironment,
    validateMigrationVerificationInput,
    validateReleaseAdmissionPolicySnapshot,
    validateVerificationJobResult,
    validateVerificationJobResultForAdmission,
    POSTGRES_PLATFORM_VERIFICATION_SUITES_V1,
    BEHAVIORAL_RLS_PLATFORM_SUITE_ID,
    BEHAVIORAL_RLS_PLAN_LIMITS,
    identifyPlatformVerificationSuiteDefinition,
    parsePlatformVerificationEvidence,
} from "../core/verification";
export {
    parseIntegrationCandidateEnvelope,
    validateIntegrationCandidateEnvelope,
} from "../core/candidate";
export {
    computeCompatibilityFindingId,
    createCompatibilityFinding,
    findingResolutionProofAppliesToPolicy,
    parseCompatibilityFinding,
    parseFindingResolutionProof,
} from "../core/finding";
export { resolveCompatibilityFindings } from "../core/findingResolution";
export { identifyReviewedSchemaBaseline, parseReviewedSchemaBaseline } from "../core/baseline";
export {
    parsePinnedVerificationRunnerIdentity,
    parseVerificationPolicyIdentity,
    parseVerificationRunnerRequirement,
    runnerSatisfiesRequirement,
} from "../core/runner";
export { identifyCompatibilityReportV2, parseCompatibilityReportV2 } from "../core/reports/compatibility";
export { deriveCompatibilityReportAssessment } from "../core/reports/compatibilityAssessment";
export { identifyVerificationReport, parseVerificationReport } from "../core/reports/verification";
export { identifyMigrationReport, parseMigrationReport } from "../core/reports/migration";
export {
    assertMigrationReportAgainstPolicy,
    evaluateMigrationReportAgainstPolicy,
} from "../core/reports/migration/policy";
export {
    appendReleaseAdmissionDecision,
    assertReleaseAdmissionDecisionHistory,
    identifyReleaseAdmissionDecision,
    identifyStatefulChangeSelection,
    isIntegrationReleaseFreshInstallOnly,
    parseReleaseAdmissionDecision,
    parseStatefulChangeSelection,
} from "../core/reports/decision";
export {
    assertReleaseAdmissionDecisionMatchesReports,
    composeReleaseAdmissionDecision,
} from "../core/reports/decision/composition";
export { assertReportRevisionFollows } from "../core/reports/shared";
export {
    IntegrationVerificationContractError,
    type IntegrationVerificationContractErrorCode,
} from "../core/validation/errors";
