import type { IntegrationPackageEnvelopeV1 } from "@bernouy/cms-integration-packages";
import {
    POSTGRES_PLATFORM_VERIFICATION_SUITES_V1,
    identifyPlatformVerificationSuiteDefinition,
} from "@bernouy/cms-integration-verification";

export async function applicablePlatformSuites() {
    return await Promise.all(
        POSTGRES_PLATFORM_VERIFICATION_SUITES_V1.map(async (definition) => ({
            suiteId: definition.suiteId,
            suiteDigest: (await identifyPlatformVerificationSuiteDefinition(definition)).digest,
            applicable: true,
        })),
    );
}

export function unsafePostgresPackage(): IntegrationPackageEnvelopeV1 {
    return {
        schema: "cms.integration.package.v1",
        kind: "unsafe-postgres",
        version: "1.0.0",
        definition: "definition.json",
        releaseNotes: "release-notes.md",
        files: {
            "definition.json": {
                encoding: "utf8",
                content: JSON.stringify({
                    kind: "unsafe-postgres",
                    label: "Unsafe PostgreSQL",
                    version: "1.0.0",
                    inputs: [],
                    connectors: [
                        {
                            provider: "supabase",
                            root: "connectors/supabase",
                            dataApiSchemas: ["verifier_unsafe"],
                            schemas: [{ manifest: "sql/schema.manifest.json" }],
                            compatibility: {
                                schema: {
                                    namespaces: [{ name: "verifier_unsafe", relations: [] }],
                                },
                            },
                        },
                    ],
                }),
            },
            "release-notes.md": { encoding: "utf8", content: "Adversarial PostgreSQL fixture" },
            "connectors/supabase/sql/schema.manifest.json": {
                encoding: "utf8",
                content: JSON.stringify({
                    schema: "cms.integration.sql-bundle.v1",
                    transaction: "atomic",
                    entries: [{ file: "schema.sql" }],
                }),
            },
            "connectors/supabase/sql/schema.sql": {
                encoding: "utf8",
                content: unsafeSql(),
            },
        },
    };
}

function unsafeSql(): string {
    return [
        "insert into storage.buckets (id, name) values ('verification-escape', 'verification-escape') on conflict (id) do nothing;",
        "create schema if not exists verifier_unsafe;",
        "create table if not exists verifier_unsafe.items (id bigint generated by default as identity primary key, unexpected text);",
        "drop policy if exists unsafe_metadata on verifier_unsafe.items;",
        "create policy unsafe_metadata on verifier_unsafe.items for select to authenticated using ((current_setting('request.jwt.claims', true)::jsonb -> 'user_metadata') is not null);",
        "drop policy if exists missing_check on verifier_unsafe.items;",
        "create policy missing_check on verifier_unsafe.items for insert to authenticated;",
        "create or replace view verifier_unsafe.items_view as select id from verifier_unsafe.items;",
        "grant select on verifier_unsafe.items_view to authenticated;",
        "create or replace function verifier_unsafe.privileged() returns bigint language sql security definer as 'select 1::bigint';",
        "grant create on schema verifier_unsafe to anon;",
        "grant select on verifier_unsafe.items to public;",
        "grant truncate on verifier_unsafe.items to authenticated;",
    ].join("\n");
}
