

create table if not exists commerce.carts (
    id bigint generated by default as identity primary key,
    public_id uuid not null default gen_random_uuid() unique,
    buyer_cms_user_id text not null,
    status text not null default 'open',
    currency text,
    version integer not null default 1,
    converted_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint carts_buyer_not_blank check (length(btrim(buyer_cms_user_id)) > 0),
    constraint carts_buyer_length check (length(buyer_cms_user_id) <= 512),
    constraint carts_status check (status in ('open', 'converted', 'abandoned', 'expired')),
    constraint carts_currency check (currency is null or currency ~ '^[a-z]{3}$'),
    constraint carts_conversion_consistent check (
        (status = 'converted' and converted_at is not null)
        or (status <> 'converted' and converted_at is null)
    ),
    constraint carts_version_positive check (version > 0)
);

create unique index if not exists carts_one_open_per_buyer
    on commerce.carts(buyer_cms_user_id) where status = 'open';

create table if not exists commerce.cart_items (
    id bigint generated by default as identity primary key,
    cart_id bigint not null references commerce.carts(id) on delete cascade,
    offer_id bigint not null references commerce.offers(id) on delete restrict,
    quantity integer not null,
    unit_amount_at_add bigint not null,
    offer_version_at_add integer not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint cart_items_cart_offer_unique unique (cart_id, offer_id),
    constraint cart_items_quantity check (quantity between 1 and 1000),
    constraint cart_items_unit_amount check (unit_amount_at_add between 0 and 9007199254740991),
    constraint cart_items_offer_version_positive check (offer_version_at_add > 0)
);

create table if not exists commerce.checkout_groups (
    id uuid primary key default gen_random_uuid(),
    buyer_cms_user_id text not null,
    source_cart_id bigint references commerce.carts(id) on delete restrict,
    idempotency_key text not null,
    request_hash text not null,
    created_at timestamptz not null default now(),
    constraint checkout_groups_buyer_not_blank check (length(btrim(buyer_cms_user_id)) > 0),
    constraint checkout_groups_buyer_length check (length(buyer_cms_user_id) <= 512),
    constraint checkout_groups_idempotency_not_blank check (length(btrim(idempotency_key)) > 0),
    constraint checkout_groups_idempotency_length check (length(idempotency_key) <= 200),
    constraint checkout_groups_request_hash_format check (request_hash ~ '^[a-f0-9]{32}$'),
    constraint checkout_groups_buyer_idempotency_unique unique (buyer_cms_user_id, idempotency_key),
    constraint checkout_groups_source_cart_unique unique (source_cart_id)
);