

create table if not exists commerce.offer_price_proposals (
    id bigint generated by default as identity primary key,
    offer_id bigint not null references commerce.offers(id) on delete restrict,
    amount bigint not null,
    currency text not null,
    status text not null default 'pending',
    proposed_by text not null,
    decided_by text,
    decision_reason text,
    decided_at timestamptz,
    created_at timestamptz not null default now(),
    constraint offer_price_proposals_offer_id_id_unique unique (offer_id, id),
    constraint offer_price_proposals_amount_non_negative check (amount between 0 and 9007199254740991),
    constraint offer_price_proposals_currency check (currency ~ '^[a-z]{3}$'),
    constraint offer_price_proposals_status check (
        status in ('pending', 'accepted', 'rejected', 'withdrawn', 'superseded')
    ),
    constraint offer_price_proposals_decision_audit check (
        (status in ('accepted', 'rejected') and decided_by is not null and decided_at is not null)
        or status not in ('accepted', 'rejected')
    )
);

create unique index if not exists offer_price_proposals_one_pending
    on commerce.offer_price_proposals(offer_id)
    where status = 'pending';

create unique index if not exists offer_price_proposals_one_accepted
    on commerce.offer_price_proposals(offer_id)
    where status = 'accepted';

create table if not exists commerce.offer_events (
    id bigint generated by default as identity primary key,
    offer_id bigint not null references commerce.offers(id) on delete restrict,
    event_type text not null,
    actor_kind text not null,
    actor_id text not null,
    previous_workflow_state text,
    next_workflow_state text,
    data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint offer_events_actor_kind check (actor_kind in ('seller', 'admin', 'system')),
    constraint offer_events_data_object check (jsonb_typeof(data) = 'object')
);