

create table if not exists commerce.media (
    id bigint generated by default as identity primary key,
    storage_bucket text not null,
    storage_path text not null,
    mime_type text not null,
    file_size bigint not null,
    width integer,
    height integer,
    original_filename text not null,
    alt text,
    detached_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint media_storage_path_unique unique (storage_bucket, storage_path),
    constraint media_file_size_valid check (file_size between 1 and 10485760),
    constraint media_mime_type_valid check (
        mime_type in ('image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/avif')
    ),
    constraint media_original_filename_not_blank check (length(btrim(original_filename)) > 0),
    constraint media_alt_length check (alt is null or length(alt) <= 500),
    constraint media_dimensions_paired check ((width is null) = (height is null)),
    constraint media_dimensions_valid check (
        width is null or (
            width > 0 and height > 0
            and width::bigint * height::bigint <= 40000000
        )
    )
);

alter table commerce.media
    add column if not exists width integer,
    add column if not exists height integer,
    add column if not exists detached_at timestamptz;

do $commerce_media_constraints$
begin
    if not exists (
        select 1 from pg_constraint
        where conrelid = 'commerce.media'::regclass
          and conname = 'media_dimensions_paired'
    ) then
        alter table commerce.media
            add constraint media_dimensions_paired
            check ((width is null) = (height is null));
    end if;
    if not exists (
        select 1 from pg_constraint
        where conrelid = 'commerce.media'::regclass
          and conname = 'media_dimensions_valid'
    ) then
        alter table commerce.media
            add constraint media_dimensions_valid
            check (
                width is null or (
                    width > 0 and height > 0
                    and width::bigint * height::bigint <= 40000000
                )
            );
    end if;
end;
$commerce_media_constraints$;

create or replace function commerce.enforce_media_original_immutability()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    if tg_op = 'DELETE' then
        raise exception 'conflict: commerce media originals cannot be deleted';
    end if;
    if row(
        new.id, new.storage_bucket, new.storage_path, new.mime_type,
        new.file_size, new.original_filename, new.created_at
    ) is distinct from row(
        old.id, old.storage_bucket, old.storage_path, old.mime_type,
        old.file_size, old.original_filename, old.created_at
    ) then
        raise exception 'conflict: commerce media original metadata is immutable';
    end if;
    if old.width is not null or old.height is not null then
        if row(new.width, new.height) is distinct from row(old.width, old.height) then
            raise exception 'conflict: commerce media dimensions are immutable';
        end if;
    elsif (new.width is null) <> (new.height is null) then
        raise exception 'validation: commerce media dimensions must be recorded together';
    end if;
    if old.detached_at is not null and new.detached_at is distinct from old.detached_at then
        raise exception 'conflict: detached commerce media cannot be reattached';
    end if;
    return new;
end;
$$;

drop trigger if exists media_original_immutability on commerce.media;
create trigger media_original_immutability
before update or delete on commerce.media
for each row execute function commerce.enforce_media_original_immutability();

create table if not exists commerce.product_media (
    id bigint generated by default as identity primary key,
    product_id bigint not null references commerce.products(id) on delete restrict,
    media_id bigint not null references commerce.media(id) on delete restrict,
    sort_order integer not null default 0,
    is_main boolean not null default false,
    created_at timestamptz not null default now(),
    constraint product_media_product_media_unique unique (product_id, media_id)
);

create unique index if not exists product_media_main_unique
    on commerce.product_media(product_id) where is_main;

do $commerce_storage_bucket$
begin
    if to_regclass('storage.buckets') is not null then
        execute $sql$
            insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
            values (
                'commerce-media', 'commerce-media', false, 10485760,
                array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/avif']::text[]
            )
            on conflict (id) do update set
                public = false,
                file_size_limit = excluded.file_size_limit,
                allowed_mime_types = excluded.allowed_mime_types
        $sql$;
    end if;
end;
$commerce_storage_bucket$;
