

create table if not exists commerce.product_variants (
    id bigint generated by default as identity primary key,
    product_id bigint not null references commerce.products(id) on delete restrict,
    sku text,
    title text not null,
    status text not null default 'active',
    position integer not null default 0,
    combination_key text,
    generated_from_axes boolean not null default false,
    metadata jsonb not null default '{}'::jsonb,
    version integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint product_variants_product_id_id_unique unique (product_id, id),
    constraint product_variants_sku_not_blank check (sku is null or length(btrim(sku)) > 0),
    constraint product_variants_sku_length check (sku is null or length(sku) <= 160),
    constraint product_variants_title_not_blank check (length(btrim(title)) > 0),
    constraint product_variants_title_length check (length(title) <= 300),
    constraint product_variants_status check (status in ('draft', 'active', 'archived')),
    constraint product_variants_combination_key check (
        combination_key is null or length(combination_key) between 1 and 1000
    ),
    constraint product_variants_metadata_object check (jsonb_typeof(metadata) = 'object'),
    constraint product_variants_metadata_size check (pg_column_size(metadata) <= 65536),
    constraint product_variants_version_positive check (version > 0)
);

alter table commerce.product_variants alter column sku drop not null;
alter table commerce.product_variants add column if not exists combination_key text;
alter table commerce.product_variants
    add column if not exists generated_from_axes boolean not null default false;

create unique index if not exists product_variants_sku_unique
    on commerce.product_variants(sku) where sku is not null;
create unique index if not exists product_variants_combination_unique
    on commerce.product_variants(product_id, combination_key) where combination_key is not null;

create table if not exists commerce.product_variant_axes (
    id bigint generated by default as identity primary key,
    product_id bigint not null references commerce.products(id) on delete restrict,
    key text not null,
    field_key text,
    label text not null,
    position integer not null default 0,
    created_at timestamptz not null default now(),
    constraint product_variant_axes_product_id_id_unique unique (product_id, id),
    constraint product_variant_axes_key_format check (key ~ '^[a-z][a-z0-9_-]{0,47}$'),
    constraint product_variant_axes_label_not_blank check (length(btrim(label)) > 0),
    constraint product_variant_axes_label_length check (length(label) <= 120),
    constraint product_variant_axes_product_key_unique unique (product_id, key)
);

create table if not exists commerce.product_variant_axis_values (
    id bigint generated by default as identity primary key,
    product_id bigint not null,
    axis_id bigint not null,
    key text not null,
    label text not null,
    value jsonb,
    position integer not null default 0,
    created_at timestamptz not null default now(),
    constraint product_variant_axis_values_axis_fk foreign key (product_id, axis_id)
        references commerce.product_variant_axes(product_id, id) on delete cascade,
    constraint product_variant_axis_values_product_axis_id_unique unique (product_id, axis_id, id),
    constraint product_variant_axis_values_key_format check (key ~ '^[a-z0-9][a-z0-9_-]{0,63}$'),
    constraint product_variant_axis_values_label_not_blank check (length(btrim(label)) > 0),
    constraint product_variant_axis_values_label_length check (length(label) <= 160),
    constraint product_variant_axis_values_axis_key_unique unique (axis_id, key)
);

alter table commerce.product_variant_axes add column if not exists field_key text;
alter table commerce.product_variant_axis_values add column if not exists value jsonb;
update commerce.product_variant_axis_values set value = to_jsonb(label) where value is null;

create table if not exists commerce.product_variant_selections (
    product_id bigint not null,
    variant_id bigint not null,
    axis_id bigint not null,
    value_id bigint not null,
    created_at timestamptz not null default now(),
    primary key (variant_id, axis_id),
    constraint product_variant_selections_variant_fk foreign key (product_id, variant_id)
        references commerce.product_variants(product_id, id) on delete cascade,
    constraint product_variant_selections_axis_fk foreign key (product_id, axis_id)
        references commerce.product_variant_axes(product_id, id) on delete cascade,
    constraint product_variant_selections_value_fk foreign key (product_id, axis_id, value_id)
        references commerce.product_variant_axis_values(product_id, axis_id, id) on delete restrict
);