export const settingsRow = {
    id: "default",
    mode: "marketplace",
    default_currency: "eur",
    active_c2c_fee_policy_id: 101,
    active_c2c_protection_policy_id: 201,
    active_c2c_seller_risk_policy_id: 301,
    version: 9,
    updated_at: "2026-07-17T10:00:00.000Z",
};

export const feePolicyRow = {
    id: 101,
    policy_key: "c2c-marketplace",
    version: 4,
    name: "Protected marketplace policy",
    status: "draft",
    currency: "eur",
    shipping_beneficiary: "platform",
    estimated_stripe_cost_amount: 125,
    estimated_carrier_cost_amount: 275,
    platform_risk_reserve_contribution_amount: 50,
    configured_minimum_margin_amount: 100,
    cost_estimates_configured: true,
    subsidy_override: true,
    subsidy_reason: "Launch subsidy",
    published_at: null,
    created_by: "admin-9",
    created_at: "2026-07-17T09:00:00.000Z",
};

export const protectionPolicyRow = {
    id: 201,
    policy_key: "c2c-marketplace",
    version: 4,
    name: "Protected marketplace policy",
    status: "published",
    currency: "eur",
    payment_window_minutes: 30,
    seller_handoff_hours: 72,
    scan_grace_hours: 48,
    claim_window_hours: 48,
    seller_response_hours: 72,
    return_ship_hours: 168,
    finance_review_threshold_amount: 50_000,
    dual_approval_threshold_amount: 100_000,
    published_at: "2026-07-17T09:05:00.000Z",
    created_by: "admin-9",
    created_at: "2026-07-17T09:00:00.000Z",
};

export const sellerRiskPolicyRow = {
    id: 301,
    policy_key: "c2c-marketplace",
    version: 4,
    name: "Protected marketplace policy",
    status: "published",
    currency: "eur",
    reserve_rate_bps: 1_000,
    payout_delay_days: 14,
    reserve_liability_days: 120,
    order_transfer_limit_amount: 500_000,
    velocity_limit_amount: 1_000_000,
    high_value_review_amount: 50_000,
    claim_ratio_review_bps: 1_000,
    chargeback_ratio_review_bps: 200,
    published_at: "2026-07-17T09:05:00.000Z",
    created_by: "admin-9",
    created_at: "2026-07-17T09:00:00.000Z",
};

export const componentRows = [
    {
        id: 1_001,
        fee_policy_id: 101,
        component_key: "seller_commission",
        payer: "seller",
        basis: "merchandise",
        rate_bps: 1_000,
        fixed_amount: 50,
        minimum_amount: 100,
        maximum_amount: null,
        rounding_mode: "round_half_up",
        refund_policy: "never",
        position: 5,
        created_at: "2026-07-17T09:01:00.000Z",
    },
    {
        id: 1_002,
        fee_policy_id: 101,
        component_key: "buyer_protection",
        payer: "buyer",
        basis: "merchandise_and_shipping",
        rate_bps: 500,
        fixed_amount: 75,
        minimum_amount: null,
        maximum_amount: 2_500,
        rounding_mode: "round_half_up",
        refund_policy: "resolution_defined",
        position: 5,
        created_at: "2026-07-17T09:01:00.000Z",
    },
];

export const subsidyRows = [
    {
        id: 1_102,
        fee_policy_id: 101,
        maximum_deficit_amount: 450,
        reason: "Launch subsidy",
        approved_by: "admin-11",
        expires_at: null,
        created_at: "2026-07-17T09:03:00.000Z",
    },
    {
        id: 1_101,
        fee_policy_id: 101,
        maximum_deficit_amount: 300,
        reason: "Older subsidy",
        approved_by: "admin-7",
        expires_at: "2026-08-01T00:00:00.000Z",
        created_at: "2026-07-16T09:03:00.000Z",
    },
];
