export function fulfillmentQuote() {
    return {
        quoteId: "quote-42",
        externalOrderId: "order-public-42",
        orderVersion: 1,
        revision: 1,
        selectedForCmsUserId: "buyer-subject",
        relayLocation: "FR-024474",
        country: "FR",
        number: "024474",
        name: "Relay",
        addressLine1: "3 Relay Street",
        addressLine2: "",
        postalCode: "75002",
        city: "Paris",
        weightGrams: 500,
        shippingAmount: 450,
        currency: "EUR",
        merchandiseSubtotalMinorAmount: 11000,
        quotedAt: "2026-07-12T09:00:00.000Z",
        expiresAt: "2099-07-12T09:15:00.000Z",
        recipientSnapshot: {
            name: "Alice Buyer",
            firstName: "Alice",
            lastName: "Buyer",
            email: "",
            phone: "+33600000000",
            addressLine1: "1 rue du Test",
            addressLine2: "",
            addressLine3: "",
            postalCode: "75001",
            city: "Paris",
            country: "FR",
        },
        sellerFulfillmentSnapshot: {
            name: "Seller Test",
            firstName: "Seller",
            lastName: "Test",
            email: "",
            phone: "+33611111111",
            addressLine1: "2 rue du Vendeur",
            addressLine2: "",
            addressLine3: "",
            postalCode: "69001",
            city: "Lyon",
            country: "FR",
        },
    };
}
