import type { Db } from "mongodb";
import type { Runner, SecretCrypto } from "@bernouy/core";
import type { Tenant } from "src/interfaces/Tenant";
import type { TenantRepository } from "src/interfaces/TenantRepository";
import { mountTenant, type MountedTenant, type TenantRole } from "src/core/tenant/mountTenant";
import { unmountTenant } from "src/core/tenant/unmountTenant";
import { purgeTenantData } from "src/core/tenant/purgeTenantData";
import { seedAdmin } from "src/core/tenant/members";
import { seedTenantAuth } from "src/core/tenant/seedTenantAuth";
import { createPiiCrypto } from "@bernouy/cms";
import { randomBase64Url } from "@bernouy/core";

/**
 * Shared, platform-level session config. Configured **once** at the runtime's
 * composition root, not per-tenant. The CMS owns authentication (a builtin
 * local provider + per-tenant dynamic OIDC providers stored as data); the only
 * platform-wide secret is the one used to sign every tenant's session cookie.
 */
export type AdminSessionConfig = {
    /** HMAC key for the signed session cookie, shared across all tenants. */
    sessionSecret: string;
};

/**
 * What a provisioner passes to mount a tenant. No session secret here — it is
 * platform-level (`AdminSessionConfig`), configured once at the composition
 * root. `initialAdminEmail` is seeded as the tenant's first CMS admin (granted
 * the `admin` role on the builtin local provider).
 */
export type TenantProvisionInput = {
    id:                string;
    name:              string;
    /** Email of the bootstrap admin — seeded into the tenant's member set. */
    initialAdminEmail: string;
    /** Bootstrap password for the builtin local admin (`admin@local.com`).
     *  Generated by the hub and surfaced in the tenant info. When absent (dev),
     *  a random one is generated and logged. */
    initialAdminPassword?: string;
};

export type MtControlCmsDeps = {
    runner:     Runner;
    db:         Db;
    /** Public origin (https://platform.com) used to build per-tenant OIDC
     *  callback URLs (one per identity provider configured in the tenant's
     *  `identityProviders` repo). */
    appBaseUrl: string;
    tenantRepo: TenantRepository;
    /** Shared session-signing config, configured once for every tenant. */
    session:    AdminSessionConfig;
    /** Envelope-encryption surface used by every per-tenant `SecretStore`.
     *  Typically `new EnvelopeSecretCrypto(kekProvider, dekRepo)` where
     *  `kekProvider` is `OvhOkmsKekProvider` (Customer Managed Key in OVH
     *  OKMS, never reachable in-process) and `dekRepo` is a single
     *  `MongoDekRepository` on a shared `cms_deks` collection — DEKs
     *  isolate across tenants by `scopeId = tenantId`. */
    secretCrypto: SecretCrypto;
};

/**
 * Multi-tenant orchestrator. Holds the shared infrastructure (one runner,
 * one Db, one MongoClient) and lazily mounts/unmounts per-tenant CMS
 * Control instances on demand. Provisioning is driven by the hub via the
 * `cms-control` tenant-provisioner's hooks, which call
 * `provisionTenant`/`reprovisionTenant`/`deprovisionTenant` — there is no
 * in-process superadmin surface; the tenant registry is a hub-fed runtime
 * store.
 */
export class MtControlCms {

    private readonly _runner:         Runner;
    private readonly _db:             Db;
    private readonly _appBaseUrl:     string;
    private readonly _tenantRepo:     TenantRepository;
    private readonly _secretCrypto:   SecretCrypto;
    private readonly _session:        AdminSessionConfig;
    private readonly _mounted:        Map<string, MountedTenant> = new Map();

    constructor(deps: MtControlCmsDeps) {
        this._runner         = deps.runner;
        this._db             = deps.db;
        this._appBaseUrl     = deps.appBaseUrl;
        this._tenantRepo     = deps.tenantRepo;
        this._secretCrypto   = deps.secretCrypto;
        this._session        = deps.session;
    }

    /** Read-only accessors — used by the provisioning connector. */
    get runner():     Runner            { return this._runner; }
    get db():         Db                { return this._db; }
    get appBaseUrl(): string            { return this._appBaseUrl; }
    get tenantRepo(): TenantRepository  { return this._tenantRepo; }

    /**
     * Mount every tenant currently in the registry. Call once at boot,
     * before `runner.start()`. The hub does NOT re-run `onProvision` after a
     * restart, so this boot-mount is what brings existing tenants back online.
     */
    async init(): Promise<void> {
        const tenants = await this._tenantRepo.list();
        for (const t of tenants) await this._mount(t);
    }

    /**
     * Provision a tenant: persist the row, seed the builtin local admin, then
     * mount. **Idempotent** — a tenant already mounted is left as-is (the hub
     * may retry `onProvision`), and `seedTenantAuth` skips already-seeded
     * admins (so a retry never resets the admin password).
     * `initialAdminPassword` bootstraps the builtin local provider; when
     * absent, a random one is generated and logged in non-prod only.
     */
    async provisionTenant(input: TenantProvisionInput): Promise<void> {
        if (this._mounted.has(input.id)) return;

        const now = new Date();
        const tenant: Tenant = {
            id: input.id, name: input.name, createdAt: now, updatedAt: now,
        };
        await this._tenantRepo.create(tenant);
        try {
            await this._seedAuth(input);
            await this._mount(tenant);
        } catch (err) {
            console.error(`[cms-control-mt] provisionTenant "${input.id}" failed:`, err);
            // mountTenant registers routes (LocalAuthentication, OidcAuthentication,
            // ControlCms) before its first async network call. If it throws
            // afterwards, those routes remain on the runner and a retry with
            // corrected config stacks duplicates — first-match-wins keeps the
            // broken handlers alive. Drop the whole prefix on rollback.
            this._runner.removeRoutesByPathPrefix(`/cms/${tenant.id}`);
            await this._tenantRepo.delete(tenant.id).catch(() => null);
            throw err;
        }
    }

    /**
     * Seed the builtin local admin (member-store row + `local` identity
     * provider + admin credential + `admin` role in `UsersRepository`).
     * Idempotent — a retry never resets the admin password. Generated
     * passwords are logged only in non-prod (`NODE_ENV !== "production"`) so
     * a mis-wired prod TP cannot leak the bootstrap secret to stdout.
     */
    private async _seedAuth(input: TenantProvisionInput): Promise<void> {
        await seedAdmin(this._db, input.id, input.initialAdminEmail);
        const password = input.initialAdminPassword ?? randomBase64Url(18);
        const pii = await createPiiCrypto(input.id, this._secretCrypto, this._db, `tenant_${input.id}__`);
        await seedTenantAuth(this._db, input.id, pii, { email: input.initialAdminEmail, password });
        if (!input.initialAdminPassword && process.env.NODE_ENV !== "production") {
            console.warn(`[cms-control-mt] tenant "${input.id}" bootstrap admin: ${input.initialAdminEmail} / ${password} (generated)`);
        }
    }

    /**
     * Re-mount a tenant: unmount, upsert the row, re-seed the admin, then
     * mount. The session-signing key is platform-level (shared), so there is
     * nothing per-tenant to preserve across the remount. The seed step is
     * idempotent — a new `initialAdminPassword` on an existing admin email
     * does NOT rotate the credential (operators rotate via the admin UI).
     * Falls back to a fresh create (incl. local admin seed) when the tenant
     * is unknown.
     */
    async reprovisionTenant(input: TenantProvisionInput): Promise<void> {
        const existing = await this._tenantRepo.get(input.id);

        const mounted = this._mounted.get(input.id);
        if (mounted) {
            unmountTenant(this._runner, mounted);
            this._mounted.delete(input.id);
        }

        let tenant = existing
            ? await this._tenantRepo.update(input.id, { name: input.name, updatedAt: new Date() })
            : null;
        if (!tenant) {
            const now = new Date();
            tenant = { id: input.id, name: input.name, createdAt: now, updatedAt: now };
            await this._tenantRepo.create(tenant);
        }
        await this._seedAuth(input);
        await this._mount(tenant);
    }

    /**
     * Deprovision a tenant: always unmount + drop the runtime row (so a
     * restart won't re-mount it). The tenant's **CMS data is dropped only
     * when `force`** — a non-force deprovision keeps the collections so the
     * tenant can be restored by re-provisioning the same id.
     */
    async deprovisionTenant(id: string, opts: { force: boolean }): Promise<void> {
        const mounted = this._mounted.get(id);
        if (mounted) {
            unmountTenant(this._runner, mounted);
            this._mounted.delete(id);
        }
        if (opts.force) await purgeTenantData(this._db, id);
        await this._tenantRepo.delete(id);
    }

    /** Snapshot of currently mounted tenants — used by the dashboard. */
    listMounted(): MountedTenant[] {
        return [...this._mounted.values()];
    }

    private async _mount(tenant: Tenant): Promise<void> {
        const mounted = await mountTenant({
            runner:       this._runner,
            db:           this._db,
            tenant,
            appBaseUrl:   this._appBaseUrl,
            secretCrypto: this._secretCrypto,
            session:      this._session,
        });
        this._mounted.set(tenant.id, mounted);
    }
}

export type { TenantRole };
