import { writeFile, rename } from "node:fs/promises";
import type { Bucket } from "../../interfaces/entities/Bucket";

const HEADER = "# Generated by BasicStorageProvider — do not edit by hand.\n";

/**
 * Atomic write of the bucket → 404 file path map fragment, included by the
 * top-level Nginx config inside `map $bucket_id $bucket_notfound { … }`.
 * Buckets without a `notFoundPath` are omitted (nginx falls back to its
 * built-in 404).
 */
export async function regenerateNotFoundPaths(buckets: Bucket[], outputPath: string): Promise<void> {
    const lines = buckets
        .filter(b => typeof b.notFoundPath === "string" && b.notFoundPath.length > 0)
        .map(b => `${b.id} ${quote(b.notFoundPath as string)};`);
    const body = HEADER + lines.join("\n") + (lines.length > 0 ? "\n" : "");
    const tempPath = outputPath + ".tmp";
    await writeFile(tempPath, body);
    await rename(tempPath, outputPath);
}

function quote(value: string): string {
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
