import { writeFile, rename } from "node:fs/promises";
import type { Alias } from "../../interfaces/entities/Alias";

const HEADER = "# Generated by BasicStorageProvider — do not edit by hand.\n";

export type AliasCertPath = (domain: string) => { cert: string; key: string };

const DEFAULT_CERT_PATH: AliasCertPath = (domain) => ({
    cert: `/etc/lego/certificates/${domain}.crt`,
    key:  `/etc/lego/certificates/${domain}.key`,
});

/**
 * Atomic rewrite of the two alias-related Nginx fragments:
 * - `aliases.conf`        — `<host> <bucketId>;` map entries.
 * - `aliasesServers.conf` — one `server { … }` per alias with its TLS pair.
 *
 * Each file is written to a `.tmp` sibling and `rename`d into place so a
 * concurrent `nginx -s reload` never sees a half-written fragment.
 */
export async function regenerateAliases(
    aliases: Alias[],
    aliasesPath: string,
    aliasesServersPath: string,
    bucketServingIncludePath: string,
    certPath: AliasCertPath = DEFAULT_CERT_PATH,
): Promise<void> {
    const mapBody     = HEADER + aliases.map((a) => `${a.domain} ${a.bucketId};`).join("\n") + (aliases.length > 0 ? "\n" : "");
    const serversBody = HEADER + aliases.map((a) => buildServerBlock(a, certPath, bucketServingIncludePath)).join("\n");

    await atomicWrite(aliasesPath,        mapBody);
    await atomicWrite(aliasesServersPath, serversBody);
}

function buildServerBlock(alias: Alias, certPath: AliasCertPath, includePath: string): string {
    const { cert, key } = certPath(alias.domain);
    return `server {
    listen 443 ssl http2;
    server_name ${alias.domain};

    ssl_certificate     ${cert};
    ssl_certificate_key ${key};

    include ${includePath};
}
`;
}

async function atomicWrite(path: string, body: string): Promise<void> {
    const tmp = path + ".tmp";
    await writeFile(tmp, body);
    await rename(tmp, path);
}
