import { writeFile, rename } from "node:fs/promises";
import type { Alias } from "../../interfaces/entities/Alias";
import type { BucketProxy } from "../../interfaces/entities/BucketProxy";
import { renderProxyLocations } from "../proxy/renderProxyLocations";

const HEADER = "# Generated by BasicStorageProvider — do not edit by hand.\n";

export type AliasCertPath = (domain: string) => { cert: string; key: string };

const DEFAULT_CERT_PATH: AliasCertPath = (domain) => ({
    cert: `/etc/lego/certificates/${domain}.crt`,
    key:  `/etc/lego/certificates/${domain}.key`,
});

/**
 * Atomic rewrite of the two alias-related Nginx fragments:
 * - `aliases.conf`        — `<host> <bucketId>;` map entries.
 * - `aliasesServers.conf` — one `server { … }` per alias with its TLS pair,
 *                            plus inline proxy `location` blocks for each
 *                            proxy attached to the alias's bucket.
 *
 * The proxy locations contain `${SECRET_<hex>}` placeholders, NOT plain
 * tokens — `envsubst` resolves them on the edge at reload time using the
 * manifest fetched from `/edge-api/secrets`. The plaintext never lands
 * on persistent disk.
 *
 * Each file is written to a `.tmp` sibling and `rename`d into place so a
 * concurrent `nginx -s reload` never sees a half-written fragment.
 */
export async function regenerateAliases(
    aliases: Alias[],
    proxiesByBucket: Map<string, BucketProxy[]>,
    aliasesPath: string,
    aliasesServersPath: string,
    bucketServingIncludePath: string,
    certPath: AliasCertPath = DEFAULT_CERT_PATH,
): Promise<void> {
    const mapBody     = HEADER + aliases.map((a) => `${a.domain} ${a.bucketId};`).join("\n") + (aliases.length > 0 ? "\n" : "");
    const serversBody = HEADER + aliases.map((a) => {
        const proxies = proxiesByBucket.get(a.bucketId) ?? [];
        return buildServerBlock(a, proxies, certPath, bucketServingIncludePath);
    }).join("\n");

    await atomicWrite(aliasesPath,        mapBody);
    await atomicWrite(aliasesServersPath, serversBody);
}

function buildServerBlock(alias: Alias, proxies: BucketProxy[], certPath: AliasCertPath, includePath: string): string {
    const { cert, key } = certPath(alias.domain);
    const proxyBlock    = proxies.length > 0 ? indent(renderProxyLocations(proxies), 4) + "\n\n" : "";
    return `server {
    listen 443 ssl;
    http2 on;
    server_name ${alias.domain};

    ssl_certificate     ${cert};
    ssl_certificate_key ${key};

${proxyBlock}    include ${includePath};
}
`;
}

function indent(body: string, spaces: number): string {
    const pad = " ".repeat(spaces);
    return body.split("\n").map((line) => line.length > 0 ? pad + line : line).join("\n");
}

async function atomicWrite(path: string, body: string): Promise<void> {
    const tmp = path + ".tmp";
    await writeFile(tmp, body);
    await rename(tmp, path);
}
