

create table if not exists commerce.payment_cancellation_requests (
    id bigint generated by default as identity primary key,
    order_id bigint not null references commerce.orders(id) on delete restrict,
    order_cancellation_request_id bigint references commerce.order_cancellation_requests(id) on delete restrict,
    business_key text not null constraint payment_cancellation_requests_business_key_key unique,
    target_order_status text not null,
    reason text not null,
    status text not null default 'requested',
    provider_payment_id bigint,
    provider_payment_intent_id text,
    provider_operation_id bigint,
    provider_snapshot jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint payment_cancellation_requests_key check (length(btrim(business_key)) > 0),
    constraint payment_cancellation_requests_target check (target_order_status in ('cancelled', 'expired')),
    constraint payment_cancellation_requests_status check (status in (
        'requested', 'processing', 'provider_cancelled', 'refund_pending', 'completed', 'manual_review'
    )),
    constraint payment_cancellation_requests_reason check (length(btrim(reason)) > 0),
    constraint payment_cancellation_requests_provider_payment check (
        provider_payment_id is null or provider_payment_id > 0
    ),
    constraint payment_cancellation_requests_provider_intent check (
        provider_payment_intent_id is null or length(btrim(provider_payment_intent_id)) > 0
    ),
    constraint payment_cancellation_requests_provider_operation check (
        provider_operation_id is null or provider_operation_id > 0
    ),
    constraint payment_cancellation_requests_snapshot check (jsonb_typeof(provider_snapshot) = 'object')
);

create unique index if not exists payment_cancellation_requests_open_order_idx
    on commerce.payment_cancellation_requests(order_id)
    where status in ('requested', 'processing', 'provider_cancelled', 'refund_pending', 'manual_review');
create index if not exists payment_cancellation_requests_due_idx
    on commerce.payment_cancellation_requests(status, created_at, id);
