

create table if not exists commerce.provider_projection_events (
    id bigint generated by default as identity primary key,
    authority text not null,
    provider_event_id text not null,
    order_id bigint not null references commerce.orders(id) on delete restrict,
    event_type text not null,
    occurred_at timestamptz not null,
    payload jsonb not null,
    created_at timestamptz not null default now(),
    constraint provider_projection_events_authority check (authority in ('stripe', 'delivery')),
    constraint provider_projection_events_provider_event check (length(btrim(provider_event_id)) > 0),
    constraint provider_projection_events_payload check (jsonb_typeof(payload) = 'object'),
    constraint provider_projection_events_unique unique (authority, provider_event_id)
);

create index if not exists provider_projection_events_order_idx
    on commerce.provider_projection_events(order_id, occurred_at, id);