

create table if not exists commerce.sellers (
    id bigint generated by default as identity primary key,
    kind text not null,
    cms_user_id text,
    slug text not null unique,
    display_name text not null,
    verification_status text not null default 'pending',
    verified_at timestamptz,
    verified_by text,
    metadata jsonb not null default '{}'::jsonb,
    version integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint sellers_kind check (kind in ('merchant', 'user', 'external')),
    constraint sellers_user_identity check (
        (kind = 'user' and cms_user_id is not null and length(btrim(cms_user_id)) > 0)
        or (kind <> 'user' and cms_user_id is null)
    ),
    constraint sellers_cms_user_id_length check (cms_user_id is null or length(cms_user_id) <= 512),
    constraint sellers_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    constraint sellers_slug_length check (length(slug) <= 160),
    constraint sellers_display_name_not_blank check (length(btrim(display_name)) > 0),
    constraint sellers_display_name_length check (length(display_name) <= 200),
    constraint sellers_verification_status check (
        verification_status in ('pending', 'verified', 'rejected', 'suspended')
    ),
    constraint sellers_verification_audit check (
        (verification_status = 'verified' and verified_at is not null and verified_by is not null)
        or verification_status <> 'verified'
    ),
    constraint sellers_metadata_object check (jsonb_typeof(metadata) = 'object'),
    constraint sellers_metadata_size check (pg_column_size(metadata) <= 65536),
    constraint sellers_version_positive check (version > 0)
);

create unique index if not exists sellers_cms_user_id_unique
    on commerce.sellers(cms_user_id)
    where cms_user_id is not null;

create table if not exists commerce.seller_verification_events (
    id bigint generated by default as identity primary key,
    seller_id bigint not null references commerce.sellers(id) on delete restrict,
    previous_status text,
    next_status text not null,
    actor_id text not null,
    reason text,
    data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint seller_verification_events_previous_status check (
        previous_status is null or previous_status in ('pending', 'verified', 'rejected', 'suspended')
    ),
    constraint seller_verification_events_next_status check (
        next_status in ('pending', 'verified', 'rejected', 'suspended')
    ),
    constraint seller_verification_events_data_object check (jsonb_typeof(data) = 'object')
);