

create table if not exists commerce.order_cancellation_requests (
    id bigint generated by default as identity primary key,
    order_id bigint not null references commerce.orders(id) on delete restrict,
    status text not null default 'requested',
    requested_by_kind text not null,
    requested_by text not null,
    reason text not null,
    decision_reason text,
    decided_by text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint order_cancellation_requests_status check (status in (
        'requested', 'approved', 'rejected', 'provider_cancellation_pending',
        'refund_pending', 'completed', 'manual_review'
    )),
    constraint order_cancellation_requests_actor check (requested_by_kind in ('buyer', 'seller', 'support', 'system')),
    constraint order_cancellation_requests_reason check (length(btrim(reason)) > 0)
);

create unique index if not exists order_cancellation_requests_one_open_idx
    on commerce.order_cancellation_requests(order_id)
    where status in ('requested', 'approved', 'provider_cancellation_pending', 'refund_pending', 'manual_review');

alter table commerce.order_cancellation_requests
    drop constraint if exists order_cancellation_requests_status;
alter table commerce.order_cancellation_requests
    add constraint order_cancellation_requests_status check (status in (
        'requested', 'approved', 'rejected', 'provider_cancellation_pending',
        'refund_pending', 'completed', 'manual_review'
    ));
drop index if exists commerce.order_cancellation_requests_one_open_idx;
create unique index order_cancellation_requests_one_open_idx
    on commerce.order_cancellation_requests(order_id)
    where status in ('requested', 'approved', 'provider_cancellation_pending', 'refund_pending', 'manual_review');