import type { ContentSlot } from "@bernouy/cms-content/editor";

const definitions = [
    ["Change", "change"],
    ["Continue", "continue"],
    ["Product step", "stepProduct"],
    ["Model label", "model"],
    ["Search placeholder", "searchPlaceholder"],
    ["Valuation step", "stepValuation"],
    ["Estimate label", "estimateKicker"],
    ["Empty estimate", "selectValuation"],
    ["Condition label", "estimatedCondition"],
    ["Description step", "stepDescription"],
    ["Description label", "description"],
    ["Description placeholder", "descriptionPlaceholder"],
    ["Photos label", "photos"],
    ["Submission step", "stepSubmit"],
    ["Review explanation", "review"],
    ["Submit action", "submit"],
    ["Search error", "searchFailed"],
    ["Model error", "modelFailed"],
    ["Exact version label", "exactVersion"],
    ["Variant label", "chooseVariant"],
    ["Choose action", "choose"],
    ["Pending range", "rangePending"],
    ["Pending range explanation", "rangePendingDetail"],
    ["Valuation range", "rangeBetween"],
    ["Range explanation", "rangeDetail"],
    ["Maximum photos", "maximumPhotos"],
    ["Preview alternative", "previewAlt"],
    ["Remove photo", "removePhoto"],
    ["Main photo", "mainPhoto"],
    ["One photo count", "photoCountOne"],
    ["Several photos count", "photoCountMany"],
    ["No photo", "noPhoto"],
    ["Add more photos", "addMorePhotos"],
    ["Add photos", "addPhotos"],
    ["Exact photo requirement", "photoRequirementExact"],
    ["Photo range requirement", "photoRequirementRange"],
    ["Expired session", "sessionExpired"],
    ["Submission error", "submissionFailed"],
    ["Photo summary", "summaryPhotos"],
    ["Description added", "descriptionAdded"],
    ["Preparing status", "preparing"],
    ["Seller fallback", "seller"],
    ["Uploading status", "uploading"],
    ["Submitting status", "submitting"],
    ["Submitted status", "submitted"],
    ["Choose product error", "chooseProduct"],
    ["Required field error", "provide"],
    ["Choose variant error", "chooseExactVariant"],
    ["Choose condition error", "chooseCondition"],
    ["Exact photo count error", "invalidPhotoCountExact"],
    ["Photo count range error", "invalidPhotoCountRange"],
    ["Invalid image error", "invalidImage"],
    ["Generic error", "unable"],
] as const;

export const sellCopySlots: ContentSlot[] = definitions.map(([label, name]) => ({
    label,
    slot: copySlotName(name),
    accepts: [{ kind: "any-component" }],
    min: 1,
    max: 1,
}));

function copySlotName(name: string): string {
    return `copy-${name.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)}`;
}
