alter table commerce.settings
    add column if not exists buyer_legal_acceptance_enabled boolean not null default false;
alter table commerce.settings
    add column if not exists buyer_legal_snapshot_origin text;
alter table commerce.settings
    drop constraint if exists settings_buyer_legal_snapshot_origin;
alter table commerce.settings
    add constraint settings_buyer_legal_snapshot_origin check (
        buyer_legal_snapshot_origin is null
        or (
            length(buyer_legal_snapshot_origin) <= 2048
            and buyer_legal_snapshot_origin ~ '^https?://'
        )
    );

create table if not exists commerce.buyer_legal_documents (
    document_key text primary key,
    enabled boolean not null default true,
    current_version_id uuid,
    published_snapshot_url text,
    configured_by text not null,
    version integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint buyer_legal_documents_key_format
        check (document_key ~ '^[a-z][a-z0-9_.-]{1,79}$'),
    constraint buyer_legal_documents_actor_not_blank
        check (length(btrim(configured_by)) > 0),
    constraint buyer_legal_documents_snapshot_url check (
        published_snapshot_url is null
        or (
            length(published_snapshot_url) <= 4096
            and published_snapshot_url ~ '^https?://'
        )
    ),
    constraint buyer_legal_documents_version_positive check (version > 0)
);

create table if not exists commerce.buyer_legal_document_versions (
    id uuid primary key default gen_random_uuid(),
    document_key text not null
        references commerce.buyer_legal_documents(document_key) on delete restrict,
    label text not null,
    consent_text text not null,
    checkout_contexts text[] not null,
    cms_page_id text not null,
    page_path text not null,
    page_title text not null,
    page_description text,
    page_content jsonb not null,
    content_hash text not null,
    materialization_hash text not null,
    materialized_by text not null,
    materialized_at timestamptz not null default now(),
    constraint buyer_legal_versions_label check (length(btrim(label)) between 1 and 200),
    constraint buyer_legal_versions_consent check (length(btrim(consent_text)) between 1 and 1000),
    constraint buyer_legal_versions_contexts_not_empty check (cardinality(checkout_contexts) > 0),
    constraint buyer_legal_versions_contexts_supported check (
        checkout_contexts <@ array[
            'buyer_checkout', 'protected_payment', 'direct_purchase', 'negotiated_offer', 'cart'
        ]::text[]
    ),
    constraint buyer_legal_versions_page_id_not_blank check (length(btrim(cms_page_id)) > 0),
    constraint buyer_legal_versions_page_path check (page_path ~ '^/'),
    constraint buyer_legal_versions_page_title_not_blank check (length(btrim(page_title)) > 0),
    constraint buyer_legal_versions_page_description_length
        check (page_description is null or length(page_description) <= 1000),
    constraint buyer_legal_versions_page_content_string
        check (jsonb_typeof(page_content) = 'string'),
    constraint buyer_legal_versions_content_size check (pg_column_size(page_content) <= 2097152),
    constraint buyer_legal_versions_hash check (content_hash ~ '^[a-f0-9]{64}$'),
    constraint buyer_legal_versions_materialization_hash
        check (materialization_hash ~ '^[a-f0-9]{64}$'),
    constraint buyer_legal_versions_actor_not_blank check (length(btrim(materialized_by)) > 0),
    constraint buyer_legal_versions_identity_unique unique (id, document_key, content_hash),
    constraint buyer_legal_versions_id_document_unique unique (id, document_key)
);

alter table commerce.buyer_legal_documents
    add column if not exists published_snapshot_url text;

alter table commerce.buyer_legal_document_versions
    drop constraint if exists buyer_legal_versions_materialization_unique;
create index if not exists buyer_legal_versions_materialization_idx
    on commerce.buyer_legal_document_versions(document_key, materialization_hash);

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'buyer_legal_documents_current_version_fkey'
          and conrelid = 'commerce.buyer_legal_documents'::regclass
    ) then
        alter table commerce.buyer_legal_documents
            add constraint buyer_legal_documents_current_version_fkey
            foreign key (current_version_id, document_key)
            references commerce.buyer_legal_document_versions(id, document_key)
            on delete restrict;
    end if;
end $$;

create index if not exists buyer_legal_documents_current_version_idx
    on commerce.buyer_legal_documents(current_version_id)
    where current_version_id is not null;

create table if not exists commerce.order_buyer_legal_acceptances (
    id bigint generated by default as identity primary key,
    order_id bigint not null references commerce.orders(id) on delete restrict,
    checkout_group_id uuid not null references commerce.checkout_groups(id) on delete restrict,
    payment_attempt_id bigint not null
        references commerce.order_payment_attempts(id) on delete restrict,
    buyer_cms_user_id text not null,
    document_key text not null,
    document_version_id uuid not null,
    content_hash text not null,
    correlation_id uuid not null,
    accepted_at timestamptz not null default now(),
    constraint order_buyer_legal_acceptances_buyer_not_blank
        check (length(btrim(buyer_cms_user_id)) > 0),
    constraint order_buyer_legal_acceptances_buyer_length
        check (length(buyer_cms_user_id) <= 512),
    constraint order_buyer_legal_acceptances_hash check (content_hash ~ '^[a-f0-9]{64}$'),
    constraint order_buyer_legal_acceptances_version_fkey
        foreign key (document_version_id, document_key, content_hash)
        references commerce.buyer_legal_document_versions(id, document_key, content_hash)
        on delete restrict,
    constraint order_buyer_legal_acceptances_attempt_version_unique
        unique (payment_attempt_id, document_version_id)
);

create index if not exists order_buyer_legal_acceptances_order_idx
    on commerce.order_buyer_legal_acceptances(order_id, accepted_at, id);
create index if not exists order_buyer_legal_acceptances_checkout_idx
    on commerce.order_buyer_legal_acceptances(checkout_group_id, accepted_at, id);
create index if not exists order_buyer_legal_acceptances_version_idx
    on commerce.order_buyer_legal_acceptances(document_version_id);
