

create table if not exists commerce.offer_conditions (
    code text primary key,
    label text not null,
    description text,
    position integer not null default 0,
    enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint offer_conditions_code_format check (code ~ '^[a-z][a-z0-9_]{0,47}$'),
    constraint offer_conditions_label_not_blank check (length(btrim(label)) > 0),
    constraint offer_conditions_label_length check (length(label) <= 200),
    constraint offer_conditions_description_length check (description is null or length(description) <= 2000)
);

create table if not exists commerce.offer_workflow_states (
    code text primary key,
    label text not null,
    phase text not null,
    position integer not null default 0,
    enabled boolean not null default true,
    terminal boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint offer_workflow_states_code_format check (code ~ '^[a-z][a-z0-9_]{0,47}$'),
    constraint offer_workflow_states_label_not_blank check (length(btrim(label)) > 0),
    constraint offer_workflow_states_label_length check (length(label) <= 200),
    constraint offer_workflow_states_phase check (
        phase in ('draft', 'seller_input', 'admin_review', 'ready', 'terminal')
    ),
    constraint offer_workflow_states_terminal_phase check (
        not terminal or phase = 'terminal'
    )
);

create table if not exists commerce.offer_workflow_transitions (
    from_state text not null references commerce.offer_workflow_states(code) on delete restrict,
    action text not null,
    actor_kind text not null,
    to_state text not null references commerce.offer_workflow_states(code) on delete restrict,
    created_at timestamptz not null default now(),
    primary key (from_state, action, actor_kind),
    constraint offer_workflow_transitions_action_format check (action ~ '^[a-z][a-z0-9_]{0,47}$'),
    constraint offer_workflow_transitions_actor check (actor_kind in ('seller', 'admin', 'system')),
    constraint offer_workflow_transitions_changes_state check (from_state <> to_state)
);

create table if not exists commerce.offers (
    id bigint generated by default as identity primary key,
    seller_id bigint not null references commerce.sellers(id) on delete restrict,
    product_id bigint not null references commerce.products(id) on delete restrict,
    variant_id bigint,
    slug text not null constraint offers_slug_key unique,
    title text not null,
    description text,
    condition_code text not null references commerce.offer_conditions(code) on delete restrict,
    publication_status text not null default 'draft',
    workflow_state text not null default 'draft' references commerce.offer_workflow_states(code) on delete restrict,
    accepted_price_amount bigint,
    currency text not null,
    availability text not null default 'available',
    quantity_available integer,
    inventory_revision integer not null default 1,
    metadata jsonb not null default '{}'::jsonb,
    version integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint offers_product_variant_fk foreign key (product_id, variant_id)
        references commerce.product_variants(product_id, id) on delete restrict,
    constraint offers_seller_id_id_unique unique (seller_id, id),
    constraint offers_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    constraint offers_slug_length check (length(slug) <= 160),
    constraint offers_title_not_blank check (length(btrim(title)) > 0),
    constraint offers_title_length check (length(title) <= 300),
    constraint offers_description_length check (description is null or length(description) <= 20000),
    constraint offers_publication_status check (
        publication_status in ('draft', 'active', 'paused', 'archived')
    ),
    constraint offers_currency check (currency ~ '^[a-z]{3}$'),
    constraint offers_accepted_price_non_negative check (
        accepted_price_amount is null or accepted_price_amount between 0 and 9007199254740991
    ),
    constraint offers_active_has_price check (
        publication_status <> 'active' or accepted_price_amount is not null
    ),
    constraint offers_availability check (availability in ('available', 'unavailable', 'preorder')),
    constraint offers_quantity_non_negative check (quantity_available is null or quantity_available between 0 and 1000),
    constraint offers_inventory_revision_positive check (inventory_revision > 0),
    constraint offers_metadata_object check (jsonb_typeof(metadata) = 'object'),
    constraint offers_metadata_size check (pg_column_size(metadata) <= 65536),
    constraint offers_version_positive check (version > 0)
);

create table if not exists commerce.offer_media (
    id bigint generated by default as identity primary key,
    offer_id bigint not null references commerce.offers(id) on delete restrict,
    media_id bigint not null references commerce.media(id) on delete restrict,
    sort_order integer not null default 0,
    is_main boolean not null default false,
    created_at timestamptz not null default now(),
    constraint offer_media_offer_media_unique unique (offer_id, media_id)
);

create unique index if not exists offer_media_main_unique
    on commerce.offer_media(offer_id) where is_main;

create table if not exists commerce.offer_price_rules (
    offer_id bigint primary key references commerce.offers(id) on delete restrict,
    minimum_amount bigint not null,
    maximum_amount bigint not null,
    currency text not null,
    configured_by text not null,
    version integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint offer_price_rules_range check (
        minimum_amount >= 0 and maximum_amount >= minimum_amount
        and maximum_amount <= 9007199254740991
    ),
    constraint offer_price_rules_currency check (currency ~ '^[a-z]{3}$'),
    constraint offer_price_rules_version_positive check (version > 0)
);
