create table if not exists commerce.sale_capability_requirements (
    capability_key text primary key,
    seller_kind text not null,
    enabled boolean not null default true,
    configured_by text not null,
    version integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint sale_capability_requirements_key_format
        check (capability_key ~ '^[a-z][a-z0-9_.-]{1,79}$'),
    constraint sale_capability_requirements_seller_kind
        check (seller_kind in ('merchant', 'user', 'external')),
    constraint sale_capability_requirements_actor_not_blank
        check (length(btrim(configured_by)) > 0),
    constraint sale_capability_requirements_version_positive check (version > 0)
);

create table if not exists commerce.seller_sale_capabilities (
    seller_id bigint not null references commerce.sellers(id) on delete restrict,
    capability_key text not null
        references commerce.sale_capability_requirements(capability_key) on delete restrict,
    ready boolean not null,
    evidence_reference text,
    confirmed_at timestamptz,
    revoked_at timestamptz,
    version integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (seller_id, capability_key),
    constraint seller_sale_capabilities_evidence_length
        check (evidence_reference is null or length(evidence_reference) <= 200),
    constraint seller_sale_capabilities_state check (
        (ready and confirmed_at is not null and revoked_at is null)
        or (not ready and revoked_at is not null)
    ),
    constraint seller_sale_capabilities_version_positive check (version > 0)
);

create index if not exists seller_sale_capabilities_capability_key_idx
    on commerce.seller_sale_capabilities(capability_key);

create table if not exists commerce.price_agreements (
    id bigint generated by default as identity primary key,
    public_id uuid not null default gen_random_uuid() constraint price_agreements_public_id_key unique,
    authority_key text not null,
    authority_reference text not null,
    authority_version integer not null,
    offer_id bigint not null references commerce.offers(id) on delete restrict,
    seller_id bigint not null references commerce.sellers(id) on delete restrict,
    buyer_cms_user_id text not null,
    unit_amount bigint not null,
    currency text not null,
    quantity integer not null default 1,
    status text not null default 'active',
    expires_at timestamptz not null,
    order_id bigint constraint price_agreements_order_id_key unique references commerce.orders(id) on delete restrict,
    consumed_at timestamptz,
    canceled_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint price_agreements_authority_key_format
        check (authority_key ~ '^[a-z][a-z0-9_.-]{1,79}$'),
    constraint price_agreements_authority_reference_not_blank
        check (length(btrim(authority_reference)) > 0),
    constraint price_agreements_authority_reference_length
        check (length(authority_reference) <= 200),
    constraint price_agreements_authority_version_positive
        check (authority_version > 0),
    constraint price_agreements_buyer_not_blank
        check (length(btrim(buyer_cms_user_id)) > 0),
    constraint price_agreements_buyer_length check (length(buyer_cms_user_id) <= 512),
    constraint price_agreements_amount
        check (unit_amount between 0 and 9007199254740991),
    constraint price_agreements_currency check (currency ~ '^[a-z]{3}$'),
    constraint price_agreements_quantity check (quantity between 1 and 1000),
    constraint price_agreements_subtotal_supported check (
        unit_amount::numeric * quantity <= 9007199254740991
    ),
    constraint price_agreements_status
        check (status in ('active', 'consumed', 'expired', 'canceled')),
    constraint price_agreements_expiry_after_creation check (expires_at > created_at),
    constraint price_agreements_consumption_state check (
        (status = 'consumed' and order_id is not null and consumed_at is not null)
        or (status <> 'consumed' and order_id is null and consumed_at is null)
    ),
    constraint price_agreements_cancellation_state check (
        (status = 'canceled' and canceled_at is not null)
        or (status <> 'canceled' and canceled_at is null)
    ),
    constraint price_agreements_offer_seller_fk foreign key (seller_id, offer_id)
        references commerce.offers(seller_id, id) on delete restrict,
    constraint price_agreements_offer_id_id_unique unique (offer_id, id),
    constraint price_agreements_authority_reference_unique
        unique (authority_key, authority_reference)
);

alter table commerce.price_agreements
    add column if not exists authority_version integer not null default 1;

alter table commerce.price_agreements
    alter column authority_version drop default;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'price_agreements_authority_version_positive'
          and conrelid = 'commerce.price_agreements'::regclass
    ) then
        alter table commerce.price_agreements
            add constraint price_agreements_authority_version_positive
            check (authority_version > 0);
    end if;
    if not exists (
        select 1 from pg_constraint
        where conname = 'price_agreements_subtotal_supported'
          and conrelid = 'commerce.price_agreements'::regclass
    ) then
        alter table commerce.price_agreements
            add constraint price_agreements_subtotal_supported
            check (unit_amount::numeric * quantity <= 9007199254740991);
    end if;
end $$;

create unique index if not exists price_agreements_one_active_per_offer
    on commerce.price_agreements(offer_id) where status = 'active';

create index if not exists price_agreements_seller_offer_idx
    on commerce.price_agreements(seller_id, offer_id);

create index if not exists price_agreements_buyer_status_created_idx
    on commerce.price_agreements(buyer_cms_user_id, status, created_at desc);

create index if not exists price_agreements_active_expiry_idx
    on commerce.price_agreements(expires_at) where status = 'active';
