

create table if not exists commerce.stripe_dispute_projections (
    id bigint generated by default as identity primary key,
    order_id bigint not null references commerce.orders(id) on delete restrict,
    provider_dispute_id text not null constraint stripe_dispute_projections_provider_dispute_id_key unique,
    status text not null,
    reason text,
    amount bigint not null,
    currency text not null,
    evidence_due_by timestamptz,
    funds_withdrawn boolean not null default false,
    provider_snapshot jsonb not null default '{}'::jsonb,
    opened_at timestamptz not null,
    closed_at timestamptz,
    updated_at timestamptz not null default now(),
    constraint stripe_dispute_projections_status check (status in (
        'warning_needs_response', 'warning_under_review', 'warning_closed',
        'needs_response', 'under_review', 'won', 'lost', 'prevented', 'manual_review'
    )),
    constraint stripe_dispute_projections_amount check (amount between 1 and 9007199254740991),
    constraint stripe_dispute_projections_currency check (currency = 'eur'),
    constraint stripe_dispute_projections_snapshot check (jsonb_typeof(provider_snapshot) = 'object')
);

alter table commerce.stripe_dispute_projections
    add column if not exists funds_withdrawn boolean not null default false;

create index if not exists stripe_dispute_projections_order_idx
    on commerce.stripe_dispute_projections(order_id, status, updated_at desc);
