import { describe, expect, test } from "bun:test";
import {
    createSourceImageInterceptor,
    InMemorySourceImageCache,
    SOURCE_RESPONSIVE_WEBP_V1,
} from "@bernouy/cms-source-images";
import { interceptorHarness, invoke, sourceRequest } from "../../helpers/interceptorHarness";

describe("Source image failure telemetry", () => {
    test("delivers generated bytes but does not claim a cache hit when storage fails", async () => {
        class FailingCache extends InMemorySourceImageCache {
            override async putDerivative(): Promise<{ evicted: number }> {
                throw new Error("disk full");
            }
        }
        const harness = interceptorHarness({ cache: new FailingCache() });
        const first = await invoke(harness.interceptor, harness.endpoint, sourceRequest(), harness.next);
        const second = await invoke(harness.interceptor, harness.endpoint, sourceRequest(), harness.next);
        expect(first.headers.get("content-type")).toBe("image/webp");
        expect(first.headers.get("cache-control")).toBe("public, max-age=3600, must-revalidate");
        expect(second.headers.get("content-type")).toBe("image/webp");
        expect(harness.next).toHaveBeenCalledTimes(2);
        expect(harness.transformer.transformCalls).toBe(2);
        expect(harness.observations).toHaveLength(2);
        expect(harness.observations.every((observation) => observation.cacheErrors === 1)).toBe(true);
    });

    test("counts cache reads and lookup publication failures without failing delivery", async () => {
        class FailingCache extends InMemorySourceImageCache {
            override async getDerivative(): Promise<null> {
                throw new Error("cache read failed");
            }

            override async putLookup(): Promise<void> {
                throw new Error("lookup write failed");
            }
        }
        const harness = interceptorHarness({ cache: new FailingCache() });

        const response = await invoke(harness.interceptor, harness.endpoint, sourceRequest(), harness.next);

        expect(response.status).toBe(200);
        expect(response.headers.get("content-type")).toBe("image/webp");
        expect(harness.observations).toHaveLength(1);
        expect(harness.observations[0]).toMatchObject({
            outcome: "generated",
            cache: "miss",
            cacheErrors: 3,
        });
    });

    test("observer failures never alter the image response", async () => {
        const harness = interceptorHarness();
        const interceptor = createSourceImageInterceptor({
            cache: harness.cache,
            transformer: harness.transformer,
            scope: "observer-failure",
            recipe: SOURCE_RESPONSIVE_WEBP_V1,
            observe: () => {
                throw new Error("metrics offline");
            },
        });
        const response = await invoke(interceptor, harness.endpoint, sourceRequest(), harness.next);
        expect(response.status).toBe(200);
        expect(response.headers.get("content-type")).toBe("image/webp");
    });

    test("emits closed aggregate byte and stage metrics only", async () => {
        const harness = interceptorHarness();
        await invoke(harness.interceptor, harness.endpoint, sourceRequest(), harness.next);
        expect(harness.observations[0]).toMatchObject({
            outcome: "generated",
            width: 384,
            sourceBytes: 12,
            cache: "miss",
        });
        expect(harness.observations[0]?.outputBytes).toBeGreaterThan(12);
        expect(harness.observations[0]?.compressionRatio).toBeGreaterThan(0);
        expect(Object.keys(harness.observations[0]?.stagesMs ?? {}).sort()).toEqual([
            "decode",
            "encode",
            "read",
            "semaphore_wait",
            "store",
            "upstream",
        ]);
    });
});
