export const PAGE_TAGS = new Set([
    "a",
    "abbr",
    "article",
    "aside",
    "b",
    "blockquote",
    "br",
    "button",
    "code",
    "cite",
    "div",
    "em",
    "form",
    "figcaption",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "header",
    "input",
    "img",
    "label",
    "li",
    "main",
    "nav",
    "ol",
    "optgroup",
    "output",
    "p",
    "pre",
    "section",
    "select",
    "small",
    "span",
    "strong",
    "svg",
    "textarea",
    "ul",
    "option",
]);

export const PAGE_NATIVE_ATTRIBUTES: Readonly<Record<string, ReadonlySet<string>>> = {
    a: new Set([
        "slot",
        "href",
        "target",
        "rel",
        "aria-current",
        "data-cms-page-ref",
        "data-cms-page-suffix",
        "data-cms-success-page-ref",
    ]),
    button: new Set(["slot", "type", "disabled", "name", "value"]),
    img: new Set([
        "slot",
        "src",
        "alt",
        "role",
        "aria-hidden",
        "loading",
        "fetchpriority",
        "width",
        "height",
        "decoding",
    ]),
    input: new Set([
        "slot",
        "type",
        "name",
        "value",
        "checked",
        "disabled",
        "required",
        "readonly",
        "autocomplete",
        "placeholder",
        "min",
        "max",
        "step",
        "multiple",
        "accept",
        "inputmode",
        "role",
    ]),
    label: new Set(["slot", "for"]),
    option: new Set(["slot", "value", "selected", "disabled"]),
    optgroup: new Set(["slot", "label", "disabled"]),
    output: new Set(["slot", "name", "for", "aria-live"]),
    select: new Set(["slot", "name", "multiple", "size", "required", "disabled"]),
    svg: new Set(["slot", "role", "aria-hidden", "aria-label"]),
    textarea: new Set([
        "slot",
        "name",
        "rows",
        "required",
        "readonly",
        "disabled",
        "autocomplete",
        "placeholder",
        "maxlength",
    ]),
};

export const PAGE_INPUT_TYPES = new Set([
    "checkbox",
    "date",
    "datetime-local",
    "email",
    "file",
    "hidden",
    "month",
    "number",
    "password",
    "radio",
    "search",
    "tel",
    "text",
    "time",
    "url",
    "week",
]);
