import { claimEvidenceRows, claimEvents, claimReturnEvents, claimRow } from "./fixtures";

export function expectedClaimDetail(): Record<string, unknown> {
    return {
        id: 7,
        publicId: claimRow.public_id,
        orderId: 42,
        buyerCmsUserId: "buyer-17",
        sellerId: 4,
        reason: "not_as_described",
        status: "return_required",
        description: "The received item differs from the listing.",
        buyerRequestedAmount: 10_000,
        resolutionOutcome: "return_required",
        resolutionBuyerRefundAmount: null,
        resolutionSellerTransferAmount: null,
        resolutionProtectionFeeRefundAmount: null,
        decisionReason: "Return the item before resolution.",
        sellerResponseByAt: "2026-07-18T08:00:00.000Z",
        returnShipByAt: "2026-07-25T08:00:00.000Z",
        returnDeliveryStatus: "carrier_accepted",
        returnProviderReference: "return-42",
        returnCarrierAcceptedAt: "2026-07-20T08:00:00.000Z",
        returnRecipientHandoffAt: null,
        resolvedAt: null,
        resolvedBy: null,
        version: 3,
        createdAt: "2026-07-17T08:00:00.000Z",
        updatedAt: "2026-07-20T08:00:00.000Z",
        events: claimEvents.map(event => ({
            id: event.id,
            claimId: event.claim_id,
            eventType: event.event_type,
            actorKind: event.actor_kind,
            actorId: event.actor_id,
            message: event.message,
            data: event.data,
            createdAt: event.created_at,
        })),
        evidence: claimEvidenceRows.map(evidence => ({
            id: evidence.id,
            claimId: evidence.claim_id,
            submittedByKind: evidence.submitted_by_kind,
            mimeType: evidence.mime_type,
            fileSize: evidence.file_size,
            originalFilename: evidence.original_filename,
            sha256: evidence.sha256,
            description: evidence.description,
            metadata: evidence.metadata,
            createdAt: evidence.created_at,
        })),
        returnEvents: claimReturnEvents.map(event => ({
            id: event.id,
            providerEventId: event.provider_event_id,
            providerReference: event.provider_reference,
            normalizedStatus: event.normalized_status,
            occurredAt: event.occurred_at,
            createdAt: event.created_at,
        })),
    };
}
