import { registerAccountProviderBoundaryContracts } from "../../provider-boundary/accounts.contracts";
import { registerDisputeApplicationReadContextContracts } from "../../provider-boundary/dispute-application/read-context.contracts";
import { registerDisputeApprovalContracts } from "../../provider-boundary/dispute-approval/approval.contracts";
import { registerDisputeApprovalCompletionContracts } from "../../provider-boundary/dispute-approval/completion.contracts";
import { registerDisputeApprovalFailureContracts } from "../../provider-boundary/dispute-approval/failures.contracts";
import { registerDisputeApprovalSubmissionContracts } from "../../provider-boundary/dispute-approval/submission.contracts";
import { registerDisputeFileProviderBoundaryContracts } from "../../provider-boundary/dispute-writes/files.contracts";
import { registerDisputeStagingContracts } from "../../provider-boundary/dispute-writes/staging.contracts";
import { registerProtectedPaymentFailureContracts } from "../../provider-boundary/protected-payment/failures.contracts";
import { registerPlatformPayoutProtectionFailureContracts } from "../../provider-boundary/protected-payment/platform-protection/failures.contracts";
import { registerPlatformPayoutProtectionValidationContracts } from "../../provider-boundary/protected-payment/platform-protection/validation.contracts";
import { registerPlatformPayoutProtectionWorkflowContracts } from "../../provider-boundary/protected-payment/platform-protection/workflow.contracts";
import { registerProtectedPaymentPayoutContracts } from "../../provider-boundary/protected-payment/payout.contracts";
import { registerProtectedPaymentProjectionRaceContracts } from "../../provider-boundary/protected-payment/projection-races.contracts";
import { registerProtectedPaymentReservationContracts } from "../../provider-boundary/protected-payment/reservation.contracts";
import { registerProtectedPaymentReplayContracts } from "../../provider-boundary/protected-payment/replay.contracts";
import { registerProtectedRefundFailureContracts } from "../../provider-boundary/protected-refund/failures.contracts";
import { registerProtectedRefundRecoveryContracts } from "../../provider-boundary/protected-refund/recovery.contracts";
import { registerProtectedRefundReplayContracts } from "../../provider-boundary/protected-refund/replay.contracts";
import { registerProtectedRefundSellerRecoveryContracts } from "../../provider-boundary/protected-refund/seller-recovery.contracts";
import { registerProtectedRefundSuccessContracts } from "../../provider-boundary/protected-refund/success/contracts";
import { registerProtectedRefundPreflightInterleavingContracts } from "../../provider-boundary/protected-refund/success/preflight-interleavings.contracts";
import { registerProtectedRefundProjectionInterleavingContracts } from "../../provider-boundary/protected-refund/success/projection-interleavings.contracts";
import { registerProtectedRefundProjectionStatusContracts } from "../../provider-boundary/protected-refund/success/projection-statuses.contracts";
import { registerProtectedRefundValidationContracts } from "../../provider-boundary/protected-refund/validations.contracts";
import { registerTransferReversalCompletionSnapshotContracts } from "../../provider-boundary/transfer-reversal/completion-snapshots.contracts";
import { registerTransferReversalFailureContracts } from "../../provider-boundary/transfer-reversal/failures.contracts";
import { registerTransferReversalRecoveryContracts } from "../../provider-boundary/transfer-reversal/recovery.contracts";
import { registerTransferReversalSuccessContracts } from "../../provider-boundary/transfer-reversal/success.contracts";
import type { BoundaryHarnesses } from "./harnesses";

export function registerProviderBoundaryContracts(harnesses: BoundaryHarnesses): void {
    const createHarness = harnesses.providerBoundary;
    registerAccountProviderBoundaryContracts(createHarness);
    registerDisputeApplicationReadContextContracts(createHarness);
    registerDisputeApprovalContracts(createHarness);
    registerDisputeApprovalCompletionContracts(createHarness);
    registerDisputeApprovalFailureContracts(createHarness);
    registerDisputeApprovalSubmissionContracts(createHarness);
    registerDisputeFileProviderBoundaryContracts(createHarness);
    registerDisputeStagingContracts(createHarness);
    registerProtectedPaymentFailureContracts(createHarness);
    registerPlatformPayoutProtectionFailureContracts(createHarness);
    registerPlatformPayoutProtectionValidationContracts(createHarness);
    registerPlatformPayoutProtectionWorkflowContracts(createHarness);
    registerProtectedPaymentPayoutContracts(createHarness);
    registerProtectedPaymentProjectionRaceContracts(createHarness);
    registerProtectedPaymentReservationContracts(createHarness);
    registerProtectedPaymentReplayContracts(createHarness);
    registerProtectedRefundFailureContracts(createHarness);
    registerProtectedRefundRecoveryContracts(createHarness);
    registerProtectedRefundReplayContracts(createHarness);
    registerProtectedRefundSellerRecoveryContracts(createHarness);
    registerProtectedRefundSuccessContracts(createHarness);
    registerProtectedRefundProjectionInterleavingContracts(createHarness);
    registerProtectedRefundProjectionStatusContracts(createHarness);
    registerProtectedRefundPreflightInterleavingContracts(createHarness);
    registerProtectedRefundValidationContracts(createHarness);
    registerTransferReversalCompletionSnapshotContracts(createHarness);
    registerTransferReversalFailureContracts(createHarness);
    registerTransferReversalRecoveryContracts(createHarness);
    registerTransferReversalSuccessContracts(createHarness);
}
