

create table if not exists commerce.fee_policies (
    id bigint generated by default as identity primary key,
    policy_key text not null,
    version integer not null,
    name text not null,
    status text not null default 'draft',
    currency text not null default 'eur',
    shipping_beneficiary text not null default 'platform',
    estimated_stripe_cost_amount bigint not null default 0,
    estimated_carrier_cost_amount bigint not null default 0,
    platform_risk_reserve_contribution_amount bigint not null default 0,
    configured_minimum_margin_amount bigint not null default 0,
    cost_estimates_configured boolean not null default false,
    subsidy_override boolean not null default false,
    subsidy_reason text,
    published_at timestamptz,
    created_by text not null,
    created_at timestamptz not null default now(),
    constraint fee_policies_key_format check (policy_key ~ '^[a-z][a-z0-9_-]{0,63}$'),
    constraint fee_policies_version_positive check (version > 0),
    constraint fee_policies_name_not_blank check (length(btrim(name)) > 0),
    constraint fee_policies_status check (status in ('draft', 'published', 'retired')),
    constraint fee_policies_currency check (currency = 'eur'),
    constraint fee_policies_shipping_beneficiary check (shipping_beneficiary in ('platform', 'seller')),
    constraint fee_policies_amounts check (
        estimated_stripe_cost_amount between 0 and 9007199254740991
        and estimated_carrier_cost_amount between 0 and 9007199254740991
        and platform_risk_reserve_contribution_amount between 0 and 9007199254740991
        and configured_minimum_margin_amount between 0 and 9007199254740991
    ),
    constraint fee_policies_subsidy_reason check (not subsidy_override or length(btrim(subsidy_reason)) > 0),
    constraint fee_policies_publication check (
        (status = 'draft' and published_at is null) or (status <> 'draft' and published_at is not null)
    ),
    constraint fee_policies_key_version_unique unique (policy_key, version)
);

create table if not exists commerce.fee_policy_components (
    id bigint generated by default as identity primary key,
    fee_policy_id bigint not null references commerce.fee_policies(id) on delete restrict,
    component_key text not null,
    payer text not null,
    basis text not null,
    rate_bps integer not null default 0,
    fixed_amount bigint not null default 0,
    minimum_amount bigint,
    maximum_amount bigint,
    rounding_mode text not null default 'round_half_up',
    refund_policy text not null default 'proportional',
    position integer not null default 0,
    created_at timestamptz not null default now(),
    constraint fee_policy_components_key check (component_key in ('buyer_protection', 'seller_commission')),
    constraint fee_policy_components_payer check (payer in ('buyer', 'seller')),
    constraint fee_policy_components_key_payer check (
        (component_key = 'buyer_protection' and payer = 'buyer')
        or (component_key = 'seller_commission' and payer = 'seller')
    ),
    constraint fee_policy_components_basis check (basis in ('merchandise', 'merchandise_and_shipping')),
    constraint fee_policy_components_rate check (rate_bps between 0 and 10000),
    constraint fee_policy_components_amounts check (
        fixed_amount between 0 and 9007199254740991
        and (minimum_amount is null or minimum_amount between 0 and 9007199254740991)
        and (maximum_amount is null or maximum_amount between 0 and 9007199254740991)
        and (minimum_amount is null or maximum_amount is null or minimum_amount <= maximum_amount)
        and (maximum_amount is null or fixed_amount <= maximum_amount)
    ),
    constraint fee_policy_components_rounding check (rounding_mode = 'round_half_up'),
    constraint fee_policy_components_refund check (refund_policy in ('always', 'never', 'proportional', 'resolution_defined')),
    constraint fee_policy_components_policy_key_unique unique (fee_policy_id, component_key)
);

alter table commerce.fee_policy_components
    drop constraint if exists fee_policy_components_amounts;
alter table commerce.fee_policy_components
    add constraint fee_policy_components_amounts check (
        fixed_amount between 0 and 9007199254740991
        and (minimum_amount is null or minimum_amount between 0 and 9007199254740991)
        and (maximum_amount is null or maximum_amount between 0 and 9007199254740991)
        and (minimum_amount is null or maximum_amount is null or minimum_amount <= maximum_amount)
        and (maximum_amount is null or fixed_amount <= maximum_amount)
    );

create index if not exists fee_policy_components_policy_idx
    on commerce.fee_policy_components(fee_policy_id);

create table if not exists commerce.protection_policies (
    id bigint generated by default as identity primary key,
    policy_key text not null,
    version integer not null,
    name text not null,
    status text not null default 'draft',
    currency text not null default 'eur',
    payment_window_minutes integer not null default 30,
    seller_handoff_hours integer not null default 72,
    scan_grace_hours integer not null default 48,
    claim_window_hours integer not null default 48,
    seller_response_hours integer not null default 72,
    return_ship_hours integer not null default 168,
    finance_review_threshold_amount bigint not null default 50000,
    dual_approval_threshold_amount bigint not null default 100000,
    published_at timestamptz,
    created_by text not null,
    created_at timestamptz not null default now(),
    constraint protection_policies_key_format check (policy_key ~ '^[a-z][a-z0-9_-]{0,63}$'),
    constraint protection_policies_version_positive check (version > 0),
    constraint protection_policies_name_not_blank check (length(btrim(name)) > 0),
    constraint protection_policies_status check (status in ('draft', 'published', 'retired')),
    constraint protection_policies_currency check (currency = 'eur'),
    constraint protection_policies_durations check (
        payment_window_minutes between 1 and 1440
        and seller_handoff_hours between 1 and 720
        and scan_grace_hours between 1 and 720
        and claim_window_hours between 1 and 720
        and seller_response_hours between 1 and 720
        and return_ship_hours between 1 and 2160
    ),
    constraint protection_policies_thresholds check (
        finance_review_threshold_amount between 0 and 9007199254740991
        and dual_approval_threshold_amount between finance_review_threshold_amount and 9007199254740991
    ),
    constraint protection_policies_publication check (
        (status = 'draft' and published_at is null) or (status <> 'draft' and published_at is not null)
    ),
    constraint protection_policies_key_version_unique unique (policy_key, version)
);