export const BEHAVIORAL_RLS_AUTHOR_INPUT_SCHEMA = "cms.integration.behavioral-rls-author-input.v1" as const;
export const BEHAVIORAL_RLS_PLAN_SCHEMA = "cms.integration.behavioral-rls-plan.v1" as const;

export type BehavioralRlsScalarV1 = string | number | boolean | null;

export type BehavioralRlsFixtureV1 = Readonly<{
    key: BehavioralRlsScalarV1;
    values: Readonly<Record<string, BehavioralRlsScalarV1>>;
}>;

export type BehavioralRlsProbeV1 = Readonly<{
    probeId: string;
    namespace: string;
    relation: string;
    keyColumn: string;
    subjectColumn: string;
    first: BehavioralRlsFixtureV1;
    second: BehavioralRlsFixtureV1;
    firstCrossInsert: BehavioralRlsFixtureV1;
    secondCrossInsert: BehavioralRlsFixtureV1;
}>;

/** Author-owned fixture input. It cannot bind policy or candidate identity. */
export type BehavioralRlsAuthorInputV1 = Readonly<{
    schema: typeof BEHAVIORAL_RLS_AUTHOR_INPUT_SCHEMA;
    probes: readonly BehavioralRlsProbeV1[];
}>;

/** Policy-owned, immutable execution input generated by the repository. */
export type BehavioralRlsPlanV1 = Readonly<{
    schema: typeof BEHAVIORAL_RLS_PLAN_SCHEMA;
    target: Readonly<{
        kind: string;
        version: string;
        candidateDigest: string;
        packageDigest: string;
        verificationDigest: string;
    }>;
    policyDigest: string;
    probes: readonly BehavioralRlsProbeV1[];
}>;

export type IdentifiedBehavioralRlsPlanV1 = Readonly<{
    plan: BehavioralRlsPlanV1;
    canonicalBytes: Uint8Array;
    digest: string;
}>;

export type AdmissionBehavioralRlsPlanBindingV1 = Readonly<{
    digest: string;
    plan: BehavioralRlsPlanV1;
}>;
