

create table if not exists commerce.financial_subsidy_overrides (
    id bigint generated by default as identity primary key,
    fee_policy_id bigint not null references commerce.fee_policies(id) on delete restrict,
    maximum_deficit_amount bigint not null,
    reason text not null,
    approved_by text not null,
    expires_at timestamptz,
    created_at timestamptz not null default now(),
    constraint financial_subsidy_overrides_amount check (
        maximum_deficit_amount between 0 and 9007199254740991
    ),
    constraint financial_subsidy_overrides_reason check (length(btrim(reason)) > 0),
    constraint financial_subsidy_overrides_approver check (length(btrim(approved_by)) > 0)
);

create index if not exists financial_subsidy_overrides_policy_idx
    on commerce.financial_subsidy_overrides(fee_policy_id, expires_at);