

create table if not exists commerce.orders (
    id bigint generated by default as identity primary key,
    public_id uuid not null default gen_random_uuid() unique,
    order_number text not null unique,
    checkout_group_id uuid not null default gen_random_uuid()
        references commerce.checkout_groups(id) on delete restrict,
    seller_id bigint not null references commerce.sellers(id) on delete restrict,
    buyer_cms_user_id text not null,
    status text not null default 'awaiting_quote',
    currency text not null,
    subtotal_amount bigint not null,
    shipping_amount bigint not null default 0,
    delivery_quoted_at timestamptz,
    total_amount bigint not null,
    shipping_address jsonb not null default '{}'::jsonb,
    billing_address jsonb not null default '{}'::jsonb,
    metadata jsonb not null default '{}'::jsonb,
    idempotency_key text not null,
    request_hash text not null,
    archived_at timestamptz,
    version integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint orders_buyer_not_blank check (length(btrim(buyer_cms_user_id)) > 0),
    constraint orders_buyer_length check (length(buyer_cms_user_id) <= 512),
    constraint orders_status check (status in (
        'awaiting_quote', 'awaiting_payment', 'active', 'completed',
        'expired', 'cancellation_pending', 'cancelled'
    )),
    constraint orders_currency check (currency ~ '^[a-z]{3}$'),
    constraint orders_amounts_non_negative check (
        subtotal_amount >= 0 and shipping_amount >= 0
        and total_amount >= subtotal_amount + shipping_amount
        and total_amount <= 9007199254740991
    ),
    constraint orders_shipping_address_object check (jsonb_typeof(shipping_address) = 'object'),
    constraint orders_shipping_address_size check (pg_column_size(shipping_address) <= 65536),
    constraint orders_billing_address_object check (jsonb_typeof(billing_address) = 'object'),
    constraint orders_billing_address_size check (pg_column_size(billing_address) <= 65536),
    constraint orders_metadata_object check (jsonb_typeof(metadata) = 'object'),
    constraint orders_metadata_size check (pg_column_size(metadata) <= 65536),
    constraint orders_idempotency_not_blank check (length(btrim(idempotency_key)) > 0),
    constraint orders_idempotency_length check (length(idempotency_key) <= 200),
    constraint orders_request_hash_format check (request_hash ~ '^[a-f0-9]{32}$'),
    constraint orders_seller_id_id_unique unique (seller_id, id),
    constraint orders_version_positive check (version > 0)
);

alter table commerce.orders
    add column if not exists shipping_amount bigint not null default 0;
alter table commerce.orders
    add column if not exists delivery_quoted_at timestamptz;
alter table commerce.orders
    add column if not exists archived_at timestamptz;

alter table commerce.orders drop constraint if exists orders_status;
update commerce.orders set status = 'awaiting_quote' where status = 'placed';
update commerce.orders set status = 'completed', archived_at = coalesce(archived_at, now())
where status = 'archived';
alter table commerce.orders add constraint orders_status check (status in (
    'awaiting_quote', 'awaiting_payment', 'active', 'completed',
    'expired', 'cancellation_pending', 'cancelled'
));
alter table commerce.orders drop constraint if exists orders_amounts_non_negative;
alter table commerce.orders add constraint orders_amounts_non_negative check (
    subtotal_amount >= 0 and shipping_amount >= 0
    and total_amount >= subtotal_amount + shipping_amount
    and total_amount <= 9007199254740991
);

alter table commerce.orders drop constraint if exists orders_buyer_idempotency_unique;
alter table commerce.orders alter column checkout_group_id set default gen_random_uuid();

insert into commerce.checkout_groups (
    id, buyer_cms_user_id, idempotency_key, request_hash, created_at
)
select
    checkout_group_id, buyer_cms_user_id, idempotency_key, request_hash, created_at
from commerce.orders
on conflict do nothing;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'orders_checkout_group_id_fkey'
          and conrelid = 'commerce.orders'::regclass
    ) then
        alter table commerce.orders
            add constraint orders_checkout_group_id_fkey
            foreign key (checkout_group_id) references commerce.checkout_groups(id) on delete restrict;
    end if;
end $$;