import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { categoryToFolder } from "cms-cli/push/shared/categoryFolder";
import { GENERATED_INTEGRATION_INSTANCES_FILE } from "cms-cli/dev-server/integrations";
import { safeJoin } from "cms-cli/push/shared/safeJoin";
import type { IntegrationInstance } from "@bernouy/cms-integrations";

const HEADERS = (token: string) => ({ "Authorization": `Bearer ${token}` });

export type PullBlocsResult = {
    pulled:  string[];
    skipped: { tag: string; reason: string }[];
    failed:  { tag: string; error:  string }[];
};

export type RemoteBlocSummary = { tag: string; group: string };

/**
 * Download every bloc that has a `source` bundle on the remote and write
 * its files under `<siteDir>/blocs/<group>/<tag>/`. Blocs uploaded before
 * the source-bundle feature have no bundle — we report them under
 * `skipped` so the user knows to push them once with the new CLI to make
 * them pull-able. The `default-group` field is stripped from
 * `manifest.json` on write, since the group is carried by the folder layout.
 */
export async function pullBlocs(adminBase: URL, token: string, siteDir: string): Promise<PullBlocsResult> {
    const out: PullBlocsResult = { pulled: [], skipped: [], failed: [] };
    const list = await fetchRemoteBlocList(adminBase, token);
    const generatedIntegrationBlocs = await readGeneratedIntegrationBlocIds(siteDir);

    for (const { tag, group } of list) {
        if (generatedIntegrationBlocs.has(tag)) {
            out.skipped.push({ tag, reason: "generated by an integration; use `p9r pull --type=integrations`" });
            continue;
        }
        try {
            const source = await fetchBlocSource(adminBase, token, tag);
            if (source === null) {
                out.skipped.push({ tag, reason: "no source bundle on the server" });
                continue;
            }
            const target = safeJoin(siteDir, "blocs", categoryToFolder(group), tag);
            await writeBlocSource(target, source);
            out.pulled.push(tag);
        } catch (err) {
            out.failed.push({ tag, error: err instanceof Error ? err.message : String(err) });
        }
    }
    return out;
}

export async function fetchRemoteBlocList(adminBase: URL, token: string): Promise<RemoteBlocSummary[]> {
    const url = new URL("api/bloc/list", adminBase).href;
    const res = await fetch(url, { headers: HEADERS(token) });
    if (!res.ok) throw new Error(`GET ${url} → HTTP ${res.status}`);
    const data = await res.json() as { id: string; group?: string }[];
    return data.map(b => ({ tag: b.id, group: b.group ?? "" }));
}

export async function fetchBlocSource(adminBase: URL, token: string, tag: string): Promise<Record<string, string> | null> {
    const url = new URL(`api/bloc/source?tag=${encodeURIComponent(tag)}`, adminBase).href;
    const res = await fetch(url, { headers: HEADERS(token) });
    if (res.status === 404) return null;
    if (!res.ok) throw new Error(`GET ${url} → HTTP ${res.status}`);
    const data = await res.json() as { source?: Record<string, string> };
    return data.source ?? null;
}

export async function writeBlocSource(target: string, source: Record<string, string>): Promise<void> {
    for (const [rel, base64] of Object.entries(source)) {
        const full = safeJoin(target, rel);
        await mkdir(dirname(full), { recursive: true });
        const bytes = rel === "manifest.json"
            ? Buffer.from(stripLegacyManifestFields(Buffer.from(base64, "base64").toString("utf-8")), "utf-8")
            : Buffer.from(base64, "base64");
        await writeFile(full, bytes);
    }
}

async function readGeneratedIntegrationBlocIds(siteDir: string): Promise<Set<string>> {
    const file = join(siteDir, GENERATED_INTEGRATION_INSTANCES_FILE);
    if (!existsSync(file)) return new Set();
    try {
        const parsed = JSON.parse(await readFile(file, "utf-8")) as unknown;
        if (!Array.isArray(parsed)) return new Set();
        return new Set(parsed.flatMap(instanceBlocArtifacts));
    } catch {
        return new Set();
    }
}

function instanceBlocArtifacts(value: unknown): string[] {
    const instance = value as Partial<IntegrationInstance> | null;
    if (!instance || !Array.isArray(instance.artifacts)) return [];
    return instance.artifacts
        .filter(artifact => artifact.type === "bloc")
        .map(artifact => artifact.id);
}

/**
 * Strip `default-group` from a server-stored manifest before writing it to
 * disk. Old bundles still carry it; the local scan rejects it on read, so
 * this lets a single `p9r pull` migrate every existing site cleanly.
 */
function stripLegacyManifestFields(raw: string): string {
    let manifest: Record<string, unknown>;
    try { manifest = JSON.parse(raw); }
    catch { return raw; }
    if (!manifest || typeof manifest !== "object" || Array.isArray(manifest)) return raw;
    if (!("default-group" in manifest)) return raw;
    delete manifest["default-group"];
    return JSON.stringify(manifest, null, 4) + "\n";
}
