import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { GENERATED_INTEGRATION_INSTALLATIONS_FILE } from "cms-cli/dev-server/integrations";
import type { IntegrationInstallation } from "@bernouy/cms-integrations";
import type { BlocOwnership } from "@bernouy/cms-content";
import { parseRemoteBlocOwnership } from "cms-cli/push/blocs/apply";
import { writeBlocSourceAtomically } from "cms-cli/push/blocs/atomicSource";
import { assertSafeBlocTag, writePulledBloc } from "cms-cli/push/blocs/pullLocation";

const HEADERS = (token: string) => ({ "Authorization": `Bearer ${token}` });

export type PullBlocsResult = {
    pulled: string[];
    skipped: { tag: string; reason: string }[];
    failed: { tag: string; error: string }[];
};

export type RemoteBlocSummary = { tag: string; group: string; ownership: BlocOwnership };

/**
 * Download every bloc that has a `source` bundle on the remote and write
 * its files under `<siteDir>/blocs/<group>/<tag>/`. Blocs uploaded before
 * the source-bundle feature have no bundle — we report them under
 * `skipped` so the user knows to push them once with the new CLI to make
 * them pull-able. The `default-group` field is stripped from
 * `manifest.json` on write, since the group is carried by the folder layout.
 */
export async function pullBlocs(adminBase: URL, token: string, siteDir: string): Promise<PullBlocsResult> {
    const out: PullBlocsResult = { pulled: [], skipped: [], failed: [] };
    const list = await fetchRemoteBlocList(adminBase, token);
    const generatedIntegrationBlocs = await readGeneratedIntegrationBlocIds(siteDir);

    for (const { tag, group, ownership } of list) {
        try {
            assertSafeBlocTag(tag);
        } catch (err) {
            out.failed.push({ tag, error: err instanceof Error ? err.message : String(err) });
            continue;
        }
        if (generatedIntegrationBlocs.has(tag)) {
            out.skipped.push({ tag, reason: "generated by an integration; use `p9r pull --type=integrations`" });
            continue;
        }
        try {
            const source = await fetchBlocSource(adminBase, token, tag);
            if (source === null) {
                out.skipped.push({ tag, reason: "no source bundle on the server" });
                continue;
            }
            await writePulledBloc(siteDir, group, tag, source, ownership);
            out.pulled.push(tag);
        } catch (err) {
            out.failed.push({ tag, error: err instanceof Error ? err.message : String(err) });
        }
    }
    return out;
}

export async function fetchRemoteBlocList(adminBase: URL, token: string): Promise<RemoteBlocSummary[]> {
    const url = new URL("api/bloc/list", adminBase).href;
    const res = await fetch(url, { headers: HEADERS(token) });
    if (!res.ok) {
        throw new Error(`GET ${url} → HTTP ${res.status}`);
    }
    const data = await res.json().catch(() => null);
    if (!Array.isArray(data)) {
        throw new Error(`GET ${url} did not return a JSON array`);
    }
    return data
        .filter((bloc): bloc is { id: string; group?: unknown; ownership?: unknown } => typeof bloc?.id === "string")
        .map((bloc) => ({
            tag: bloc.id,
            group: typeof bloc.group === "string" ? bloc.group : "",
            ownership: parseRemoteBlocOwnership(bloc.ownership, bloc.id),
        }));
}

export async function fetchBlocSource(
    adminBase: URL,
    token: string,
    tag: string,
): Promise<Record<string, string> | null> {
    const url = new URL(`api/bloc/source?tag=${encodeURIComponent(tag)}`, adminBase).href;
    const res = await fetch(url, { headers: HEADERS(token) });
    if (res.status === 404) {
        return null;
    }
    if (!res.ok) {
        throw new Error(`GET ${url} → HTTP ${res.status}`);
    }
    const data = (await res.json()) as { source?: Record<string, string> };
    return data.source ?? null;
}

export async function writeBlocSource(target: string, source: Record<string, string>): Promise<void> {
    await writeBlocSourceAtomically(target, source);
}

async function readGeneratedIntegrationBlocIds(siteDir: string): Promise<Set<string>> {
    const file = join(siteDir, GENERATED_INTEGRATION_INSTALLATIONS_FILE);
    if (!existsSync(file)) {
        return new Set();
    }
    try {
        const parsed = JSON.parse(await readFile(file, "utf-8")) as unknown;
        if (!Array.isArray(parsed)) {
            return new Set();
        }
        return new Set(parsed.flatMap(installationBlocArtifacts));
    } catch {
        return new Set();
    }
}

function installationBlocArtifacts(value: unknown): string[] {
    const installation = value as Partial<IntegrationInstallation> | null;
    if (!installation || !Array.isArray(installation.artifacts)) {
        return [];
    }
    return installation.artifacts.filter((artifact) => artifact.type === "bloc").map((artifact) => artifact.id);
}
