

create table if not exists commerce.order_payment_attempts (
    id bigint generated by default as identity primary key,
    order_id bigint not null references commerce.orders(id) on delete restrict,
    provider text not null default 'stripe',
    provider_payment_id bigint,
    provider_payment_intent_id text,
    provider_charge_id text,
    client_reference_id text not null,
    status text not null default 'created',
    amount bigint not null,
    currency text not null,
    financial_terms_hash text not null,
    failure_code text,
    provider_snapshot jsonb not null default '{}'::jsonb,
    succeeded_at timestamptz,
    failed_at timestamptz,
    cancelled_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint order_payment_attempts_provider check (provider = 'stripe'),
    constraint order_payment_attempts_provider_id check (
        provider_payment_id is null or provider_payment_id > 0
    ),
    constraint order_payment_attempts_intent_id check (
        provider_payment_intent_id is null or length(btrim(provider_payment_intent_id)) > 0
    ),
    constraint order_payment_attempts_charge_id check (
        provider_charge_id is null or length(btrim(provider_charge_id)) > 0
    ),
    constraint order_payment_attempts_reference check (length(btrim(client_reference_id)) > 0),
    constraint order_payment_attempts_status check (
        status in ('created', 'requires_action', 'processing', 'succeeded', 'failed', 'cancelled', 'manual_review')
    ),
    constraint order_payment_attempts_amount check (amount between 1 and 9007199254740991),
    constraint order_payment_attempts_currency check (currency = 'eur'),
    constraint order_payment_attempts_terms_hash check (financial_terms_hash ~ '^[a-f0-9]{64}$'),
    constraint order_payment_attempts_snapshot check (jsonb_typeof(provider_snapshot) = 'object'),
    constraint order_payment_attempts_provider_unique unique (provider, provider_payment_id),
    constraint order_payment_attempts_reference_unique unique (provider, client_reference_id)
);

create unique index if not exists order_payment_attempts_one_success_idx
    on commerce.order_payment_attempts(order_id) where status = 'succeeded';
create index if not exists order_payment_attempts_order_idx
    on commerce.order_payment_attempts(order_id, created_at desc);
create unique index if not exists order_payment_attempts_charge_unique_idx
    on commerce.order_payment_attempts(provider_charge_id) where provider_charge_id is not null;
create unique index if not exists order_payment_attempts_intent_unique_idx
    on commerce.order_payment_attempts(provider_payment_intent_id)
    where provider_payment_intent_id is not null;

alter table commerce.order_payment_attempts
    drop constraint if exists order_payment_attempts_terms_hash;
alter table commerce.order_payment_attempts
    add constraint order_payment_attempts_terms_hash check (financial_terms_hash ~ '^[a-f0-9]{64}$');