import type { DataShape } from "@bernouy/cms-sources";

export const stripeConnectStatusShape: DataShape = {
    type: "object",
    properties: {
        exists: { type: "boolean" },
        userId: { type: "string" },
        connected: { type: "boolean" },
        stripeAccountId: { type: "string", nullable: true },
        stripeAccountApiVersion: { type: "string" },
        onboardingStatus: { type: "string" },
        payoutsEnabled: { type: "boolean" },
        riskStatus: { type: "string" },
        applicationControlledRecipient: { type: "boolean" },
        canAcceptHeldPayments: { type: "boolean" },
        canReceiveProtectedPayments: { type: "boolean" },
        payoutBankReady: { type: "boolean" },
        accountStatus: { type: "string" },
        termsStatus: { type: "string" },
        stripeTermsStatus: { type: "string" },
        marketplaceTermsStatus: { type: "string" },
        marketplaceTermsCurrentVersionAccepted: { type: "boolean" },
        marketplaceTermsVersion: { type: "string" },
        marketplaceTermsHash: { type: "string" },
        marketplaceTermsAcceptedAt: { type: "string", nullable: true },
        enrollmentStatus: { type: "string" },
        stripeTransfersStatus: { type: "string" },
        bankAccountStatus: { type: "string" },
        bankPayoutsStatus: { type: "string" },
        detailsSubmitted: { type: "boolean" },
        chargesEnabled: { type: "boolean" },
        currentlyDue: { type: "array", items: { type: "string" } },
        eventuallyDue: { type: "array", items: { type: "string" } },
        pastDue: { type: "array", items: { type: "string" } },
        pendingVerification: { type: "array", items: { type: "string" } },
    },
    required: [
        "exists",
        "userId",
        "connected",
        "onboardingStatus",
        "payoutsEnabled",
        "applicationControlledRecipient",
        "canAcceptHeldPayments",
        "canReceiveProtectedPayments",
        "payoutBankReady",
        "accountStatus",
        "termsStatus",
        "stripeTermsStatus",
        "marketplaceTermsStatus",
        "marketplaceTermsCurrentVersionAccepted",
        "enrollmentStatus",
        "stripeTransfersStatus",
        "bankAccountStatus",
        "bankPayoutsStatus",
        "detailsSubmitted",
        "chargesEnabled",
        "currentlyDue",
        "eventuallyDue",
        "pastDue",
        "pendingVerification",
    ],
};
