

create table if not exists commerce.platform_payout_liability_controls (
    control_key text primary key default 'default',
    liability_revision bigint not null default 0,
    required_minimum_amount bigint not null default 0,
    previous_required_minimum_amount bigint not null default 0,
    change_direction text not null default 'unchanged',
    decrease_authorization_id uuid,
    decrease_authorized_by text,
    decrease_authorized_reason text,
    decrease_authorized_at timestamptz,
    last_provider_applied_revision bigint not null default 0,
    last_provider_applied_amount bigint not null default 0,
    last_provider_applied_at timestamptz,
    calculated_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint platform_payout_liability_controls_singleton check (control_key = 'default'),
    constraint platform_payout_liability_controls_amounts check (
        liability_revision between 0 and 9007199254740991
        and required_minimum_amount between 0 and 9007199254740991
        and previous_required_minimum_amount between 0 and 9007199254740991
        and last_provider_applied_revision between 0 and liability_revision
        and last_provider_applied_amount between 0 and 9007199254740991
    ),
    constraint platform_payout_liability_controls_direction check (
        change_direction in ('unchanged', 'increase', 'decrease')
    ),
    constraint platform_payout_liability_controls_decrease_authorization check (
        (change_direction <> 'decrease'
            and decrease_authorization_id is null
            and decrease_authorized_by is null
            and decrease_authorized_reason is null
            and decrease_authorized_at is null)
        or (change_direction = 'decrease' and (
            (decrease_authorization_id is null
                and decrease_authorized_by is null
                and decrease_authorized_reason is null
                and decrease_authorized_at is null)
            or (decrease_authorization_id is not null
                and length(btrim(decrease_authorized_by)) > 0
                and length(btrim(decrease_authorized_reason)) > 0
                and decrease_authorized_at is not null)
        ))
    )
);

insert into commerce.platform_payout_liability_controls (control_key)
values ('default')
on conflict (control_key) do nothing;

create table if not exists commerce.platform_payout_order_liabilities (
    order_id bigint primary key references commerce.orders(id) on delete restrict,
    lifecycle_status text not null default 'provisional',
    risk_release_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint platform_payout_order_liabilities_status check (
        lifecycle_status in ('provisional', 'active', 'released')
    ),
    constraint platform_payout_order_liabilities_risk_window check (
        (lifecycle_status = 'active' and risk_release_at is not null)
        or (lifecycle_status <> 'active' and risk_release_at is null)
    )
);

create index if not exists platform_payout_order_liabilities_window_idx
    on commerce.platform_payout_order_liabilities(lifecycle_status, risk_release_at);

create table if not exists commerce.platform_payout_order_contributions (
    order_id bigint primary key references commerce.platform_payout_order_liabilities(order_id)
        on delete cascade,
    seller_liability_amount bigint not null default 0,
    risk_reserve_liability_amount bigint not null default 0,
    next_reconciliation_at timestamptz,
    constraint platform_payout_order_contributions_amounts check (
        seller_liability_amount >= 0 and risk_reserve_liability_amount >= 0
    )
);

create index if not exists platform_payout_order_contributions_due_idx
    on commerce.platform_payout_order_contributions(next_reconciliation_at, order_id)
    where next_reconciliation_at is not null;

create table if not exists commerce.platform_payout_liability_pending_orders (
    event_id bigint generated by default as identity primary key,
    transaction_id xid8 not null,
    trigger_depth integer not null,
    source_table text not null,
    order_id bigint,
    requires_full_reconciliation boolean not null default false,
    constraint platform_payout_liability_pending_orders_target check (
        order_id is not null or requires_full_reconciliation
    )
);

create table if not exists commerce.platform_payout_liability_cache_state (
    control_key text primary key references commerce.platform_payout_liability_controls(control_key)
        on delete restrict,
    calculation_version integer not null,
    initialized boolean not null default false,
    initialized_at timestamptz,
    constraint platform_payout_liability_cache_state_singleton check (
        control_key = 'default'
    ),
    constraint platform_payout_liability_cache_state_version check (
        calculation_version > 0
    )
);

insert into commerce.platform_payout_liability_cache_state (
    control_key, calculation_version, initialized
) values ('default', 1, false)
on conflict (control_key) do nothing;

create table if not exists commerce.platform_payout_liability_revisions (
    liability_revision bigint primary key,
    required_minimum_amount bigint not null,
    previous_required_minimum_amount bigint not null,
    change_direction text not null,
    calculation_reason text not null,
    included_prospective_order_id bigint references commerce.orders(id) on delete restrict,
    decrease_authorization_id uuid unique,
    decrease_authorized_by text,
    decrease_authorized_reason text,
    decrease_authorized_at timestamptz,
    provider_applied_amount bigint,
    provider_applied_at timestamptz,
    created_at timestamptz not null default now(),
    constraint platform_payout_liability_revisions_amounts check (
        required_minimum_amount between 0 and 9007199254740991
        and previous_required_minimum_amount between 0 and 9007199254740991
        and (provider_applied_amount is null or provider_applied_amount between 0 and 9007199254740991)
    ),
    constraint platform_payout_liability_revisions_direction check (
        change_direction in ('unchanged', 'increase', 'decrease')
    )
);