import { z } from "zod";
import { defineTenantConfig } from "@bernouy/tenant-provisioner-sdk";

/**
 * Per-tenant config the **hub** sets when provisioning a CMS instance
 * (base.md §11). Intentionally minimal: only the bootstrap admin for the
 * tenant's **admin space**. Authentication is **CMS-owned** — a builtin local
 * provider seeded at provision + per-tenant dynamic OIDC providers stored as
 * data, both managed in the CMS admin afterwards. Only the session-signing
 * key is platform-level (configured once on the TP runtime via env), not
 * here. Everything else (site name, host, language, theme, media bucket, …)
 * is configured inside the CMS admin itself — the hub neither sees nor
 * manages it.
 *
 * All fields are control-plane-writable — operator concern, not tenant
 * self-service (the `/tenant/config` PATCH path does NOT notify our hooks).
 */
const CmsConfigShape = z.object({
    initialAdminEmail:    z.string().email(),           // bootstrap admin — authZ lives in the CMS
    initialAdminPassword: z.string().min(12).optional(), // bootstrap password for the builtin local admin; generated by the TP (18-byte base64-url) when omitted. Min 12 chars rejects trivial values — operator rotates from the admin UI afterwards.
});

export const CMS_TENANT_CONFIG = defineTenantConfig({
    version: "3.1",
    zod:     CmsConfigShape,
    title:   "CMS tenant config",
    defaultWritableBy: ["control-plane"],
    annotations: {
        initialAdminEmail:    { title: "Initial admin email", widget: "text", group: "Admin auth" },
        initialAdminPassword: { title: "Initial admin password (optional — generated if blank)", widget: "text", group: "Admin auth" },
    },
});

export type CmsTenantConfig = z.infer<typeof CmsConfigShape>;
