import {
    identifyObservedSchemaContract,
    sameObservedSchemaContract,
    type ObservedSchemaContractV1,
} from "@bernouy/cms-integrations";
import { readSupabaseObservedSchemaContract } from "@bernouy/cms-integrations/supabase";
import { DisposableSchemaCalibrationCluster, type SchemaCalibrationDatabase } from "../database";
import type { schemaCalibrationEnvironmentIdentity } from "../environment/manifest";
import { schemaCatalogClient } from "./catalogClient";
import type { SchemaCalibrationDialectReport } from "./report";

const DIALECT_SQL = `
create schema calibration;
create sequence calibration.manual_sequence;
create table calibration.identity_forms (
    always_id bigint generated always as identity,
    default_id bigint generated by default as identity,
    serial_id bigserial,
    ordinary_nextval bigint not null default nextval('calibration.manual_sequence'::regclass),
    quantity integer not null,
    constraint identity_forms_pkey primary key (always_id),
    constraint identity_forms_quantity_check check ((quantity >= 0))
);
`;

export async function calibratePostgresDialect(
    cluster: DisposableSchemaCalibrationCluster,
    environment: Awaited<ReturnType<typeof schemaCalibrationEnvironmentIdentity>>,
): Promise<SchemaCalibrationDialectReport> {
    const databaseA = await cluster.create("cmscore_contracts_dialect_a", environment);
    const databaseB = await cluster.create("cmscore_contracts_dialect_b", environment);
    try {
        const contractA = await installAndObserve(databaseA);
        const contractB = await installAndObserve(databaseB);
        if (!sameObservedSchemaContract(contractA, contractB)) {
            throw new Error("Pinned PostgreSQL dialect fixture is not deterministic across fresh databases");
        }
        const relation = contractA.namespaces[0]?.relations[0];
        if (!relation) {
            throw new Error("Pinned PostgreSQL dialect fixture relation was not observed");
        }
        const identities = Object.fromEntries(
            relation.columns.map((column) => [
                column.name,
                {
                    identity: column.identity,
                    sequenceDependency: column.sequenceDependency,
                    ...(column.default !== undefined ? { default: column.default } : {}),
                },
            ]),
        );
        assertDialectIdentity(identities, "always_id", "always", "internal");
        assertDialectIdentity(identities, "default_id", "by-default", "internal");
        assertDialectIdentity(identities, "serial_id", "none", "auto");
        assertDialectIdentity(identities, "ordinary_nextval", "none", "none");
        const check = relation.constraints.find((constraint) => constraint.name === "identity_forms_quantity_check");
        if (!check || check.kind !== "check") {
            throw new Error("Pinned PostgreSQL CHECK fixture was not observed");
        }
        return {
            contractDigest: (await identifyObservedSchemaContract(contractA)).digest,
            freshDeterministic: true,
            identities,
            checkExpression: check.expression,
        };
    } finally {
        await cluster.drop(databaseB);
        await cluster.drop(databaseA);
    }
}

async function installAndObserve(database: SchemaCalibrationDatabase): Promise<ObservedSchemaContractV1> {
    await database.sql.unsafe(DIALECT_SQL);
    return readSupabaseObservedSchemaContract({
        client: schemaCatalogClient(database.sql),
        owner: { connectorKey: "dialect", lineageId: "postgres-16-calibration-v1" },
        ownedNamespaces: ["calibration"],
    });
}

function assertDialectIdentity(
    identities: SchemaCalibrationDialectReport["identities"],
    name: string,
    identity: "none" | "always" | "by-default",
    sequenceDependency: "none" | "auto" | "internal",
): void {
    const actual = identities[name];
    if (!actual || actual.identity !== identity || actual.sequenceDependency !== sequenceDependency) {
        throw new Error(`Pinned PostgreSQL identity semantics changed for ${name}`);
    }
}
