export const orderCopy: Record<string, string> = {
    "loading-label": "Loading order",
    "order-eyebrow": "ORDER",
    "progress-label": "Delivery progress",
    "progress-confirmed-label": "Confirmed",
    "progress-prepared-label": "Prepared",
    "progress-shipped-label": "Shipped",
    "progress-pickup-label": "At pickup point",
    "item-heading": "Ordered item",
    "summary-heading": "Summary",
    "item-label": "Item",
    "delivery-label": "Delivery",
    "protection-label": "Buyer protection",
    "total-label": "Total",
    "relay-heading": "Selected pickup point",
    "order-reference-label": "Order {reference}",
    "order-date-label": "Placed on {date}",
    "condition-label": "Condition: {condition}",
    "tracking-number-label": "Parcel number {number}",
    "delivery-completed-label": "Delivery completed",
    "amount-pending-label": "To calculate",
    "relay-pending-label": "Pickup point to be confirmed",
    "relay-address-unavailable-label": "Pickup-point address unavailable",
    "relay-selected-label": "Pickup point selected for the order",
    "relay-mismatch-label": "The parcel destination does not match the selected pickup point",
    "relay-confirmed-label": "Destination recorded for the shipment",
    "relay-confirmation-pending-label": "Pickup-point confirmation pending",
    "state-payment-not-started": "Payment not started",
    "state-payment-pending": "Payment pending",
    "state-payment-to-complete": "Payment to complete",
    "state-payment-confirmation-in-progress": "Payment confirmation in progress",
    "state-payment-confirmed": "Payment confirmed",
    "state-payment-failed": "Payment failed",
    "state-payment-cancelled": "Payment cancelled",
    "state-payment-under-review": "Payment under review",
    "state-payment-refunded": "Payment refunded",
    "state-payment-partially-refunded": "Payment partially refunded",
    "state-payment-disputed": "Payment disputed",
    "state-payment-status-unavailable": "Payment status unavailable",
    "state-cancelled": "Cancelled",
    "state-cancellation-in-progress": "Cancellation in progress",
    "state-expired": "Expired",
    "state-completed": "Completed",
    "state-delivery-to-complete": "Delivery to complete",
    "state-payment-in-progress": "Payment in progress",
    "state-status-unavailable": "Status unavailable",
    "state-delivered": "Delivered",
    "state-in-delivery": "In delivery",
    "state-delivery-incident": "Delivery incident",
    "state-shipment-to-complete": "Shipment to complete",
    "state-tracking-to-be-confirmed": "Tracking to be confirmed",
    "state-order-confirmed": "Order confirmed",
    "state-order-under-review": "Order under review",
    "shipment-payment-pending-description": "Preparation will begin once payment is confirmed.",
    "shipment-payment-review-description": "Preparation is paused while payment is reviewed.",
    "shipment-payment-cancelled-description": "This order cannot be prepared.",
    "state-order-refunded": "Order refunded",
    "shipment-refunded-description": "No new shipment will be prepared for this order.",
    "shipment-unavailable-title": "Tracking unavailable",
    "shipment-unavailable-description": "Payment status does not yet allow delivery details to be shown.",
    "state-waiting-for-payment": "Waiting for payment",
    "state-parcel-delivered": "Parcel delivered",
    "shipment-delivered-description": "Your parcel was delivered to the selected pickup point.",
    "state-parcel-in-transit": "Parcel in transit",
    "shipment-in-transit-description": "Your parcel is being handled by the carrier.",
    "state-delivery-incident-reported": "Delivery incident reported",
    "shipment-incident-description": "The latest known event is shown below.",
    "shipment-failed-description": "The parcel is not yet confirmed as shipped.",
    "state-shipment-status-to-be-confirmed": "Shipment status to be confirmed",
    "shipment-unknown-description": "Waiting for carrier confirmation.",
    "state-shipment-cancelled": "Shipment cancelled",
    "shipment-cancelled-description": "The parcel is not in transit.",
    "state-shipment-being-prepared": "Shipment being prepared",
    "shipment-created-description": "The parcel will be handed to the carrier.",
    "state-order-being-prepared": "Order being prepared",
    "shipment-preparing-description": "Tracking will appear here once the shipment is created.",
    "condition-very-good-label": "Very good",
    "condition-good-label": "Good",
    "condition-poor-label": "Poor",
};

export function readOrderCopy(host: HTMLElement, name: string, values: Record<string, string> = {}): string {
    const content = host.getAttribute(name)?.trim() || orderCopy[name] || "";
    return Object.entries(values).reduce((result, [key, value]) => result.replaceAll(`{${key}}`, value), content);
}
