import { expect, test } from "bun:test";
import { SQL } from "bun";
import { createDisposableVerificationDatabaseProviderFromEnv } from "../../../src/runtime/providers/postgres";
import { POSTGRES_DEDICATED_CLUSTER_CONTRACT } from "../../../src/runtime/providers/postgres/fingerprint";
import { DIGEST_A, DIGEST_B } from "../../fixtures/contracts";
import { disposablePostgresAvailable, startDisposablePostgres } from "../postgresFixture";

const postgresTest = disposablePostgresAvailable ? test : test.skip;

postgresTest(
    "provisions a least-privilege disposable database and destroys it idempotently",
    async () => {
        const fixture = await startDisposablePostgres();
        try {
            await provisionDedicatedCluster(fixture);
            const provider = await createDisposableVerificationDatabaseProviderFromEnv({
                CMS_INTEGRATION_VERIFIER_POSTGRES_HOST: fixture.host,
                CMS_INTEGRATION_VERIFIER_POSTGRES_PORT: String(fixture.port),
                CMS_INTEGRATION_VERIFIER_POSTGRES_USER: "postgres",
                CMS_INTEGRATION_VERIFIER_POSTGRES_DATABASE: "postgres",
                CMS_INTEGRATION_VERIFIER_POSTGRES_PASSWORD_FILE: fixture.passwordFile,
            });
            const lease = await provider.acquire(
                { candidateId: "candidate-1", packageDigest: DIGEST_A, verificationDigest: DIGEST_B },
                new AbortController().signal,
            );
            const database = new SQL(lease.credential.connectionUri, { max: 1 });
            try {
                const rows = (await database.unsafe(
                    "select current_database()::text as database, current_user::text as role",
                )) as Array<{ database: string; role: string }>;
                expect(rows[0]?.database).toBe(lease.credential.databaseId);
                expect(rows[0]?.role).toStartWith("cmsv_");
                const roles = (await database.unsafe(`select
                    rolsuper,
                    rolcreatedb,
                    rolcreaterole,
                    rolinherit,
                    rolreplication,
                    rolbypassrls,
                    rolconnlimit,
                    current_user = pg_get_userbyid((select datdba from pg_catalog.pg_database where datname = current_database())) as owns_database,
                    pg_has_role(current_user, 'pg_read_server_files', 'member') as read_server_files,
                    pg_has_role(current_user, 'pg_write_server_files', 'member') as write_server_files,
                    pg_has_role(current_user, 'pg_execute_server_program', 'member') as execute_server_program
                from pg_catalog.pg_roles
                where rolname = current_user`)) as Array<Record<string, boolean | number>>;
                expect(roles[0]).toEqual({
                    rolsuper: false,
                    rolcreatedb: false,
                    rolcreaterole: false,
                    rolinherit: false,
                    rolreplication: false,
                    rolbypassrls: false,
                    rolconnlimit: 4,
                    owns_database: false,
                    read_server_files: false,
                    write_server_files: false,
                    execute_server_program: false,
                });
                await database.unsafe("create schema provider_probe");
                await database.unsafe(
                    "create table provider_probe.values (id bigint generated by default as identity primary key)",
                );
                expect(
                    fixture.executeAs(lease.credential.connectionUri, "copy (select 1) to program 'true'").exitCode,
                ).toBeGreaterThan(0);
                expect(
                    fixture.executeAs(lease.credential.connectionUri, "select pg_catalog.pg_read_file('/etc/passwd')")
                        .exitCode,
                ).toBeGreaterThan(0);
                expect(fixture.executeAs(lease.credential.connectionUri, "set role anon").exitCode).toBeGreaterThan(0);
                const extension = fixture.executeAs(lease.credential.connectionUri, "create extension hstore");
                expect(extension.exitCode).toBeGreaterThan(0);
                expect(extension.stderr).toContain("not allowlisted");
                const administrativeTarget = new URL(lease.credential.connectionUri);
                administrativeTarget.pathname = "/postgres";
                expect(fixture.executeAs(administrativeTarget.toString(), "select 1").exitCode).toBeGreaterThan(0);
            } finally {
                await database.close();
            }
            await lease.release();
            await lease.release();
        } finally {
            await fixture.close();
        }
    },
    30_000,
);

postgresTest(
    "preserves another provider's active lease and recovers it only after expiry",
    async () => {
        const fixture = await startDisposablePostgres();
        try {
            await provisionDedicatedCluster(fixture);
            const source = {
                CMS_INTEGRATION_VERIFIER_POSTGRES_HOST: fixture.host,
                CMS_INTEGRATION_VERIFIER_POSTGRES_PORT: String(fixture.port),
                CMS_INTEGRATION_VERIFIER_POSTGRES_USER: "postgres",
                CMS_INTEGRATION_VERIFIER_POSTGRES_DATABASE: "postgres",
                CMS_INTEGRATION_VERIFIER_POSTGRES_PASSWORD_FILE: fixture.passwordFile,
            };
            const first = await createDisposableVerificationDatabaseProviderFromEnv(source);
            const orphan = await first.acquire(
                { candidateId: "candidate-1", packageDigest: DIGEST_A, verificationDigest: DIGEST_B },
                new AbortController().signal,
            );
            const role = decodeURIComponent(new URL(orphan.credential.connectionUri).username);

            const admin = new SQL(
                `postgresql://postgres:${fixture.password}@${fixture.host}:${fixture.port}/postgres?sslmode=disable`,
                { max: 1 },
            );
            try {
                await createDisposableVerificationDatabaseProviderFromEnv(source);
                expect(await databaseCount(admin, orphan.credential.databaseId)).toBe(1);
                const stillActive = new SQL(orphan.credential.connectionUri, { max: 1 });
                try {
                    expect((await stillActive.unsafe("select 1 as value"))[0]?.value).toBe(1);
                } finally {
                    await stillActive.close();
                }
                await admin.unsafe(
                    `update cms_verifier_provider.owned_leases
                      set lease_expires_at = clock_timestamp() - interval '1 second'
                      where database_name = $1`,
                    [orphan.credential.databaseId],
                );
                await createDisposableVerificationDatabaseProviderFromEnv(source);
                const remaining = (await admin.unsafe(
                    "select (select count(*)::int from pg_catalog.pg_database where datname = $1) as databases, (select count(*)::int from pg_catalog.pg_roles where rolname = $2) as roles",
                    [orphan.credential.databaseId, role],
                )) as Array<{ databases: number; roles: number }>;
                expect(remaining[0]).toEqual({ databases: 0, roles: 0 });
            } finally {
                await admin.close();
            }
            await orphan.release();
        } finally {
            await fixture.close();
        }
    },
    30_000,
);

async function provisionDedicatedCluster(fixture: Awaited<ReturnType<typeof startDisposablePostgres>>): Promise<void> {
    const admin = new SQL(
        `postgresql://postgres:${fixture.password}@${fixture.host}:${fixture.port}/postgres?sslmode=disable`,
        { max: 1 },
    );
    try {
        await admin.unsafe(`comment on database postgres is '${POSTGRES_DEDICATED_CLUSTER_CONTRACT}'`);
    } finally {
        await admin.close();
    }
}

async function databaseCount(admin: SQL, database: string): Promise<number> {
    const rows = (await admin.unsafe("select count(*)::int as count from pg_catalog.pg_database where datname = $1", [
        database,
    ])) as Array<{ count: number }>;
    return rows[0]?.count ?? -1;
}
