

create table if not exists commerce.seller_risk_policies (
    id bigint generated by default as identity primary key,
    policy_key text not null,
    version integer not null,
    name text not null,
    status text not null default 'draft',
    currency text not null default 'eur',
    reserve_rate_bps integer not null default 0,
    payout_delay_days integer not null default 7,
    reserve_liability_days integer not null default 120,
    order_transfer_limit_amount bigint not null default 500000,
    velocity_limit_amount bigint not null default 1000000,
    high_value_review_amount bigint not null default 50000,
    claim_ratio_review_bps integer not null default 1000,
    chargeback_ratio_review_bps integer not null default 200,
    published_at timestamptz,
    created_by text not null,
    created_at timestamptz not null default now(),
    constraint seller_risk_policies_key_format check (policy_key ~ '^[a-z][a-z0-9_-]{0,63}$'),
    constraint seller_risk_policies_version_positive check (version > 0),
    constraint seller_risk_policies_name_not_blank check (length(btrim(name)) > 0),
    constraint seller_risk_policies_status check (status in ('draft', 'published', 'retired')),
    constraint seller_risk_policies_currency check (currency = 'eur'),
    constraint seller_risk_policies_rates check (
        reserve_rate_bps between 0 and 9999
        and claim_ratio_review_bps between 0 and 10000
        and chargeback_ratio_review_bps between 0 and 10000
    ),
    constraint seller_risk_policies_delay check (
        payout_delay_days between 0 and 31 and reserve_liability_days between 1 and 180
    ),
    constraint seller_risk_policies_amounts check (
        order_transfer_limit_amount between 1 and 9007199254740991
        and velocity_limit_amount between order_transfer_limit_amount and 9007199254740991
        and high_value_review_amount between 0 and 9007199254740991
    ),
    constraint seller_risk_policies_publication check (
        (status = 'draft' and published_at is null) or (status <> 'draft' and published_at is not null)
    ),
    constraint seller_risk_policies_key_version_unique unique (policy_key, version)
);

insert into commerce.fee_policies (
    policy_key, version, name, status, currency, shipping_beneficiary,
    cost_estimates_configured, subsidy_override, subsidy_reason, published_at, created_by
) values (
    'c2c-default', 1, 'Protected C2C configuration required', 'draft', 'eur', 'platform',
    false, false, null, null, 'system'
) on conflict (policy_key, version) do nothing;

insert into commerce.fee_policy_components (
    fee_policy_id, component_key, payer, basis, rate_bps, fixed_amount, refund_policy, position
)
select id, 'buyer_protection', 'buyer', 'merchandise', 0, 0, 'resolution_defined', 10
from commerce.fee_policies where policy_key = 'c2c-default' and version = 1
on conflict (fee_policy_id, component_key) do nothing;

insert into commerce.fee_policies (
    policy_key, version, name, status, currency, shipping_beneficiary,
    cost_estimates_configured, subsidy_override, subsidy_reason, published_at, created_by
) values (
    'c2c-default', 2, 'Protected C2C configuration required', 'draft', 'eur', 'platform',
    false, false, null, null, 'system'
) on conflict (policy_key, version) do nothing;

insert into commerce.fee_policy_components (
    fee_policy_id, component_key, payer, basis, rate_bps, fixed_amount, refund_policy, position
)
select id, 'buyer_protection', 'buyer', 'merchandise', 0, 0, 'resolution_defined', 10
from commerce.fee_policies where policy_key = 'c2c-default' and version = 2
on conflict (fee_policy_id, component_key) do nothing;

insert into commerce.fee_policy_components (
    fee_policy_id, component_key, payer, basis, rate_bps, fixed_amount, refund_policy, position
)
select id, 'seller_commission', 'seller', 'merchandise', 0, 0, 'never', 20
from commerce.fee_policies where policy_key = 'c2c-default' and version = 2
on conflict (fee_policy_id, component_key) do nothing;

insert into commerce.fee_policy_components (
    fee_policy_id, component_key, payer, basis, rate_bps, fixed_amount, refund_policy, position
)
select id, 'seller_commission', 'seller', 'merchandise', 0, 0, 'never', 20
from commerce.fee_policies where policy_key = 'c2c-default' and version = 1
on conflict (fee_policy_id, component_key) do nothing;

insert into commerce.protection_policies (
    policy_key, version, name, status, currency, published_at, created_by
) values (
    'c2c-default', 1, 'Protected C2C default', 'published', 'eur', now(), 'system'
) on conflict (policy_key, version) do nothing;

insert into commerce.seller_risk_policies (
    policy_key, version, name, status, currency, reserve_rate_bps,
    payout_delay_days, reserve_liability_days, published_at, created_by
) values (
    'c2c-default', 1, 'Protected C2C default', 'published', 'eur', 1000,
    14, 120, now(), 'system'
) on conflict (policy_key, version) do nothing;

alter table commerce.seller_risk_policies
    add column if not exists reserve_liability_days integer not null default 120;
alter table commerce.seller_risk_policies
    drop constraint if exists seller_risk_policies_delay;
alter table commerce.seller_risk_policies
    add constraint seller_risk_policies_delay check (
        payout_delay_days between 0 and 31 and reserve_liability_days between 1 and 180
    );

insert into commerce.seller_risk_policies (
    policy_key, version, name, status, currency, reserve_rate_bps,
    payout_delay_days, reserve_liability_days, published_at, created_by
) values (
    'c2c-default', 2, 'Protected C2C prudent default', 'published', 'eur', 1000,
    14, 120, now(), 'system'
) on conflict (policy_key, version) do nothing;