const offer = {
    id: 91,
    sellerId: 7,
    productId: 42,
    variantId: 51,
    slug: "camera-offer",
    title: "Camera offer",
    description: null,
    conditionCode: "good",
    publicationStatus: "draft",
    workflowState: "pending_review",
    acceptedPriceAmount: 12500,
    currency: "eur",
    availability: "available",
    quantityAvailable: null,
    metadata: { privateSellerNote: "owner-visible", internal_note: "keep-snake-case" },
    version: 4,
    createdAt: "2026-07-01T10:00:00Z",
    updatedAt: "2026-07-04T10:00:00Z",
};
const seller = {
    id: 7,
    kind: "user",
    slug: "seller-seven",
    displayName: "Seller Seven",
    verificationStatus: "verified",
};
const product = {
    id: 42,
    slug: "camera",
    title: "Camera",
    brandId: 77,
    status: "active",
    visibility: "public",
    metadata: { publicSpec: "24MP", privateCost: 9000 },
    brand: { id: 77, slug: "canon", name: "Canon", status: "active" },
    primaryCategoryId: 88,
    primaryCategory: {
        id: 88,
        parentId: null,
        slug: "cameras",
        fullSlug: "cameras",
        label: "Cameras",
        status: "active",
        position: 10,
    },
};
const variant = { id: 51, sku: null, title: "Body only", status: "active" };
const media = [
    {
        id: 501,
        mediaId: 201,
        sortOrder: 1,
        isMain: false,
        media: {
            id: 201,
            storageBucket: "commerce-media",
            storagePath: "offers/91/side.jpg",
            mimeType: "image/jpeg",
            fileSize: 1200,
            originalFilename: "side.jpg",
            alt: null,
            createdAt: "2026-07-01T11:00:00Z",
            updatedAt: "2026-07-01T11:00:00Z",
            url: "",
        },
    },
    {
        id: 502,
        mediaId: 202,
        sortOrder: 2,
        isMain: true,
        media: {
            id: 202,
            storageBucket: "commerce-media",
            storagePath: "offers/91/front.jpg",
            mimeType: "image/jpeg",
            fileSize: 1400,
            originalFilename: "front.jpg",
            alt: "Front",
            createdAt: "2026-07-01T12:00:00Z",
            updatedAt: "2026-07-02T12:00:00Z",
            url: "",
        },
    },
];
const sellerRule = {
    offerId: 91,
    minimumAmount: 11000,
    maximumAmount: 15000,
    currency: "eur",
    version: 3,
    createdAt: "2026-07-02T10:00:00Z",
    updatedAt: "2026-07-03T10:00:00Z",
};
const sellerProposals = [
    {
        id: 302,
        offerId: 91,
        amount: 12500,
        currency: "eur",
        status: "pending",
        decisionReason: null,
        decidedAt: null,
        createdAt: "2026-07-04T09:00:00Z",
    },
    {
        id: 301,
        offerId: 91,
        amount: 12000,
        currency: "eur",
        status: "rejected",
        decisionReason: "too low",
        decidedAt: "2026-07-03T09:30:00Z",
        createdAt: "2026-07-03T09:00:00Z",
    },
];

export const sellerOfferDetail = {
    ...offer,
    seller,
    product: { ...product, metadata: { publicSpec: "24MP" } },
    variant,
    priceRule: sellerRule,
    priceProposals: sellerProposals,
    media,
    mainImageMediaId: "202",
};

export const adminOfferDetail = {
    ...offer,
    seller,
    product,
    variant,
    priceRule: { ...sellerRule, configuredBy: "admin-1" },
    priceProposals: [
        { ...sellerProposals[0], proposedBy: "seller", decidedBy: null },
        { ...sellerProposals[1], proposedBy: "admin", decidedBy: "seller-user-123" },
    ],
    media,
    mainImageMediaId: "202",
};

export const newOfferTemplate = {
    id: null,
    productId: null,
    variantId: null,
    slug: "",
    title: "",
    description: "",
    conditionCode: "good",
    publicationStatus: "draft",
    workflowState: "draft",
    acceptedPriceAmount: null,
    currency: "eur",
    availability: "available",
    quantityAvailable: null,
    metadata: {},
    media: [],
    mainImageMediaId: null,
    version: 1,
};

export const nullOfferDetail = {
    ...offer,
    variantId: null,
    seller: null,
    product: null,
    variant: null,
    priceRule: null,
    priceProposals: [],
    media: [],
    mainImageMediaId: null,
};
