import { financialTermsHash, type JsonRecord } from "../harness";

export function expectedProtectedPayment(actual: JsonRecord, patch: JsonRecord = {}): JsonRecord {
    return {
        paymentId: 1,
        providerPaymentId: 1,
        clientReferenceId: "provider-order-1",
        financialTermsHash,
        financialRevision: 1,
        dualApprovalThresholdAmount: 1000,
        buyerUserId: "buyer-1",
        sellerUserId: "seller-1",
        stripePaymentIntentId: "pi_1",
        stripeChargeId: null,
        providerEventId: null,
        transferGroup: "cms_order_5a66e34d5f14d1ea34206f0ee2e0c236b961ff46e95cbb568d051704dae96881",
        currency: "eur",
        amountTotal: 1200,
        sellerTransferAmount: 1080,
        platformRetainedAmount: 120,
        refundedAmount: 0,
        transferredAmount: 0,
        reversedAmount: 0,
        stripeChargeBalanceTransactionId: null,
        actualStripeChargeFeeAmount: 0,
        actualStripeRefundFeeAmount: 0,
        actualStripeProcessingFeeAmount: 0,
        actualStripeChargeNetAmount: null,
        actualStripeFeeCurrency: null,
        actualStripeChargeFeeDetails: [],
        actualPlatformMarginAfterStripeAmount: 120,
        paymentStatus: "created",
        commercePaymentStatus: "created",
        settlementStatus: "held",
        disputeStatus: "none",
        manualReviewReason: null,
        paidAt: null,
        cancelledAt: null,
        lastProviderSyncAt: actual.lastProviderSyncAt,
        occurredAt: "2026-07-06T12:10:00.000Z",
        createdAt: "2026-07-06T12:05:00.000Z",
        updatedAt: "2026-07-06T12:10:00.000Z",
        clientSecret: "pi_1_secret",
        ...patch,
    };
}
