import type { Edge } from "../../interfaces/entities/Edge";

export type LsyncdConfigInput = {
    /** Local source path watched by lsyncd. Typically `/var/lib/cdn/`
     *  (the volume root) so a single sync block covers buckets +
     *  `nginx-generated/` + `lego/certificates/` in one go. */
    sourcePath: string;
    /** Path to the SSH private key used for rsync targets. */
    sshKeyPath: string;
    /** Where lsyncd writes its status / log files. */
    statusFile: string;
    logFile:    string;
    edges:      ReadonlyArray<Edge>;
};

/**
 * Top-level paths under `/var/lib/cdn/` that must NEVER leave the origin:
 * - `ssh/`           — origin's private key.
 * - `lsyncd/`        — lsyncd's own status + log files.
 * - `backups/`       — local backup output (huge, redundant for edges).
 * - `lego/webroot/`  — ACME-01 challenge dir is per-issuance + ephemeral;
 *                      edges proxy back here, they don't need a copy.
 * - `lego/accounts/` — lego account state is origin-owned by design.
 *
 * The remaining `buckets/`, `lego/certificates/`, `nginx-generated/`
 * are exactly what an edge needs to serve.
 */
const RSYNC_EXCLUDES: ReadonlyArray<string> = [
    "ssh/",
    "lsyncd/",
    "backups/",
    "lego/webroot/",
    "lego/accounts/",
];

/**
 * Render a self-contained lsyncd Lua config that watches `sourcePath` and
 * pushes every change to each edge via `rsync -e ssh`. Notes:
 *
 * - `--delete` is enabled so a delete on the origin removes the file on
 *   every edge (the origin is the source of truth).
 * - `init = true`: on lsyncd startup it does a full rsync against every
 *   target, which doubles as the bootstrap pass for newly-added edges.
 * - `delay = 5` lets a burst of writes (e.g. a delivery cycle uploading
 *   dozens of files) be coalesced into a single rsync invocation.
 * - `StrictHostKeyChecking=accept-new` accepts the host key on first
 *   connection then pins it, so a man-in-the-middle requires a key change
 *   that lsyncd will refuse on the next run.
 * - `RSYNC_EXCLUDES` keeps origin-private state out of edges (cf. above).
 */
export function generateLsyncdConfig(input: LsyncdConfigInput): string {
    const { sourcePath, sshKeyPath, statusFile, logFile, edges } = input;

    const header = [
        "-- Generated by @bernouy/cdn-origin. DO NOT EDIT BY HAND.",
        "-- Origin pushes the buckets root to every edge via rsync over SSH.",
        "",
        "settings {",
        `    logfile    = "${escapeLua(logFile)}",`,
        `    statusFile = "${escapeLua(statusFile)}",`,
        "    nodaemon   = true,",
        "    insist     = true,",
        "}",
        "",
    ].join("\n");

    const targets = edges.map((e) => renderEdgeTarget(e, sourcePath, sshKeyPath)).join("\n\n");

    return header + targets + "\n";
}

function renderEdgeTarget(edge: Edge, sourcePath: string, sshKeyPath: string): string {
    const rsh = [
        "ssh",
        `-i ${sshKeyPath}`,
        `-p ${edge.sshPort}`,
        "-o StrictHostKeyChecking=accept-new",
        "-o BatchMode=yes",
        "-o ServerAliveInterval=30",
        "-o ConnectTimeout=10",
    ].join(" ");

    const target = `${edge.sshUser}@${edge.hostname}:${edge.dataPath}/`;

    const excludes = RSYNC_EXCLUDES
        .map((p) => `"${escapeLua(p)}"`)
        .join(", ");

    return [
        `-- edge: ${edge.id} (${edge.label})`,
        "sync {",
        "    default.rsync,",
        `    source = "${escapeLua(sourcePath)}/",`,
        `    target = "${escapeLua(target)}",`,
        "    delay  = 5,",
        "    init   = true,",
        "    rsync  = {",
        '        binary   = "/usr/bin/rsync",',
        "        archive  = true,",
        "        compress = true,",
        "        verbose  = false,",
        "        _extra   = { \"--delete\" },",
        `        exclude  = { ${excludes} },`,
        `        rsh      = "${escapeLua(rsh)}",`,
        "    },",
        "}",
    ].join("\n");
}

function escapeLua(s: string): string {
    return s.replace(/\\/g, "\\\\").replace(/"/g, "\\\"");
}
