

create table if not exists commerce.media (
    id bigint generated by default as identity primary key,
    storage_bucket text not null,
    storage_path text not null,
    mime_type text not null,
    file_size bigint not null,
    original_filename text not null,
    alt text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint media_storage_path_unique unique (storage_bucket, storage_path),
    constraint media_file_size_valid check (file_size between 1 and 10485760),
    constraint media_mime_type_valid check (
        mime_type in ('image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/avif')
    ),
    constraint media_original_filename_not_blank check (length(btrim(original_filename)) > 0),
    constraint media_alt_length check (alt is null or length(alt) <= 500)
);

create table if not exists commerce.product_media (
    id bigint generated by default as identity primary key,
    product_id bigint not null references commerce.products(id) on delete restrict,
    media_id bigint not null references commerce.media(id) on delete restrict,
    sort_order integer not null default 0,
    is_main boolean not null default false,
    created_at timestamptz not null default now(),
    constraint product_media_product_media_unique unique (product_id, media_id)
);

create unique index if not exists product_media_main_unique
    on commerce.product_media(product_id) where is_main;

do $commerce_storage_bucket$
begin
    if to_regclass('storage.buckets') is not null then
        execute $sql$
            insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
            values (
                'commerce-media', 'commerce-media', false, 10485760,
                array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/avif']::text[]
            )
            on conflict (id) do update set
                public = false,
                file_size_limit = excluded.file_size_limit,
                allowed_mime_types = excluded.allowed_mime_types
        $sql$;
    end if;
end;
$commerce_storage_bucket$;