create table if not exists commerce.marketplace_service_withdrawal_requests (
    id bigint generated by default as identity primary key,
    public_id uuid not null default gen_random_uuid() unique,
    order_id bigint not null references commerce.orders(id) on delete restrict,
    buyer_cms_user_id text not null,
    service_scope text not null,
    reason text,
    confirmation_key text not null,
    confirmed_at timestamptz not null,
    legal_acceptances_snapshot jsonb not null default '[]'::jsonb,
    idempotency_key text not null,
    request_hash text not null,
    status text not null default 'submitted',
    resolution text,
    last_reviewed_at timestamptz,
    last_reviewed_by text,
    review_note text,
    version integer not null default 1,
    submitted_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint service_withdrawal_buyer_not_blank
        check (length(btrim(buyer_cms_user_id)) between 1 and 512),
    constraint service_withdrawal_scope
        check (service_scope ~ '^[a-z][a-z0-9_.-]{1,79}$'),
    constraint service_withdrawal_reason
        check (reason is null or length(btrim(reason)) between 1 and 4000),
    constraint service_withdrawal_confirmation
        check (confirmation_key ~ '^[a-z][a-z0-9_.-]{1,119}$'),
    constraint service_withdrawal_legal_snapshot
        check (
            jsonb_typeof(legal_acceptances_snapshot) = 'array'
            and pg_column_size(legal_acceptances_snapshot) <= 262144
        ),
    constraint service_withdrawal_idempotency
        check (length(btrim(idempotency_key)) between 1 and 200),
    constraint service_withdrawal_request_hash
        check (request_hash ~ '^[a-f0-9]{64}$'),
    constraint service_withdrawal_status
        check (status in ('submitted', 'under_review', 'information_requested', 'resolved')),
    constraint service_withdrawal_resolution
        check (resolution is null or resolution in ('accepted', 'rejected', 'no_action')),
    constraint service_withdrawal_resolution_state
        check (
            (status = 'resolved' and resolution is not null)
            or (status <> 'resolved' and resolution is null)
        ),
    constraint service_withdrawal_review_state
        check (
            (status = 'submitted'
                and last_reviewed_at is null
                and last_reviewed_by is null
                and review_note is null)
            or (status <> 'submitted'
                and last_reviewed_at is not null
                and length(btrim(last_reviewed_by)) between 1 and 512
                and length(btrim(review_note)) between 1 and 4000)
        ),
    constraint service_withdrawal_version_positive check (version > 0),
    constraint service_withdrawal_order_scope_unique unique (order_id, service_scope),
    constraint service_withdrawal_buyer_idempotency_unique
        unique (buyer_cms_user_id, idempotency_key)
);

create index if not exists marketplace_service_withdrawal_queue_idx
    on commerce.marketplace_service_withdrawal_requests(status, submitted_at, id);
create index if not exists marketplace_service_withdrawal_buyer_idx
    on commerce.marketplace_service_withdrawal_requests(
        buyer_cms_user_id, submitted_at desc, id desc
    );

create table if not exists commerce.marketplace_service_withdrawal_events (
    id bigint generated by default as identity primary key,
    request_id bigint not null
        references commerce.marketplace_service_withdrawal_requests(id) on delete restrict,
    order_id bigint not null references commerce.orders(id) on delete restrict,
    event_type text not null,
    actor_kind text not null,
    actor_id text not null,
    previous_status text,
    next_status text not null,
    request_version integer not null,
    note text,
    data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint service_withdrawal_events_type
        check (event_type in ('submitted', 'reviewed')),
    constraint service_withdrawal_events_actor
        check (actor_kind in ('buyer', 'admin')),
    constraint service_withdrawal_events_actor_id
        check (length(btrim(actor_id)) between 1 and 512),
    constraint service_withdrawal_events_previous_status
        check (
            previous_status is null
            or previous_status in ('submitted', 'under_review', 'information_requested', 'resolved')
        ),
    constraint service_withdrawal_events_next_status
        check (next_status in ('submitted', 'under_review', 'information_requested', 'resolved')),
    constraint service_withdrawal_events_version check (request_version > 0),
    constraint service_withdrawal_events_note
        check (note is null or length(btrim(note)) between 1 and 4000),
    constraint service_withdrawal_events_data
        check (jsonb_typeof(data) = 'object' and pg_column_size(data) <= 65536)
);

create index if not exists marketplace_service_withdrawal_events_request_idx
    on commerce.marketplace_service_withdrawal_events(request_id, created_at, id);
create index if not exists marketplace_service_withdrawal_events_order_idx
    on commerce.marketplace_service_withdrawal_events(order_id, created_at, id);

comment on table commerce.marketplace_service_withdrawal_requests is
    'Auditable buyer requests concerning a marketplace service; no row has automatic cancellation or financial effect.';
comment on column commerce.marketplace_service_withdrawal_requests.service_scope is
    'Site-defined stable service identifier. It is evidence of requested scope, not a legal eligibility decision.';
comment on column commerce.marketplace_service_withdrawal_requests.legal_acceptances_snapshot is
    'Latest accepted document version and hash per document when the request was submitted, or an empty array.';
