export { orderFields } from "../projections.ts";

export const lineFields = [
    "id",
    "orderId",
    "offerId",
    "productId",
    "variantId",
    "acceptedProposalId",
    "title",
    "sku",
    "quantity",
    "unitAmount",
    "totalAmount",
    "productSnapshot",
    "variantSnapshot",
    "offerSnapshot",
    "sellerSnapshot",
    "createdAt",
] as const;
export const sellerLineFields = lineFields.filter((field) => field !== "sellerSnapshot");
export const publicEventFields = ["id", "orderId", "eventType", "previousStatus", "nextStatus", "createdAt"] as const;
export const adminEventFields = [
    "id",
    "orderId",
    "eventType",
    "actorKind",
    "actorId",
    "previousStatus",
    "nextStatus",
    "message",
    "data",
    "createdAt",
] as const;
export const sellerFields = ["id", "kind", "slug", "displayName"] as const;
export const operationFields = [
    "orderId",
    "orderPublicId",
    "orderNumber",
    "buyerCmsUserId",
    "sellerId",
    "currency",
    "buyerTotalAmount",
    "sellerProceedsAmount",
    "platformRetainedAmount",
    "financialTermsHash",
    "paymentStatus",
    "fulfillmentStatus",
    "settlementStatus",
    "claimStatus",
    "totalRefundRequestedAmount",
    "releaseEligibleAt",
    "recipientHandoffAt",
    "recipientHandoffFirstObservedAt",
    "claimWindowStartedAt",
    "claimByAt",
    "updatedAt",
] as const;
export const sellerOperationFields = [
    "orderId",
    "orderPublicId",
    "orderNumber",
    "currency",
    "paymentStatus",
    "fulfillmentStatus",
    "settlementStatus",
    "claimStatus",
    "recipientHandoffAt",
    "recipientHandoffFirstObservedAt",
    "claimWindowStartedAt",
    "claimByAt",
    "releaseEligibleAt",
    "updatedAt",
] as const;
export const financialFields = [
    "orderId",
    "deliveryQuoteId",
    "merchandiseSubtotalAmount",
    "shippingAmount",
    "buyerProtectionFeeAmount",
    "sellerCommissionAmount",
    "buyerTotalAmount",
    "sellerProceedsAmount",
    "platformRetainedAmount",
    "currency",
    "financialTermsHash",
    "pricingLockedAt",
    "payByAt",
    "financialRevision",
] as const;
export const sellerFinancialFields = [
    "orderId",
    "merchandiseSubtotalAmount",
    "shippingAmount",
    "sellerCommissionAmount",
    "platformShippingShareAmount",
    "sellerShippingShareAmount",
    "sellerProceedsAmount",
    "sellerTransferReleaseAmount",
    "sellerReserveLiabilityAmount",
    "currency",
    "pricingLockedAt",
    "payByAt",
    "financialRevision",
] as const;
export const fulfillmentFields = [
    "orderId",
    "status",
    "sellerHandoffDeadline",
    "scanGraceDeadline",
    "carrierAcceptedAt",
    "arrivedAtPickupPointAt",
    "availableForPickupAt",
    "recipientHandoffAt",
    "recipientHandoffFirstObservedAt",
    "claimWindowStartedAt",
    "claimByAt",
    "releaseEligibleAt",
    "blockingReason",
    "version",
] as const;
export const sellerFulfillmentFields = [
    "orderId",
    "status",
    "sellerHandoffDeadline",
    "scanGraceDeadline",
    "sellerHandoffDeclaredAt",
    "carrierAcceptedAt",
    "recipientHandoffAt",
    "recipientHandoffFirstObservedAt",
    "claimWindowStartedAt",
    "claimByAt",
    "releaseEligibleAt",
    "blockingReason",
    "version",
] as const;
export const settlementFields = [
    "orderId",
    "status",
    "authorizedSellerAmount",
    "totalTransferredAmount",
    "totalReversedAmount",
    "totalRefundedAmount",
    "sellerReserveLiabilityRemainingAmount",
    "version",
] as const;
export const sellerSettlementFields = settlementFields.filter((field) => field !== "totalRefundedAmount");
export const claimFields = [
    "id",
    "publicId",
    "reason",
    "status",
    "sellerResponseByAt",
    "returnShipByAt",
    "resolvedAt",
    "version",
    "createdAt",
] as const;
export const authorizationFields = [
    "allowed",
    "reason",
    "orderId",
    "orderPublicId",
    "sellerId",
    "currency",
    "paymentStatus",
    "fulfillmentStatus",
] as const;
