\set ON_ERROR_STOP on

\if :{?cms_integration_schema_bundle}
\else
    \echo 'cms_integration_schema_bundle must point to an assembled temporary SQL bundle.'
    \quit 3
\endif

\if :{?allow_commerce_notification_schema_reset}
\else
    \echo 'Set allow_commerce_notification_schema_reset=true on a disposable database.'
    \quit 3
\endif

drop schema if exists commerce cascade;

do $roles$
begin
    if not exists (select 1 from pg_roles where rolname = 'anon') then
        create role anon nologin;
    end if;
    if not exists (select 1 from pg_roles where rolname = 'authenticated') then
        create role authenticated nologin;
    end if;
    if not exists (select 1 from pg_roles where rolname = 'service_role') then
        create role service_role nologin bypassrls;
    end if;
end;
$roles$;

create schema commerce;

create table commerce.orders (
    id bigint generated by default as identity primary key,
    public_id uuid not null default gen_random_uuid() unique,
    order_number text not null unique,
    buyer_cms_user_id text not null,
    status text not null,
    currency text not null,
    subtotal_amount bigint not null,
    shipping_amount bigint not null default 0,
    total_amount bigint not null
);

create table commerce.offers (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    title text not null
);

create table commerce.price_agreements (
    id bigint generated by default as identity primary key,
    public_id uuid not null default gen_random_uuid() unique,
    authority_version integer not null,
    offer_id bigint not null references commerce.offers(id) on delete restrict,
    unit_amount bigint not null,
    currency text not null,
    quantity integer not null,
    status text not null,
    expires_at timestamptz not null
);

create table commerce.audit_events (
    id bigint generated by default as identity primary key,
    order_id bigint references commerce.orders(id) on delete restrict,
    aggregate_type text not null,
    aggregate_id text not null,
    event_type text not null,
    actor_kind text not null,
    actor_id text not null,
    reason text,
    data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

\ir :cms_integration_schema_bundle
\ir :cms_integration_schema_bundle

do $reapply$
begin
    if (select count(*) from commerce.notification_rules) <> 12 then
        raise exception 'notification rules were not seeded exactly once';
    end if;
    if (select mode from commerce.notification_configuration where id = 'default') <> 'builtin' then
        raise exception 'native notification delivery is not the default';
    end if;
end;
$reapply$;
