

create table if not exists commerce.financial_exceptions (
    id bigint generated by default as identity primary key,
    deduplication_key text,
    order_id bigint references commerce.orders(id) on delete restrict,
    kind text not null,
    severity text not null default 'high',
    status text not null default 'open',
    reason text not null,
    details jsonb not null default '{}'::jsonb,
    detected_at timestamptz not null default now(),
    resolved_at timestamptz,
    resolved_by text,
    constraint financial_exceptions_kind check (kind in (
        'payment_mismatch', 'fulfillment_ambiguity', 'settlement_ambiguity',
        'refund_failure', 'provider_dispute', 'reconciliation_mismatch', 'risk_hold',
        'seller_debt', 'late_payment_success'
    )),
    constraint financial_exceptions_severity check (severity in ('medium', 'high', 'critical')),
    constraint financial_exceptions_status check (status in ('open', 'investigating', 'resolved')),
    constraint financial_exceptions_reason check (length(btrim(reason)) > 0),
    constraint financial_exceptions_details check (jsonb_typeof(details) = 'object')
);

alter table commerce.financial_exceptions
    add column if not exists deduplication_key text;

create unique index if not exists financial_exceptions_deduplication_key_unique
    on commerce.financial_exceptions(deduplication_key)
    where deduplication_key is not null;

create index if not exists financial_exceptions_queue_idx
    on commerce.financial_exceptions(status, severity, detected_at)
    where status <> 'resolved';

alter table commerce.financial_exceptions
    drop constraint if exists financial_exceptions_kind;
alter table commerce.financial_exceptions
    add constraint financial_exceptions_kind check (kind in (
        'payment_mismatch', 'fulfillment_ambiguity', 'settlement_ambiguity',
        'refund_failure', 'provider_dispute', 'reconciliation_mismatch', 'risk_hold',
        'seller_debt', 'late_payment_success'
    ));