import type { SourceEndpoint } from "@bernouy/cms-sources";
import { array, boolean, endpoint, fulfillmentAddressShape, number, object, string } from "../builders";

export const deliveryCreationEndpoints: SourceEndpoint[] = [
    endpoint(
        "createShipment",
        "POST",
        "/createShipment",
        object({
            ok: boolean(),
            id: string(),
            expeditionNumber: string(),
            status: string(),
            trackingUrl: string(),
            createdAt: string(),
            idempotentReplay: boolean(),
        }),
        undefined,
        {
            externalOrderId: string(),
            sellerCmsUserId: { type: "string", semantic: "user-id" },
            deliveryQuoteId: string(),
            quoteExternalOrderId: string(),
            quotePurpose: string(),
            selectedForCmsUserId: { type: "string", semantic: "user-id" },
            senderName: string(),
            senderFirstName: string(),
            senderLastName: string(),
            senderEmail: string(),
            senderPhone: string(),
            senderAddressLine1: string(),
            senderAddressLine2: string(),
            senderAddressLine3: string(),
            senderPostalCode: string(),
            senderCity: string(),
            senderCountry: string(),
            recipientName: string(),
            recipientFirstName: string(),
            recipientLastName: string(),
            recipientEmail: string(),
            recipientPhone: string(),
            recipientAddressLine1: string(),
            recipientAddressLine2: string(),
            recipientAddressLine3: string(),
            recipientPostalCode: string(),
            recipientCity: string(),
            recipientCountry: string(),
            deliveryRelayLocation: string(),
            weightGrams: number(),
            packageCount: number(),
            declaredValueMinorAmount: number(),
            declaredCurrency: string(),
            metadata: object({
                commerceOrderId: string(),
                financialTermsHash: string(),
                commerceClaimId: number(),
                shipmentKind: string(),
                deliveryQuoteId: string(),
                declaredValueMinorAmount: number(),
                declaredCurrency: string(),
            }),
        },
        "system",
        ["200", "201"],
    ),
    endpoint(
        "shipments",
        "GET",
        "/shipments",
        object({
            items: array({ id: string(), status: string() }),
            limit: number(),
            offset: number(),
        }),
        { externalOrderId: string(), limit: number(), offset: number() },
    ),
];
