export const MIN_SCHEDULED_TRIGGER_INTERVAL_MS = 5_000;
export const MAX_SCHEDULED_TRIGGER_INTERVAL_MS = 24 * 60 * 60_000;
export const DEFAULT_SCHEDULED_TRIGGER_TIMEOUT_MS = 2 * 60_000;
export const MAX_SCHEDULED_TRIGGER_TIMEOUT_MS = 15 * 60_000;
export const DEFAULT_SCHEDULED_TRIGGER_LEASE_BUFFER_MS = 30_000;
export const DEFAULT_SCHEDULED_TRIGGER_POLL_MS = 1_000;
export const DEFAULT_SCHEDULED_TRIGGER_CLAIM_LIMIT = 10;
