import { describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { pullBlocs } from "cms-cli/push/blocs/pull";
import { withFetch } from "../fixtures";

describe("pullBlocs", () => {
    test("rejects a traversal tag without replacing the existing bloc tree", async () => {
        const siteDir = mkdtempSync(join(tmpdir(), "p9r-bloc-pull-"));
        const marker = join(siteDir, "blocs", "Keep", "safe-card", "marker.txt");
        mkdirSync(join(siteDir, "blocs", "Keep", "safe-card"), { recursive: true });
        writeFileSync(marker, "keep");

        await withFetch(
            async (url) =>
                url.endsWith("/api/bloc/list")
                    ? Response.json([{ id: "..", group: "Generated", ownership: { kind: "code-managed" } }])
                    : new Response("source must not be fetched", { status: 500 }),
            async () => {
                const result = await pullBlocs(new URL("http://cms.test/"), "token", siteDir);

                expect(result.pulled).toEqual([]);
                expect(result.failed[0]?.error).toContain("Invalid remote bloc tag");
                expect(readFileSync(marker, "utf-8")).toBe("keep");
            },
        );
    });

    test("skips blocs already owned by generated integration artifacts", async () => {
        const siteDir = mkdtempSync(join(tmpdir(), "p9r-bloc-pull-"));
        mkdirSync(join(siteDir, ".p9r", "generated"), { recursive: true });
        writeFileSync(
            join(siteDir, ".p9r", "generated", "integration-installations.json"),
            JSON.stringify([
                {
                    id: "demo",
                    artifacts: [{ type: "bloc", id: "demo-card", action: "created" }],
                },
            ]),
        );

        await withFetch(
            async (url) => {
                if (url.endsWith("/api/bloc/list")) {
                    return Response.json([
                        { id: "demo-card", group: "Generated", ownership: { kind: "code-managed" } },
                    ]);
                }
                if (url.includes("/api/bloc/source")) {
                    throw new Error("generated bloc source should not be fetched by pullBlocs");
                }
                return new Response("not found", { status: 404 });
            },
            async () => {
                const result = await pullBlocs(new URL("http://cms.test/"), "token", siteDir);

                expect(result.pulled).toEqual([]);
                expect(result.failed).toEqual([]);
                expect(result.skipped).toEqual([
                    {
                        tag: "demo-card",
                        reason: "generated by an integration; use `p9r pull --type=integrations`",
                    },
                ]);
            },
        );
    });
});
