import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { getAccessToken } from "./credentials";

/**
 * `p9r secrets template` — emits a `.env.example`-style file from the
 * remote's secret keys (NEVER values). For onboarding: a fresh dev
 * clones the repo, runs the command, and gets a list of every `${KEY}`
 * the deployment expects, ready to be filled with their own dev creds.
 *
 * Subcommand routing kept open so future operations (`list`, `set` from
 * a vault import, …) plug in without changing dispatch.
 */

const DEFAULT_OUTPUT = ".env.example";

async function resolveAdmin(): Promise<{ base: URL; token: string }> {
    const rawUrl = Bun.env.P9R_URL;
    if (!rawUrl || !/^https?:\/\//i.test(rawUrl)) {
        console.error("✖ P9R_URL must be set and start with http(s)://. Run `p9r login` after.");
        process.exit(1);
    }
    const token = await getAccessToken(rawUrl.replace(/\/+$/, ""));
    if (!token) {
        console.error(`✖ No credentials for ${rawUrl}. Run \`p9r login --url=${rawUrl}\`.`);
        process.exit(1);
    }
    return { base: new URL(rawUrl.replace(/\/$/, "") + "/"), token };
}

async function fetchKeys(base: URL, token: string): Promise<string[]> {
    const url = new URL("api/secrets/keys", base).href;
    const res = await fetch(url, { headers: { Authorization: `Bearer ${token}` } });
    if (res.status === 401 || res.status === 403) {
        console.error(`✖ Remote refused the credentials (HTTP ${res.status}). Run \`p9r login\` again.`);
        process.exit(1);
    }
    if (!res.ok) {
        console.error(`✖ GET ${url} → HTTP ${res.status}`);
        process.exit(1);
    }
    const data = await res.json().catch(() => null);
    if (!Array.isArray(data)) {
        console.error(`✖ GET ${url} did not return a JSON array`);
        process.exit(1);
    }
    return data as string[];
}

function buildEnvExample(keys: string[]): string {
    return [
        "# Generated by `p9r secrets template`.",
        "# Lists the secret KEYS expected by the remote deployment.",
        "# Fill in your local values, copy to `.env`, and NEVER commit either file.",
        "",
        ...keys.sort((a, b) => a.localeCompare(b)).map(k => `${k}=`),
    ].join("\n") + "\n";
}

async function runTemplate(args: string[]) {
    let output = DEFAULT_OUTPUT;
    let force  = false;
    for (const arg of args) {
        if (arg === "--force" || arg === "-f")    force  = true;
        else if (arg.startsWith("--output="))     output = arg.slice("--output=".length);
        else if (arg.startsWith("-o="))           output = arg.slice("-o=".length);
    }
    const target = resolve(process.cwd(), output);
    if (existsSync(target) && !force) {
        console.error(`✖ ${output} already exists — pass --force to overwrite.`);
        process.exit(1);
    }
    const { base, token } = await resolveAdmin();
    const keys = await fetchKeys(base, token);
    writeFileSync(target, buildEnvExample(keys), "utf8");
    console.log(`✓ Wrote ${keys.length} key${keys.length === 1 ? "" : "s"} to ${output}`);
    if (keys.length === 0) console.log("  (the remote has no secrets — file holds only the header)");
    else                   console.log("  Fill in your local values, then `cp .env.example .env`.");
}

export default async function CLI_secrets(args: string[]) {
    const [sub, ...rest] = args;
    switch (sub) {
        case "template":
            await runTemplate(rest);
            break;
        case undefined:
        case "help":
        case "--help":
        case "-h":
            console.log(`Usage:
  p9r secrets template [--output=<path>] [--force]
      Generate an .env.example file with KEYS only (no values) from the
      remote deployment's secrets. Default output: .env.example.`);
            break;
        default:
            console.error(`✖ Unknown subcommand: \`p9r secrets ${sub}\`. Try \`p9r secrets help\`.`);
            process.exit(1);
    }
}
