

create table if not exists commerce.shipment_creation_operations (
    id bigint generated by default as identity primary key,
    order_id bigint not null references commerce.orders(id) on delete restrict,
    business_key text not null constraint shipment_creation_operations_business_key_key unique,
    delivery_quote_id text not null,
    financial_terms_hash text not null,
    status text not null default 'requested',
    claim_token uuid,
    claimed_at timestamptz,
    claimed_by text,
    attempts integer not null default 0,
    provider_reference text,
    provider_shipment_id text,
    provider_snapshot jsonb not null default '{}'::jsonb,
    available_at timestamptz not null default now(),
    last_error text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint shipment_creation_operations_order_unique unique (order_id),
    constraint shipment_creation_operations_key check (length(btrim(business_key)) > 0),
    constraint shipment_creation_operations_quote check (length(btrim(delivery_quote_id)) > 0),
    constraint shipment_creation_operations_hash check (financial_terms_hash ~ '^[a-f0-9]{64}$'),
    constraint shipment_creation_operations_status check (status in (
        'requested', 'processing', 'succeeded', 'unknown', 'failed', 'cancelled', 'manual_review'
    )),
    constraint shipment_creation_operations_attempts check (attempts between 0 and 100),
    constraint shipment_creation_operations_claim check (
        (status = 'processing' and claim_token is not null and claimed_at is not null and claimed_by is not null)
        or (status <> 'processing' and claim_token is null and claimed_at is null and claimed_by is null)
    ),
    constraint shipment_creation_operations_snapshot check (jsonb_typeof(provider_snapshot) = 'object')
);
create index if not exists shipment_creation_operations_due_idx
    on commerce.shipment_creation_operations(available_at, created_at, id)
    where status in ('requested', 'failed');

create table if not exists commerce.shipment_cancellation_operations (
    id bigint generated by default as identity primary key,
    order_id bigint not null references commerce.orders(id) on delete restrict,
    order_cancellation_request_id bigint not null references commerce.order_cancellation_requests(id) on delete restrict,
    business_key text not null constraint shipment_cancellation_operations_business_key_key unique,
    status text not null default 'requested',
    claim_token uuid,
    claimed_at timestamptz,
    claimed_by text,
    attempts integer not null default 0,
    tracking_until timestamptz not null,
    provider_reference text,
    provider_snapshot jsonb not null default '{}'::jsonb,
    available_at timestamptz not null default now(),
    last_error text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint shipment_cancellation_operations_request_unique unique (order_cancellation_request_id),
    constraint shipment_cancellation_operations_key check (length(btrim(business_key)) > 0),
    constraint shipment_cancellation_operations_status check (status in (
        'requested', 'processing', 'provider_cancelled', 'completed', 'failed', 'manual_review'
    )),
    constraint shipment_cancellation_operations_attempts check (attempts between 0 and 100),
    constraint shipment_cancellation_operations_claim check (
        (status = 'processing' and claim_token is not null and claimed_at is not null and claimed_by is not null)
        or (status <> 'processing' and claim_token is null and claimed_at is null and claimed_by is null)
    ),
    constraint shipment_cancellation_operations_snapshot check (jsonb_typeof(provider_snapshot) = 'object')
);
create index if not exists shipment_cancellation_operations_due_idx
    on commerce.shipment_cancellation_operations(available_at, created_at, id)
    where status in ('requested', 'failed');
