

create table if not exists commerce.outbox_events (
    id bigint generated by default as identity primary key,
    order_id bigint references commerce.orders(id) on delete restrict,
    topic text not null,
    event_key text not null constraint outbox_events_event_key_key unique,
    payload jsonb not null,
    status text not null default 'pending',
    available_at timestamptz not null default now(),
    claimed_at timestamptz,
    claimed_by text,
    delivered_at timestamptz,
    attempts integer not null default 0,
    last_error text,
    created_at timestamptz not null default now(),
    constraint outbox_events_topic check (length(btrim(topic)) > 0),
    constraint outbox_events_key check (length(btrim(event_key)) > 0),
    constraint outbox_events_payload check (jsonb_typeof(payload) = 'object'),
    constraint outbox_events_status check (status in ('pending', 'processing', 'delivered', 'failed')),
    constraint outbox_events_attempts check (attempts >= 0)
);

create index if not exists outbox_events_claim_idx
    on commerce.outbox_events(available_at, id)
    where status in ('pending', 'failed');
