

create table if not exists commerce.seller_financial_exposures (
    id bigint generated by default as identity primary key,
    seller_id bigint not null references commerce.sellers(id) on delete restrict,
    order_id bigint not null references commerce.orders(id) on delete restrict,
    exposure_key text not null constraint seller_financial_exposures_exposure_key_key unique,
    exposure_type text not null,
    status text not null,
    amount bigint not null,
    recovered_amount bigint not null default 0,
    currency text not null default 'eur',
    reason text not null,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint seller_financial_exposures_type check (
        exposure_type in ('reserve', 'chargeback', 'reversal_failure')
    ),
    constraint seller_financial_exposures_status check (
        status in ('held', 'at_risk', 'debt', 'recovered', 'waived')
    ),
    constraint seller_financial_exposures_amounts check (
        amount between 1 and 9007199254740991
        and recovered_amount between 0 and amount
    ),
    constraint seller_financial_exposures_currency check (currency = 'eur'),
    constraint seller_financial_exposures_reason check (length(btrim(reason)) > 0),
    constraint seller_financial_exposures_details check (jsonb_typeof(details) = 'object')
);

create index if not exists seller_financial_exposures_seller_status_idx
    on commerce.seller_financial_exposures(seller_id, status, created_at desc);
