

create table if not exists commerce.brands (
    id bigint generated by default as identity primary key,
    slug text not null constraint brands_slug_key unique,
    name text not null,
    description text,
    status text not null default 'active',
    position integer not null default 0,
    metadata jsonb not null default '{}'::jsonb,
    version integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint brands_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    constraint brands_slug_length check (length(slug) <= 120),
    constraint brands_name_not_blank check (length(btrim(name)) > 0),
    constraint brands_name_length check (length(name) <= 200),
    constraint brands_description_length check (description is null or length(description) <= 10000),
    constraint brands_status check (status in ('active', 'inactive', 'archived')),
    constraint brands_metadata_object check (jsonb_typeof(metadata) = 'object'),
    constraint brands_metadata_size check (pg_column_size(metadata) <= 32768),
    constraint brands_version_positive check (version > 0)
);

alter table commerce.brands add column if not exists position integer not null default 0;

create table if not exists commerce.categories (
    id bigint generated by default as identity primary key,
    parent_id bigint references commerce.categories(id) on delete restrict,
    slug text not null,
    full_slug text not null,
    label text not null,
    description text,
    status text not null default 'active',
    position integer not null default 0,
    metadata jsonb not null default '{}'::jsonb,
    version integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint categories_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    constraint categories_slug_length check (length(slug) <= 120),
    constraint categories_full_slug_unique unique (full_slug),
    constraint categories_parent_slug_unique unique nulls not distinct (parent_id, slug),
    constraint categories_label_not_blank check (length(btrim(label)) > 0),
    constraint categories_label_length check (length(label) <= 200),
    constraint categories_description_length check (description is null or length(description) <= 10000),
    constraint categories_status check (status in ('active', 'inactive', 'archived')),
    constraint categories_no_self_parent check (parent_id is null or parent_id <> id),
    constraint categories_metadata_object check (jsonb_typeof(metadata) = 'object'),
    constraint categories_metadata_size check (pg_column_size(metadata) <= 32768),
    constraint categories_version_positive check (version > 0)
);

create table if not exists commerce.products (
    id bigint generated by default as identity primary key,
    slug text not null constraint products_slug_key unique,
    title text not null,
    description text,
    brand_id bigint references commerce.brands(id) on delete restrict,
    status text not null default 'draft',
    visibility text not null default 'public',
    metadata jsonb not null default '{}'::jsonb,
    version integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint products_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    constraint products_slug_length check (length(slug) <= 160),
    constraint products_title_not_blank check (length(btrim(title)) > 0),
    constraint products_title_length check (length(title) <= 300),
    constraint products_description_length check (description is null or length(description) <= 20000),
    constraint products_status check (status in ('draft', 'active', 'archived')),
    constraint products_visibility check (visibility in ('public', 'hidden')),
    constraint products_metadata_object check (jsonb_typeof(metadata) = 'object'),
    constraint products_metadata_size check (pg_column_size(metadata) <= 65536),
    constraint products_version_positive check (version > 0)
);

alter table commerce.products add column if not exists brand_id bigint references commerce.brands(id) on delete restrict;

create table if not exists commerce.product_categories (
    product_id bigint not null references commerce.products(id) on delete cascade,
    category_id bigint not null references commerce.categories(id) on delete restrict,
    is_primary boolean not null default false,
    position integer not null default 0,
    created_at timestamptz not null default now(),
    primary key (product_id, category_id)
);

create unique index if not exists product_categories_primary_unique
    on commerce.product_categories(product_id) where is_primary;
