

create table if not exists commerce.audit_events (
    id bigint generated by default as identity primary key,
    order_id bigint references commerce.orders(id) on delete restrict,
    aggregate_type text not null,
    aggregate_id text not null,
    event_type text not null,
    actor_kind text not null,
    actor_id text not null,
    reason text,
    data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint audit_events_actor_kind check (actor_kind in ('buyer', 'seller', 'support', 'finance', 'admin', 'system', 'provider')),
    constraint audit_events_data check (jsonb_typeof(data) = 'object')
);

alter table commerce.audit_events
    drop constraint if exists audit_events_actor_kind;
alter table commerce.audit_events
    add constraint audit_events_actor_kind check (
        actor_kind in ('buyer', 'seller', 'support', 'finance', 'admin', 'system', 'provider')
    );

create index if not exists audit_events_order_idx
    on commerce.audit_events(order_id, created_at, id);
create index if not exists audit_events_aggregate_idx
    on commerce.audit_events(aggregate_type, aggregate_id, created_at, id);