import type DeliveryCms from "cms-delivery/DeliveryCms";
import { cachedResponseAsync, publicAssetCacheControl } from "@bernouy/cms-shared";
import { generateStyleEntry } from "cms-delivery/core/assets/buildStyle";
import { P9R_CACHE } from "@bernouy/cms-shared";

/**
 * Serves the theme CSS generated by `core/assets/buildStyle`. Every rendered
 * public page links to this URL with a content-hash query (`?v=...`), so
 * editing the theme requires invalidating `P9R_CACHE.STYLE`.
 */
export default async function StyleServer(req: Request, delivery: DeliveryCms) {
    return cachedResponseAsync(
        req,
        P9R_CACHE.STYLE,
        delivery.cache,
        () => generateStyleEntry(delivery.repository),
        publicAssetCacheControl(req),
    );
}
