import { writeFile, rename } from "node:fs/promises";
import type { Bucket } from "../../interfaces/entities/Bucket";

const HEADER = "# Generated by BasicStorageProvider — do not edit by hand.\n";

/**
 * Atomic write of the bucket → Cache-Control map fragment included inside
 * Nginx's `map $bucket_id $cache_control { … }` block. The temp + rename keeps
 * Nginx from ever reading a half-written file on a concurrent reload.
 */
export async function regenerateCacheControls(buckets: Bucket[], outputPath: string): Promise<void> {
    const lines = buckets.map(b => `${b.id} ${quote(b.cacheControl)};`);
    const body = HEADER + lines.join("\n") + (lines.length > 0 ? "\n" : "");
    const tempPath = outputPath + ".tmp";
    await writeFile(tempPath, body);
    await rename(tempPath, outputPath);
}

function quote(value: string): string {
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
