import type { SourceEndpoint } from "@bernouy/cms-sources";
import { array, boolean, endpoint, fulfillmentAddressShape, number, object, string } from "../builders";

export const commerceAuthorizationEndpoints: SourceEndpoint[] = [
    endpoint(
        "getOrderFulfillmentAuthorization",
        "GET",
        "/fulfillment-authorization",
        object({
            allowed: boolean(),
            reason: { type: "string", nullable: true },
            orderId: number(),
            orderPublicId: string(),
            sellerId: { type: "string", semantic: "user-id" },
            buyerCmsUserId: string(),
            currency: string(),
            deliveryQuoteId: string(),
            merchandiseSubtotalMinorAmount: number(),
            shippingAmount: number(),
            buyerTotalAmount: number(),
            financialTermsHash: string(),
            paymentStatus: string(),
            fulfillmentStatus: string(),
        }),
        { orderPublicId: string() },
        undefined,
        "system",
    ),
    endpoint(
        "reserveOrderShipmentCreation",
        "POST",
        "/reserveShipmentCreation",
        object({
            operationId: number(),
            claimToken: string(),
            orderId: number(),
            orderPublicId: string(),
            sellerId: { type: "string", semantic: "user-id" },
            buyerCmsUserId: string(),
            currency: string(),
            deliveryQuoteId: string(),
            merchandiseSubtotalMinorAmount: number(),
            shippingAmount: number(),
            buyerTotalAmount: number(),
            financialTermsHash: string(),
            paymentStatus: string(),
            fulfillmentStatus: string(),
        }),
        undefined,
        { orderPublicId: string(), workerId: string() },
        "system",
        ["200", "409"],
    ),
    endpoint(
        "getOrderLabelAuthorization",
        "GET",
        "/label-authorization",
        object({
            allowed: boolean(),
            reason: string(),
            orderId: number(),
            orderPublicId: string(),
            sellerId: { type: "string", semantic: "user-id" },
            sellerCmsUserId: { type: "string", semantic: "user-id" },
            providerReference: string(),
        }),
        { orderPublicId: string() },
        undefined,
        "system",
    ),
];
