import type { SourceEndpoint } from "@bernouy/cms-sources";
import { array, boolean, endpoint, fulfillmentAddressShape, number, object, string } from "../builders";

export const commerceClaimEndpoints: SourceEndpoint[] = [
    endpoint(
        "getClaimReturnAuthorization",
        "GET",
        "/claim-return-authorization",
        object({
            allowed: boolean(),
            reason: string(),
            claimId: number(),
            claimPublicId: string(),
            claimStatus: string(),
            claimVersion: number(),
            returnShipByAt: string(),
            returnDeliveryStatus: string(),
            orderId: number(),
            orderPublicId: string(),
            orderNumber: string(),
            buyerCmsUserId: { type: "string", semantic: "user-id" },
            sellerId: number(),
            sellerCmsUserId: { type: "string", semantic: "user-id" },
            deliveryQuoteId: string(),
            merchandiseSubtotalMinorAmount: number(),
            currency: string(),
        }),
        { claimId: number() },
        undefined,
        "system",
    ),
    endpoint(
        "recordOrderFulfillment",
        "POST",
        "/recordOrderFulfillment",
        object({
            orderId: number(),
            orderPublicId: string(),
            status: string(),
            providerReference: string(),
            carrierAcceptedAt: string(),
            sellerHandoffDeclaredAt: string(),
            recipientHandoffAt: string(),
            claimByAt: string(),
            releaseEligibleAt: string(),
            blockingReason: string(),
            version: number(),
        }),
        undefined,
        {
            orderPublicId: string(),
            providerEventId: string(),
            normalizedStatus: string(),
            occurredAt: string(),
            providerReference: string(),
            recipientHandoffAt: string(),
            carrierAcceptedAt: string(),
            sellerHandoffDeclaredAt: string(),
        },
        "system",
    ),
    endpoint(
        "recordClaimReturnDelivery",
        "POST",
        "/recordClaimReturnDelivery",
        object({
            id: number(),
            status: string(),
            returnDeliveryStatus: string(),
        }),
        undefined,
        {
            claimId: number(),
            providerEventId: string(),
            providerReference: string(),
            normalizedStatus: string(),
            occurredAt: string(),
            providerEvidence: object({
                provider: string(),
                shipmentId: string(),
                providerStatus: string(),
            }),
        },
        "system",
    ),
];
