

create table if not exists commerce.order_lines (
    id bigint generated by default as identity primary key,
    order_id bigint not null references commerce.orders(id) on delete restrict,
    seller_id bigint not null references commerce.sellers(id) on delete restrict,
    offer_id bigint not null references commerce.offers(id) on delete restrict,
    product_id bigint not null references commerce.products(id) on delete restrict,
    variant_id bigint references commerce.product_variants(id) on delete restrict,
    accepted_proposal_id bigint references commerce.offer_price_proposals(id) on delete restrict,
    title text not null,
    sku text,
    quantity integer not null,
    inventory_reserved integer not null default 0,
    availability_before text,
    inventory_revision_before integer,
    unit_amount bigint not null,
    total_amount bigint not null,
    product_snapshot jsonb not null,
    variant_snapshot jsonb,
    offer_snapshot jsonb not null,
    seller_snapshot jsonb not null,
    created_at timestamptz not null default now(),
    constraint order_lines_order_seller_fk foreign key (seller_id, order_id)
        references commerce.orders(seller_id, id) on delete restrict,
    constraint order_lines_offer_seller_fk foreign key (seller_id, offer_id)
        references commerce.offers(seller_id, id) on delete restrict,
    constraint order_lines_product_variant_fk foreign key (product_id, variant_id)
        references commerce.product_variants(product_id, id) on delete restrict,
    constraint order_lines_offer_proposal_fk foreign key (offer_id, accepted_proposal_id)
        references commerce.offer_price_proposals(offer_id, id) on delete restrict,
    constraint order_lines_title_not_blank check (length(btrim(title)) > 0),
    constraint order_lines_title_length check (length(title) <= 300),
    constraint order_lines_sku_length check (sku is null or length(sku) <= 160),
    constraint order_lines_quantity_positive check (quantity between 1 and 1000),
    constraint order_lines_inventory_reserved check (
        inventory_reserved between 0 and quantity
        and ((inventory_reserved = 0 and availability_before is null and inventory_revision_before is null)
            or (inventory_reserved > 0
                and availability_before in ('available', 'unavailable', 'preorder')
                and inventory_revision_before > 0))
    ),
    constraint order_lines_amounts_non_negative check (
        unit_amount between 0 and 9007199254740991
        and total_amount between 0 and 9007199254740991
    ),
    constraint order_lines_total_matches check (total_amount = unit_amount * quantity),
    constraint order_lines_product_snapshot_object check (jsonb_typeof(product_snapshot) = 'object'),
    constraint order_lines_variant_snapshot_object check (
        variant_snapshot is null or jsonb_typeof(variant_snapshot) = 'object'
    ),
    constraint order_lines_offer_snapshot_object check (jsonb_typeof(offer_snapshot) = 'object'),
    constraint order_lines_seller_snapshot_object check (jsonb_typeof(seller_snapshot) = 'object')
);

alter table commerce.offers
    add column if not exists inventory_revision integer not null default 1;
alter table commerce.order_lines
    add column if not exists inventory_revision_before integer;

create table if not exists commerce.order_events (
    id bigint generated by default as identity primary key,
    order_id bigint not null references commerce.orders(id) on delete restrict,
    event_type text not null,
    actor_kind text not null,
    actor_id text not null,
    previous_status text,
    next_status text,
    message text,
    data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint order_events_actor_kind check (actor_kind in ('buyer', 'seller', 'admin', 'system')),
    constraint order_events_data_object check (jsonb_typeof(data) = 'object')
);