export const order = {
    id: 42,
    publicId: "order-public-42",
    buyerCmsUserId: "buyer-user",
    shippingAddress: {
        line1: "7 Private Street",
        postalCode: "75001",
        city: "Paris",
    },
    billingAddress: {
        line1: "7 Private Street",
        postalCode: "75001",
        city: "Paris",
    },
    lines: [{ id: 81, title: "Private basket line" }],
    events: [{ id: 91, type: "payment_pending" }],
    financialTerms: { buyerTotalAmount: 2_500 },
};

export const payment = {
    paymentId: 9,
    providerPaymentId: 9,
    clientReferenceId: order.publicId,
    financialTermsHash: "terms-hash-42",
    financialRevision: 3,
    buyerUserId: "buyer-user",
    sellerUserId: "seller-user",
    stripePaymentIntentId: "pi_9",
    stripeChargeId: "ch_9",
    providerEventId: "evt_9",
    transferGroup: "group_9",
    currency: "EUR",
    amountTotal: 2_500,
    sellerTransferAmount: 2_000,
    platformRetainedAmount: 500,
    refundedAmount: 125,
    transferredAmount: 0,
    reversedAmount: 0,
    stripeChargeBalanceTransactionId: "txn_9",
    actualStripeChargeFeeAmount: 75,
    actualStripeRefundFeeAmount: 0,
    actualStripeProcessingFeeAmount: 75,
    actualStripeChargeNetAmount: 2_425,
    actualStripeFeeCurrency: "EUR",
    actualStripeChargeFeeDetails: [],
    actualPlatformMarginAfterStripeAmount: 425,
    paymentStatus: "succeeded",
    commercePaymentStatus: "manual_review",
    settlementStatus: "manual_review",
    disputeStatus: "none",
    reconciliationPending: true,
    manualReviewReason: "Provider truth is awaiting reconciliation",
    paidAt: "2026-07-17T09:59:00.000Z",
    cancelledAt: null,
    lastProviderSyncAt: "2026-07-17T10:00:00.000Z",
    occurredAt: "2026-07-17T09:59:00.000Z",
    createdAt: "2026-07-17T09:00:00.000Z",
    updatedAt: "2026-07-17T10:00:00.000Z",
};

export const publicPayment = {
    paymentStatus: payment.paymentStatus,
    settlementStatus: payment.settlementStatus,
    disputeStatus: payment.disputeStatus,
    reconciliationPending: payment.reconciliationPending,
    refundedAmount: payment.refundedAmount,
    amountTotal: payment.amountTotal,
    currency: payment.currency,
};

export const recordPaymentBody = {
    orderPublicId: order.publicId,
    providerEventId: `payment-sync:${payment.paymentId}:${payment.updatedAt}`,
    providerPaymentId: payment.paymentId,
    status: payment.commercePaymentStatus,
    amount: payment.amountTotal,
    currency: payment.currency,
    financialTermsHash: payment.financialTermsHash,
    occurredAt: payment.updatedAt,
    providerChargeId: payment.stripeChargeId,
    providerPaymentIntentId: payment.stripePaymentIntentId,
    providerSnapshot: payment,
};
