import { buyerUserId, financialTermsHash, sellerUserId, transferGroup, type JsonRecord } from "../harness";

export const successfulPaymentKeys = [
    "paymentId",
    "providerPaymentId",
    "clientReferenceId",
    "financialTermsHash",
    "financialRevision",
    "buyerUserId",
    "sellerUserId",
    "stripePaymentIntentId",
    "stripeChargeId",
    "providerEventId",
    "transferGroup",
    "currency",
    "amountTotal",
    "sellerTransferAmount",
    "platformRetainedAmount",
    "refundedAmount",
    "transferredAmount",
    "reversedAmount",
    "stripeChargeBalanceTransactionId",
    "actualStripeChargeFeeAmount",
    "actualStripeRefundFeeAmount",
    "actualStripeProcessingFeeAmount",
    "actualStripeChargeNetAmount",
    "actualStripeFeeCurrency",
    "actualStripeChargeFeeDetails",
    "actualPlatformMarginAfterStripeAmount",
    "paymentStatus",
    "commercePaymentStatus",
    "settlementStatus",
    "disputeStatus",
    "reconciliationPending",
    "manualReviewReason",
    "paidAt",
    "cancelledAt",
    "lastProviderSyncAt",
    "occurredAt",
    "createdAt",
    "updatedAt",
];

export async function successfulPayment(body: JsonRecord, clientReferenceId: string): Promise<JsonRecord> {
    return {
        paymentId: 1,
        providerPaymentId: 1,
        clientReferenceId,
        financialTermsHash,
        financialRevision: 1,
        buyerUserId,
        sellerUserId,
        stripePaymentIntentId: "pi_1",
        stripeChargeId: "ch_1",
        stripeChargeBalanceTransactionId: "txn_charge_1",
        providerEventId: null,
        transferGroup: await transferGroup(clientReferenceId),
        currency: "eur",
        amountTotal: 1200,
        sellerTransferAmount: 1080,
        platformRetainedAmount: 120,
        refundedAmount: 0,
        transferredAmount: 0,
        reversedAmount: 0,
        actualStripeChargeFeeAmount: 65,
        actualStripeRefundFeeAmount: 0,
        actualStripeProcessingFeeAmount: 65,
        actualStripeChargeNetAmount: 1135,
        actualStripeFeeCurrency: "eur",
        actualStripeChargeFeeDetails: [{ type: "stripe_fee", amount: 65, currency: "eur" }],
        actualPlatformMarginAfterStripeAmount: 55,
        paymentStatus: "succeeded",
        commercePaymentStatus: "succeeded",
        settlementStatus: "held",
        disputeStatus: "none",
        reconciliationPending: false,
        manualReviewReason: null,
        paidAt: body.paidAt,
        cancelledAt: null,
        lastProviderSyncAt: body.lastProviderSyncAt,
        occurredAt: "2026-07-06T12:10:00.000Z",
        createdAt: "2026-07-06T12:05:00.000Z",
        updatedAt: "2026-07-06T12:10:00.000Z",
    };
}
