import type { SourceEndpoint } from "@bernouy/cms-sources";
import { array, boolean, endpoint, fulfillmentAddressShape, number, object, string } from "../builders";

export const deliveryQuoteEndpoints: SourceEndpoint[] = [
    endpoint(
        "resolveDeliveryQuote",
        "POST",
        "/resolveDeliveryQuote",
        object({
            quoteId: string(),
            externalOrderId: string(),
            orderVersion: number(),
            revision: number(),
            selectedForCmsUserId: { type: "string", semantic: "user-id" },
            relayLocation: string(),
            country: string(),
            number: string(),
            name: string(),
            addressLine1: string(),
            addressLine2: string(),
            postalCode: string(),
            city: string(),
            weightGrams: number(),
            shippingAmount: number(),
            currency: string(),
            merchandiseSubtotalMinorAmount: number(),
            quotedAt: string(),
            expiresAt: string(),
            recipientSnapshot: fulfillmentAddressShape(),
            sellerFulfillmentSnapshot: fulfillmentAddressShape(),
        }),
        undefined,
        {
            quoteId: string(),
            externalOrderId: string(),
            selectedForCmsUserId: { type: "string", semantic: "user-id" },
            orderVersion: number(),
            merchandiseSubtotalMinorAmount: number(),
            currency: string(),
            purpose: string(),
        },
        "system",
    ),
    endpoint(
        "relaySelection",
        "GET",
        "/relaySelection",
        object({
            relayLocation: string(),
            weightGrams: number(),
        }),
        { externalOrderId: string() },
        undefined,
        "system",
    ),
    endpoint(
        "saveClaimReturnRelaySelection",
        "POST",
        "/saveClaimReturnRelaySelection",
        object({
            externalOrderId: string(),
            relayLocation: string(),
            country: string(),
            number: string(),
            name: string(),
            postalCode: string(),
            city: string(),
            weightGrams: number(),
            shippingAmount: number(),
            currency: string(),
        }),
        undefined,
        {
            externalOrderId: string(),
            relayLocation: string(),
            country: string(),
            postalCode: string(),
            city: string(),
        },
        "system",
    ),
    endpoint(
        "saveRelaySelection",
        "POST",
        "/saveRelaySelection",
        object({
            externalOrderId: string(),
            relayLocation: string(),
            country: string(),
            number: string(),
            name: string(),
            postalCode: string(),
            city: string(),
            weightGrams: number(),
            shippingAmount: number(),
            currency: string(),
        }),
        undefined,
        {
            externalOrderId: string(),
            relayLocation: string(),
            country: string(),
            postalCode: string(),
            city: string(),
        },
        "system",
    ),
];
