create table if not exists commerce.notification_configuration (
    id text primary key default 'default',
    mode text not null default 'builtin',
    updated_at timestamptz not null default now(),
    constraint notification_configuration_singleton check (id = 'default'),
    constraint notification_configuration_mode check (mode in ('builtin', 'external', 'disabled'))
);

insert into commerce.notification_configuration (id, mode)
values ('default', 'builtin')
on conflict (id) do nothing;

create table if not exists commerce.notification_rules (
    key text primary key,
    event_type text not null constraint notification_rules_event_type_key unique,
    label text not null,
    description text not null,
    policy text not null,
    template_key text not null,
    stale_policy text not null,
    enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint notification_rules_key_format check (key ~ '^[a-z0-9][a-z0-9_.-]{1,120}$'),
    constraint notification_rules_policy check (policy in ('required', 'default_on', 'opt_in')),
    constraint notification_rules_stale_policy check (
        stale_policy in ('always_send', 'drop_if_superseded')
    )
);

create table if not exists commerce.notification_user_preferences (
    cms_user_id text not null,
    rule_key text not null references commerce.notification_rules(key) on delete cascade,
    enabled boolean not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (cms_user_id, rule_key),
    constraint notification_preferences_user_not_blank check (length(btrim(cms_user_id)) > 0),
    constraint notification_preferences_user_length check (length(cms_user_id) <= 512)
);

create table if not exists commerce.notification_events (
    id bigint generated by default as identity primary key,
    event_key text not null constraint notification_events_event_key_key unique,
    contract_version integer not null default 1,
    event_type text not null,
    aggregate_type text not null,
    aggregate_id text not null,
    aggregate_version bigint not null,
    occurred_at timestamptz not null,
    payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint notification_events_key_not_blank check (length(btrim(event_key)) > 0),
    constraint notification_events_version_positive check (contract_version > 0 and aggregate_version > 0),
    constraint notification_events_payload_object check (jsonb_typeof(payload) = 'object'),
    constraint notification_events_payload_size check (pg_column_size(payload) <= 65536)
);

create table if not exists commerce.notification_deliveries (
    id uuid primary key default gen_random_uuid(),
    event_id bigint not null references commerce.notification_events(id) on delete restrict,
    rule_key text not null references commerce.notification_rules(key) on delete restrict,
    recipient_cms_user_id text not null,
    channel text not null default 'email',
    status text not null default 'pending',
    attempts integer not null default 0,
    available_at timestamptz not null default now(),
    claim_expires_at timestamptz,
    claimed_by text,
    provider_message_id text,
    last_error text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    delivered_at timestamptz,
    constraint notification_deliveries_unique unique (event_id, rule_key, recipient_cms_user_id, channel),
    constraint notification_deliveries_recipient_not_blank check (length(btrim(recipient_cms_user_id)) > 0),
    constraint notification_deliveries_recipient_length check (length(recipient_cms_user_id) <= 512),
    constraint notification_deliveries_channel check (channel = 'email'),
    constraint notification_deliveries_status check (
        status in ('pending', 'processing', 'retry', 'delivered', 'dead_letter', 'suppressed')
    ),
    constraint notification_deliveries_attempts check (attempts >= 0 and attempts <= 100)
);

create index if not exists notification_deliveries_claim_idx
    on commerce.notification_deliveries(status, available_at, created_at)
    where status in ('pending', 'retry', 'processing');
create index if not exists notification_deliveries_recipient_idx
    on commerce.notification_deliveries(recipient_cms_user_id, created_at desc);
create index if not exists notification_events_aggregate_idx
    on commerce.notification_events(aggregate_type, aggregate_id, aggregate_version desc);
